### ISSUE TITLE
Getting 404 errors on browsing through uploaded images

### ISSUE THREAD

**Issue by kevgathuku** [django-ckeditor/django-ckeditor#146]
After following the installation instructions and implementing the CKEditor on the admin interface, I am unable to insert images after uploading them.

I am getting 404 errors when I try to browse through the images I have uploaded.

This is a screenshot of the screen I am getting. Any help would be appreciated.
![screenshot from 2014-11-16 22 05 21](https://cloud.githubusercontent.com/assets/3721994/5062766/c2f6b4d4-6ddc-11e4-8892-c32973d37e00.png)

**Comment by ironhouzi** [comment]
Is this for your development environment? If so, try adding this to your main urls.py:

```python
# .. imports
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    # ... urlconfs
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```
Worked on Django 1.7 with both python 2.7 and 3.4

**Comment by yunyanike** [comment]
@kevgathuku  check the varliable MEDIA_URL = '/media/'  not MEDIA_URL = 'media/'

**Comment by pkaramol** [comment]
I am having the same problem on a virtualenv with Django 1.8 and Python 3.5.1+

I have already taken care of this

```
urlpatterns = patterns('',
    # ... urlconfs
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```
 and using the following configurations

```
############################ Static Files' Settings ###########################

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_cdn')

############################ Media Files' Settings ############################

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_cdn')

############################## CKEditor Settings ##############################

CKEDITOR_UPLOAD_PATH = os.path.join(BASE_DIR, MEDIA_ROOT, 'ckeditor_media')
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_IMAGE_BACKEND = 'pillow'

################################ Other Settings ###############################
```

Files seem to be uploaded but `GET` fails with 404 altgough the path its trying to access exists.
I have also made 777 for the media folder just for testing, but still no luck.

**Comment by riklaunim** [comment]
CKEDITOR_UPLOAD_PATH should be relative against MEDIA_ROOT.

**Comment by pkaramol** [comment]
Doesn't that statement:

`CKEDITOR_UPLOAD_PATH = os.path.join(BASE_DIR, MEDIA_ROOT, 'ckeditor_media')`

make it relative to `MEDIA_ROOT`?

In the filesystem it ends up beiing 1 level below `MEDIA_ROOT`.

Either way the files ARE indeed uploaded, the cannot seem to be accessible (at least by the dev server) that returns `404`

**Comment by riklaunim** [comment]
Yes, CKEDITOR_UPLOAD_PATH is intended to be relative against MEDIA_ROOT and it must then work. Check if MEDIA_ROOT is correct.

**Comment by pkaramol** [comment]
`MEDIA_ROOT` is correct, user file uploads are functional

**Comment by Muhammad-Subhan-Khan** [comment]
> Is this for your development environment? If so, try adding this to your main `urls.py`:
> 
> ```python
> # .. imports
> from django.conf.urls.static import static
> from django.conf import settings
> 
> urlpatterns = patterns('',
>     # ... urlconfs
> ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
> ```
> 
> Worked on Django 1.7 with both python 2.7 and 3.4

Best Solution, Still working in 2019
