### ISSUE TITLE
Photo resize if Pillow installed

### ISSUE THREAD

**Issue by dangayle** [django-ckeditor/django-ckeditor#150]
Is there a way to have django-ckeditor automatically create a resized photo upon upload? For instance, someone uploads a 3000x2000 px image, obviously too big for the web. Can we hood into Pillow somehow and set a max width/height or square thumbnail function?

**Comment by edouarobin** [comment]
Hello, I have done this feature (set max size for image upload) in a fork.
Take a look: https://github.com/appli-intramuros/django-ckeditor

You just have to set CKEDITOR_IMAGE_MAX_WIDTH and/or CKEDITOR_IMAGE_MAX_HEIGHT.

This feature only works with pillow backend.
