### ISSUE TITLE
How to modify django-ckeditor inline styles?

### ISSUE THREAD

**Issue by dangayle** [django-ckeditor/django-ckeditor#152]
Using django-ckeditor==4.4.6, how can I override the built-in ckeditor styles.js file to add some margins to the default object styles like the one listed below?

``` js
{
name: 'Styled image (left)',
element: 'img',
attributes: { 'class': 'left', 'margin-right': '1em' }
},
```

I don't want to directly modify the core styles.js file, but I'm guessing that maybe I can override it using Django's app template inheritance functionality?

Or can I somehow feed in a js plugin that contains the above style declaration?

**Comment by Tyrdall** [comment]
You can also modify the ``CKEDITOR_CONFIGS`` setting:

    CKEDITOR_CONFIGS = {
        'default': {
            'stylesSet': [
                {
                    "name": 'Lead',
                    "element": 'p',
                    "attributes": {'class': 'lead'},
                },
            ],
        },
    }

**Comment by SalahAdDin** [comment]
Interesting.

**Comment by serguitus** [comment]
I know this is old but it might still help someone. Consider using [this solution](https://github.com/django-ckeditor/django-ckeditor/issues/302). Keep in mind that ckeditor should go AFTER your app on settings.INSTALLED_APPS for the template override to work
