### ISSUE TITLE
Uploading images using AWS S3 storage works, but `browse images` is broken.

### ISSUE THREAD

**Issue by ironhouzi** [django-ckeditor/django-ckeditor#160]
![snapshot1](https://cloud.githubusercontent.com/assets/3307295/5833817/5ac8cd08-a157-11e4-91ee-51cfdceae938.png)

Clicking on the links will take you to the image. The links work just fine. I'm just missing the ability to embedd an image.

Adding an image by upload works just fine.

**settings.py**
```python
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# django-storage settings
AWS_STATIC = os.environ['AWS_STATIC']
AWS_MEDIA = os.environ['AWS_MEDIA']
AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
STATICFILES_STORAGE = 'ktl_website.s3storage.AWSStatic'
DEFAULT_FILE_STORAGE = 'ktl_website.s3storage.AWSMedia'
S3_URL = '//%s.s3.amazonaws.com/'
STATIC_URL = S3_URL % AWS_STATIC
MEDIA_URL = S3_URL % AWS_MEDIA


# ADMIN_MEDIA_PREFIX = ''.join((STATIC_URL, 'admin/'))


# ckeditor
MEDIA_ROOT = '/media/'
CKEDITOR_UPLOAD_PATH = 'uploads/'
# CKEDITOR_UPLOAD_PREFIX = '/media/uploads'
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {
    'default': {
        'entities': False,
        'entities_greek': False,
        'entities_latin': False,
    }
}


```

I'm using Heroku for hosting and I've ensured that Pillow is installed and `import PIL` works in my heroku shell.

**Comment by riklaunim** [comment]
So thumbnails are missing under generated URL, but original images are there?

**Comment by ironhouzi** [comment]
Thumbnails are being generated. I just verified that all the uploaded images have thumbnails and are accessible through the S3 interface along with the original images. I downloaded a tumbnail and verified that it wasn't corrupted in any way. For some reason, the thumbnails are not shown on the page and there's no button for `Embed Image` either. Just as what the image above is showing.

**Comment by riklaunim** [comment]
Can you check what browser console is reporting - like is it 404 or some forbidden error, or maybe the urls are wrong? I can't do S3 tests at the moment.

**Comment by ironhouzi** [comment]
The requests for the images aren't even made.
![ckeditor](https://cloud.githubusercontent.com/assets/3307295/5891244/73d43dce-a48a-11e4-8112-82a5a72fa02c.jpg)

**Comment by ironhouzi** [comment]
While trying to get more debug info and pictures of the console, not the network performance, the `Browse Server` butten suddenly stopped responding completely. I cannot get the button working at all.
![js_void_ckeditor](https://cloud.githubusercontent.com/assets/3307295/5891304/d9d64aa6-a48d-11e4-8852-a13495d17344.jpg)

**Comment by ironhouzi** [comment]
Just wanted to add my settings for static files. https://gist.github.com/ironhouzi/90bd16f25563fd28e029

Perhaps the problem stems from an incorrect configuration.

**Comment by ironhouzi** [comment]
This problem was resolved by adding this line to `settings.py`:

```python
AWS_QUERYSTRING_AUTH = False
```
