### ISSUE TITLE
Galleriffic to be replaced with some modern library

### ISSUE THREAD

**Issue by fed239** [django-ckeditor/django-ckeditor#161]
Galleriffic is over 5 years and not maintained anymore. It uses insecure jQuery 1.3.2 and Django CKEditor doesn't allow to disable or override it.

**Comment by riklaunim** [comment]
Are there any alternatives for it?

**Comment by fed239** [comment]
@riklaunim There is KCFinder (http://kcfinder.sunhater.com/), free CKFinder alternative.
Also I found this Galleriffic fork: https://github.com/iamvery/galleriffic It's not actively maintained, but at least have some problems solved

**Comment by riklaunim** [comment]
will have to look at it.
