### ISSUE TITLE
Works perfectly in admin but I can't have it on my pages (crispy-forms)

### ISSUE THREAD

**Issue by karimone** [django-ckeditor/django-ckeditor#167]
Hi everyone, the plugin works for the admin, but not for my pages. I checked the html and is the ckeditor widget, but is render as a normal TextField.

The javascript is accessible, no error in the javascript console. On admin works fine.
The jquery is already loaded in my settings through django-pipeline.

I use django-crispy-forms. Is it a problem?

**Comment by riklaunim** [comment]
Maybe the form media are affected/overridden and no initialization code is available? or maybe you have to explicitly add {{ myform.media }} tag?

**Comment by karimone** [comment]
yes, I have to explicit add it... thank you!
