### ISSUE TITLE
File upload for non-Staff members?

### ISSUE THREAD

**Issue by sliaqat** [django-ckeditor/django-ckeditor#169]
Hi, Is there a possibility to allow file uploads to non-staff members?

**Comment by riklaunim** [comment]
Yes, include those https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor/urls.py URL mappings on your own (not including that file) without the decorator.

**Comment by riklaunim** [comment]
But some validation is highly recommended.

**Comment by lip365** [comment]
adding that doesn't do it for production?
