### ISSUE TITLE
Upload files other than images (pdf, doc and so on)

### ISSUE THREAD

**Issue by rhymes** [django-ckeditor/django-ckeditor#170]
Is there a way out of the box to upload a whitelisted series of file types within the Link uploader inside Django-CKEditor?

I read the code and it seems to be allowing only images. 

Thanks

**Comment by rhymes** [comment]
I ended up doing something like this https://gist.github.com/rhymes/32526b198fbcbfb40c68

It's definitely a hack.

**Comment by riklaunim** [comment]
There is one pull request waiting. A decision must be made how to handle this. Does django-ckeditor should stick to ckeditor or should it provide wider functionality set.

**Comment by int-ua** [comment]
#153

**Comment by riklaunim** [comment]
Other files can be uploaded now, so closing this.
