### ISSUE TITLE
Classes/attributes disappear sometimes when switching between code view and wysiwyg view

### ISSUE THREAD

**Issue by abhay1** [django-ckeditor/django-ckeditor#175]
There are times when classes disappear when switching between code view and editor view. To be specific, I tried to add a class to a h3 element. When I switched back/opened the object, the class attribute had disappeared. When I created a "div" element through the editor and added a class, it persisted.
Also I tried to add a "data-transition-*" attribute but that also disappeared.

Thank you!

**Comment by abhay1** [comment]
ummmm... also any scripts disappear the moment there is a toggle between the source and the wysiwyg view

**Comment by riklaunim** [comment]
What browser and version did you use. Where there any JS errors in JS console?

**Comment by abhay1** [comment]
Chrome 42.0.2311.90

I did a little search and the issue isn't isolated with ckeditor. Example: http://ckeditor.com/forums/CKEditor/Javascript-Disappears
This was a leadup on what the ckeditor can filter out
http://docs.ckeditor.com/#!/guide/dev_advanced_content_filter

Any way to configure this through the django app?

**Comment by riklaunim** [comment]
You can try adding them in the config dictionary ( http://docs.ckeditor.com/#!/guide/dev_advanced_content_filter )
```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 300,
        'removePlugins': 'some value',
        'removeButtons': 'some value',
        'allowedContent': 'some value',
    },
}
```

It's translated to ckeditor settings in JS so you can compare and modify the dict so that it works as needed.

**Comment by matthiask** [comment]
@abhay1 did this work? If not please reopen. Thanks.
