### ISSUE TITLE
[Documentation Request] Installing ckeditor plugins

### ISSUE THREAD

**Issue by negativefix** [django-ckeditor/django-ckeditor#181]
I am trying to add plugins to my ckeditor but I could not find the instructions regarding where to put downloaded individual plugin files or ckeditor files built through ckeditor builder. 

If possible could you include this topic in the documentation? 

Thanks.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by riklaunim** [comment]
I don't know what are ckeditor exact requirements, but if it has to be in some specific subfolder then you can mimic it in your static folder so that after collectstatic you get the expected end result with plugins in given subfolder.

**Comment by negativefix** [comment]
Default location for ckeditor plugins is ```ckeditor/plugins```.  I am going to give a try what you suggested.  Thanks.

**Comment by int-ua** [comment]
Putting the folder in `static/ckeditor/ckeditor/plugins/` in one of apps worked.
