### ISSUE TITLE
Remove file management and provide some sort of third-party application integration method

### ISSUE THREAD

**Issue by riklaunim** [django-ckeditor/django-ckeditor#182]
There is just to many ideas and needs about file uploads (file type, prefixing) and file upload widgets.

My current idea is to remove any file management features - just provide what the package name says - a CKEditor form field. As people want file management done as they need it there should be some way to integrate with the editor - I'll have to look what ckeditor has to say about this. Would be good to have this covered in the docs and to have at least one example for popular Django upload application/widget.

Suggestions, comments?

**Comment by riklaunim** [comment]
Looking at ckeditor 4.5.0 they added built in support for uploading drag and dropped images and media. Will have to check it, as it would solve problems with old gallerific widget being dead - and see if it must/should be supported by the package or exposed/binded to django file management app/apps.

**Comment by negativefix** [comment]
Being able to uploading drag and dropp media sounds nice. But what about images or files already uploaded via other file managers or django image/file fields. I usually find myself in one of the two situations while using ckeditor editor in django:

1. I upload already uploaded images via ckeditor gallerific widget or
2. Inputing urls into ckeditor' image widget for image files which were already uploaded via other file manager.

**Comment by int-ua** [comment]
I've used filebrowser and it works perfectly.

Had to load this JS:
'''
class Media:
            js = ('filebrowser/js/FB_CKEditor.js',)
'''
and just added to the `CKEDITOR_CONFIGS`
'''
'filebrowserBrowseUrl': '/admin/filebrowser/browse/?pop=3',
'''

**Comment by negativefix** [comment]
@ikresoft had django-ckeditor-filer app which provided integration between filer and ckeditor.As far as I know DjangoCMS also uses django-filer for file management and integration between ckeditor and django-filer is provided by django-ckeditor-filebrowser-filer app.

**Comment by luzfcb** [comment]
django-wysiwyg-redactor provides a simple way to customize the upload

https://github.com/douglasmiranda/django-wysiwyg-redactor#upload-handlers
https://github.com/douglasmiranda/django-wysiwyg-redactor/blob/master/redactor/handlers.py
https://github.com/douglasmiranda/django-wysiwyg-redactor/blob/master/redactor/views.py#L23-L73


it could at least serve as inspiration to create our own solution

**Comment by SalahAdDin** [comment]
:+1:

**Comment by ikresoft** [comment]
I am not using anymore this django-ckeditor-filebrowser-filer, so I figure out that is better to use some sort browser for all for example pictures, files, links for posts etc. This means that you can use browser for any kind of content just make plugin and register it. Unfortunately I dont have a time to finalize it its working for now but there some issue with design. So my point is use one browser for everything.

https://github.com/ikresoft/django-url-browser, old project is (django-nav-tree not using)

**Comment by riklaunim** [comment]
In current master I'm moving all file upload code to separate django application. This will allow using clean CKEdifor form field with other widgets and backends for upload.

**Comment by matthiask** [comment]
This has happened a long time ago. `ckeditor` and `ckeditor_uploader` are two different apps, both in django-ckeditor.
