### ISSUE TITLE
Image width and height not saved

### ISSUE THREAD

**Issue by int-ua** [django-ckeditor/django-ckeditor#184]
I've it up and it's working fine, but image style is dropped on saving. Any ideas on how to fix that?

Update: [workaround below](https://github.com/django-ckeditor/django-ckeditor/issues/184#issuecomment-95352678)

**Comment by riklaunim** [comment]
Does the editor set any classes, attributes to the IMG tag?

**Comment by int-ua** [comment]
Width and height are written to the style attribute: `style="height:677px; width:500px"`. I just switched the project from using TinyMCE and this problem appeared only on CKEditor. I guess they should go into attributes and Django is deleting all styles, is that so?

**Comment by int-ua** [comment]
It strips styles even with `'allowedContent': True` in the CKEDITOR_CONFIGS. Both with and without `'removePlugins': 'stylesheetparser'`

**Comment by int-ua** [comment]
https://dev.ckeditor.com/ticket/5547 (patch for 4.4.7 present) > http://docs.ckeditor.com/#!/guide/dev_acf-section-example%3A-disallow-inline-styles-and-use-attributes-instead

    'disallowedContent': 'img{width,height}',

doesn't help, it just hides width and height fields completely in the dialogue.

**Comment by int-ua** [comment]
https://github.com/ckeditor/ckeditor-dev/pull/157

**Comment by int-ua** [comment]
Replacing `static/ckeditor/ckeditor/plugins/image/dialogs/image.js` with https://dev.ckeditor.com/attachment/ticket/5547/image.js doesn't seem to help. Verified that browser loaded the correct one by checking copyright years.

**Comment by int-ua** [comment]
Switching to the [image2](http://ckeditor.com/addon/image2) plugin helped. Just unpacked `image2`, `widget` and `lineutils` into `static/ckeditor/ckeditor/plugins/` directory of an activated app and added

    'extraPlugins': 'image2',

to the `CKEDITOR_CONFIGS`

**Comment by riklaunim** [comment]
gallerific and some other addons are getting to old. One of reasons for bigger changes in upcoming releases.
