### ISSUE TITLE
Error constructing the URL for django-storages when using django-configurations and other

### ISSUE THREAD

**Issue by jdcaballerov** [django-ckeditor/django-ckeditor#187]
Hi,

When using django-configurations it happens that URL are malformed

```
<script src="https://s3.amazonaws.com/<Value default: None>/ckeditor/ckeditor/ckeditor.js" type="text/javascript"></script>
```

This happens because when using [django-configurations](https://github.com/jezdez/django-configurations) usually the bucket name is set as

```
AWS_STORAGE_BUCKET_NAME = values.SecretValue()
```

Then inside [widgets.py](https://github.com/django-ckeditor/django-ckeditor/blob/e8b9df963f4b66eff86df8cdb89e6623f5b33f64/ckeditor/widgets.py) the injected media is

```
try:
            js += (
                settings.STATIC_URL + 'ckeditor/ckeditor/ckeditor.js',
                settings.STATIC_URL + 'ckeditor/ckeditor-init.js',
            )

```

I think a better approach is to use 

```
from django.contrib.staticfiles.templatetags.staticfiles import static
url = static('ckeditor/ckeditor/ckeditor.js')
```

I think this way more cases with the storage can be handled.

When you mention on the docs

```
NOTE: django-ckeditor will not work with S3 through django-storages without this line in settings.py:

AWS_QUERYSTRING_AUTH = False
```

Isnt it an issue with [CORS](https://www.caktusgroup.com/blog/2014/11/10/Using-Amazon-S3-to-store-your-Django-sites-static-and-media-files/) and this ?

best,

**Comment by riklaunim** [comment]
Yes, definitely there shouldn't be any settings.STATIC_URL there.

**Comment by riklaunim** [comment]
New version released with the latests commits. I'm not using AWS now so I can't say much about the config.

**Comment by riklaunim** [comment]
Temporarily settings.STATIC_URL can't be replaces with static() as it causes some problems with cached storages. That would have to be solved first.

**Comment by matthiask** [comment]
Thanks! We're in the process of fixing this. See https://github.com/django-ckeditor/django-ckeditor/pull/377 and many many other issues and pull requests :-)
