### ISSUE TITLE
upload form acton url，I want to add a type parameter

### ISSUE THREAD

**Issue by shmilyoo** [django-ckeditor/django-ckeditor#189]
like this 
filebrowserImageBrowseUrl :  '/ckfinder/ckfinder.html?Type=Images',
filebrowserFlashBrowseUrl :  '/ckfinder/ckfinder.html?Type=Flash',

then I can do something in ImageUploadView function to check the file type。 now it only support images

**Comment by riklaunim** [comment]
The idea is to separate ckeditor form field from default uploader as well as provide some support for custom uploaders that can handle various file formats.

PS. flash is dead.
