### ISSUE TITLE
django 1.8.2 error

### ISSUE THREAD

**Issue by bradrice** [django-ckeditor/django-ckeditor#191]
I'm getting an error in the ckeditor/widget.html template. This doesn't seem to happen in django 1.8.

in template /Users/brad2/Sites/braddev/lib/python3.4/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 19
ckeditor/widget.html
9 {% for field in line %}
10 
11 {% if not line.fields|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
12 {% if field.is_checkbox %}
13 {{ field.field }}{{ field.label_tag }}
14 {% else %}
15 {{ field.label_tag }}
16 {% if field.is_readonly %}
17

{{ field.contents }}

18 {% else %}
19
  {{ field.field }}
20 {% endif %}
21 {% endif %}
22 {% if field.field.help_text %}
23

{{ field.field.help_text|safe }}

24 {% endif %}
25 
26 {% endfor %}
27 
28 {% endfor %}
29 n template /Users/brad2/Sites/braddev/lib/python3.4/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 19
ckeditor/widget.html
9 {% for field in line %}
10 
11 {% if not line.fields|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
12 {% if field.is_checkbox %}
13 {{ field.field }}{{ field.label_tag }}
14 {% else %}
15 {{ field.label_tag }}
16 {% if field.is_readonly %}
17
{{ field.contents }}

18 {% else %}
19
  {{ field.field }}
20 {% endif %}
21 {% endif %}
22 {% if field.field.help_text %}
23

{{ field.field.help_text|safe }}

24 {% endif %}
25 
26 {% endfor %}
27 
28 {% endfor %}
29

**Comment by riklaunim** [comment]
what type of an error?

**Comment by bradrice** [comment]
I must have something setup wrong, because it is working on my production server, but not locally.

The error is:

AttributeError at /admin/zinnia/entry/add/
'str' object has no attribute '_meta'

**Comment by riklaunim** [comment]
The app doesn't use _meta model API so the error may be somewhere else. Check the stacktrace. In 1.8.1/2 they added some fixes.

**Comment by bradrice** [comment]
Thanks. Is this it?

  399.         klass.__str__ = lambda self: mark_safe(klass_str(self))
File "/Users/brad2/Sites/braddev/lib/python3.4/site-packages/django/forms/forms.py" in __str__
  543.         return self.as_widget()
File "/Users/brad2/Sites/braddev/lib/python3.4/site-packages/django/forms/forms.py" in as_widget
  599.         return force_text(widget.render(name, self.value(), attrs=attrs))
File "/Users/brad2/Sites/braddev/lib/python3.4/site-packages/django/contrib/admin/widgets.py" in render
  284.         rel_opts = self.rel.to._meta

Exception Type: AttributeError at /admin/zinnia/entry/add/
Exception Value: 'str' object has no attribute '_meta'

**Comment by riklaunim** [comment]
django-ckeditor is now tested with tox against Django  1.8.2 and Python 2.7 / 3.4 and it passes so it's unlikely that this app is causing this exception.
