### ISSUE TITLE
how to add plugins or skin ?

### ISSUE THREAD

**Issue by n37r06u3** [django-ckeditor/django-ckeditor#193]
I want to add some more plugin to django-ckeditor.
But found that the plugin directory was located at site-packages dir..

**Comment by SalahAdDin** [comment]
well, i asked long time ago and @riklaunim say me that they don't put other plugins if aren't necesseary, so, i download the skin or plugin in the site package directory and unzip it, it's all. Ah, you need put in the ckeditor config :D

**Comment by riklaunim** [comment]
static files go into static files directory. If you put plugin ins a ckeditor/ckeditor/plugins subfolder it will work. Collectstatic will merge all files and folders and you will get typical ckeditor setup.

**Comment by n37r06u3** [comment]
thx , I put them to static/ckeditor/ckeditor/plugins and it works.
But I got a new problem .
How to config more extraPlugins in settings.py


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source', 'codesnippet','pbckcode']
        ],
        'height': 300,
        'extraPlugins': ['pbckcode', 'codesnippet']
    },
}

it not work  with 
'extraPlugins': ['pbckcode', 'codesnippet']

it seems extraPlugins can not parse the list config string..

**Comment by riklaunim** [comment]
What's the JS output of it?

**Comment by n37r06u3** [comment]
if extra_plugins:
            self.config['extraPlugins'] = ','.join(extra_plugins)

I found the parse code, solve my problem.

**Comment by BhuwanPandey** [comment]
I had used youtube plugin, it show on ckeditor but after saving the object.
I didnot get that video. what might be the problem?

**Comment by SalahAdDin** [comment]
> I had used youtube plugin, it show on ckeditor but after saving the object. I didnot get that video. what might be the problem?

It is better if you create a new issue so people can focus on it and help you better.
