### ISSUE TITLE
When order SortableStackedInline CKEditor iframe content disappears

### ISSUE THREAD

**Issue by cubiczx** [django-ckeditor/django-ckeditor#194]
When order SortableStackedInline CKEditor iframe content disappears, this not occurs with other editors as django-suit-redactor.

**Comment by paul-apacio** [comment]
I have also observed this.  The content is still there in the hidden textarea, but the wysiwig is essentially crashed.  I'd hazard a guess that the editor needs to be reinitialised.

**Comment by cubiczx** [comment]
I detect that problem is with iframe element if change for DIV works fine.

**Comment by SalahAdDin** [comment]
Please, Do a PR with your fixed in this repository, maybe can be very useful for the next release.

**Comment by cubiczx** [comment]
I use a plugin: divarea and set this in ckeditor settings:  'extraPlugins': 'divarea' http://ckeditor.com/addon/divarea

**Comment by SalahAdDin** [comment]
very interesting, will be a good fix, say it to @darklow in django-ckeditor.
