### ISSUE TITLE
Problem with image upload

### ISSUE THREAD

**Issue by efeniks** [django-ckeditor/django-ckeditor#197]
Hello!
I have problem with image upload in Django-CKEditor. When i want upload image I see this:

Are You have any idea what is wrong?
![problem](https://cloud.githubusercontent.com/assets/10468499/8034972/2c702674-0ded-11e5-8b16-2b918c4f63f5.jpg)

I use:
Linux Ubuntu (but in Windows is the same)
Django 1.8.2 (but in 1.7 is the same)
In CKEditor-Demo is the same

Thank You!
eFeniks

**Comment by riklaunim** [comment]
Exception have been thrown. Check what it is.

**Comment by efeniks** [comment]
I have this error in my terminal:

"POST /ckeditor/upload/?CKEditor=id_content&CKEditorFuncNum=1&langCode=en HTTP/1.1" 500 127763

**Comment by riklaunim** [comment]
Warning isn't an exception. Check in that mini iframe what is the exception message.

**Comment by efeniks** [comment]
When I press F12 in Firefox I see only: Method getAttributeNode () is deprecated. Use the getAttribute ().

**Comment by riklaunim** [comment]
That's javascript. If you have firebug select the "yellow" iframe and edit it styles to be larget - there you will see a standard django exception page. The iframe is very small and that's why you can't see anything there by default.

**Comment by efeniks** [comment]
Thank You very much riklaunim. You are the best! That was "decoder jpeg not available".

**Comment by riklaunim** [comment]
pillow not compile with jpeg support?

**Comment by efeniks** [comment]
I use "sudo apt-get install libjpeg-dev" and reinstall Pillow. I don't know why Pillow no compile earlier.

**Comment by riklaunim** [comment]
Problem solved?

**Comment by efeniks** [comment]
Yes. Thank You
