### ISSUE TITLE
4.4.8 and setuptools incompatibility

### ISSUE THREAD

**Issue by hedleyroos** [django-ckeditor/django-ckeditor#199]
Scenario: simple setup.py with django-ckeditor in install_requires. Create a virtualenv and run ./ve/bin/python setup.py install.

With 4.4.7 an unpacked egg is created. Since 4.4.8 the egg is not unpacked. Django can't see inside the egg in that case. Here are functionally equivalent Django products on Travis. https://travis-ci.org/praekelt/jmbo-post/builds/59877446 works with 4.4.7 and https://travis-ci.org/praekelt/jmbo-video/builds/68122923 fails with 4.4.8. 

I have looked at the ckeditor source but can't see an issue. Pip doesn't exhibit the issue. Did something change in your build process?

**Comment by riklaunim** [comment]
setup.py did not change from a long time.

**Comment by SalahAdDin** [comment]
Other problem with 4.4.8,

**Comment by riklaunim** [comment]
I've released 4.5.0. You can check that.

**Comment by SalahAdDin** [comment]
Ok man, so soon, thank you,

**Comment by luzfcb** [comment]
@riklaunim 
fixed in https://github.com/django-ckeditor/django-ckeditor/commit/c32e6fa857464a331030d479169835764a238bc6 because was added `zip_safe=False,` on `setup.py` configuration

**Comment by riklaunim** [comment]
Then closing :+1:
