### ISSUE TITLE
admin url required

### ISSUE THREAD

**Issue by williamhrs** [django-ckeditor/django-ckeditor#200]
I have a different subdomain for admins url, so I don't have admin setup on my urls.py app.

When I try to upload something I get the following error: 'admin' is not a registered namespace

If I try to manually put the admin url on the app just to see if it works it asks to login on the admin section, which is not the case for the app.

**Comment by riklaunim** [comment]
there is a login_required decorator on the upload urls so if you don't really want to you can put those two url definitions directly without the decorator. You should be able also to configure your project in a way that those ckeditor urls are on the admin subdomain and not the main one.

**Comment by williamhrs** [comment]
That was really my bad, I found it out a little bit after I posted this. nvm
