### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by MineDoubleSpace** [django-ckeditor/django-ckeditor#201]
ckeditor/views.py", line 134, in get_files_browse_urls  'visible_filename': visible_filename,
UnboundLocalError: local variable 'visible_filename' referenced before assignment

        files.append({
            'thumb': thumb,
            'src': src,
            'is_image': is_image(src),
            'visible_filename': visible_filename, # visible_filename has not been assigned. 
        })

**Comment by riklaunim** [comment]
That's a bug.

**Comment by riklaunim** [comment]
Solved already by a pull request.
