### ISSUE TITLE
config.extraPlugins command from CKEditor's config.js not being honored

### ISSUE THREAD

**Issue by DanAtShenTech** [django-ckeditor/django-ckeditor#202]
QUICK OVERVIEW:  Trying to have the Stylesheet parser plugin populate the Styles dropdown from an external css, but it won't.  A look at the rendered HTML shows the following:  data-external-plugin-resources="[]".  Seems like the     config.extraPlugins = 'stylesheetparser';   command in config.js is not being honored in the Django implementation.

I am using CKEditor via a RichTextField.  It appears fine and the CKEDITOR_CONFIGS in settings.py is honored when the editor is displayed (copy of CKEDITOR_CONFIGS below for your convenience).  However, I am trying to implement the stylesheetparser plugin for CKEditor (http://ckeditor.com/addon/stylesheetparser), and I can't get the Styles dropdown to populate from an external stylesheet.  Implementation instructions are here (and I have followed them exactly):
http://docs.ckeditor.com/#!/guide/dev_styles-section-the-stylesheet-parser-plugin

In fact, I first created a custom build on the CKEditor site with the Stylesheet Parser plugin included.  When that didn't work, I noticed that the Plugins file didn't include the Stylesheet Parser plugin, so I downloaded it separately and included the Stylesheet Parser directory in the Plugins directory.

Below is my full config.js file:

```
CKEDITOR.editorConfig = function( config ) {
    config.stylesSet = [];
    config.extraPlugins = 'stylesheetparser';
    config.contentsCss = '/media/css/styles.css';
    config.stylesheetParser_validSelectors = /^(p|span|h1|h2|h3|h4|h5|h6).\w+/;
    config.stylesheetParser_skipSelectors = /(^body.|^caption.|^.)/i;
};
```

I have a valid CSS file that is loaded and IS applied to the content area within CKEditor, however, I CANNOT get the styles to be loaded into the Styles dropdown.  The file widget.html includes:  data-external-plugin-resources='{{external_plugin_resources|safe}}'.  A look at the rendered HTML shows data-external-plugin-resources="[]".  I am using the latest version (4.5.1).  Could there be an error in the **init** routine of class CKEditorWidget where it is parsing the configuration from settings.  Here are the first few lines of the routine:

```
    def **init**(self, config_name='default', extra_plugins=None, external_plugin_resources=None, _args, *_kwargs):
        super(CKEditorWidget, self).**init**(_args, *_kwargs)
        # Setup config from defaults.
        self.config = DEFAULT_CONFIG.copy()
```

```
    # Try to get valid config from settings.
    configs = getattr(settings, 'CKEDITOR_CONFIGS', None)
    if configs:
```

---
## Your attention to this would be greatly appreciated as it is a waste of time to re-create a separate style sheet for the Styles dropdown.  Thank you.

From settings.py
```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': [['Source'],["Styles","Format","ShowBlocks"],["Scayt"],
                ['Bold','Italic','-', "Subscript","Superscript",'-','NumberedList', 'BulletedList','-',"Indent", "Outdent",'-','JustifyLeft', 'JustifyCenter',
                 'JustifyRight', 'JustifyBlock'],
                ["Link","Unlink"],['Undo', 'Redo'], 
                ["Maximize"]], 
    },
}
```

**Comment by pbassut** [comment]
+1

**Comment by luzfcb** [comment]
try this https://github.com/django-ckeditor/django-ckeditor/issues/207#issuecomment-136912435

**Comment by matthiask** [comment]
Thanks, this sounds like the issue in #207. Please reopen if this is still an issue.
