### ISSUE TITLE
cannot upload image without admin authority

### ISSUE THREAD

**Issue by ethe** [django-ckeditor/django-ckeditor#204]
can upload image by administrator, but if used user authority,  it will throw an exception like this:
![2015-08-06 20 39 11](https://cloud.githubusercontent.com/assets/12211036/9113089/254c0dba-3c85-11e5-9e3f-10e5fcbdcdda.png)
how to config the authority?

**Comment by riklaunim** [comment]
The urls have staff_member_required by default - https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor/urls.py - if you want to change add those two urls instead of including the urls file, and modify as needed.

**Comment by ethe** [comment]
thx:smile:, i've already solved this problem
