### ISSUE TITLE
how to restrict file types on uploader

### ISSUE THREAD

**Issue by v1k45** [django-ckeditor/django-ckeditor#209]
the current app allows us to upload anything to the server, is there any way to restrict file types to images and documents only?

**Comment by riklaunim** [comment]
You would have to implement custom ImageUploadView and hook the URL to it. Sadly all logic is in one method at the moment so most of the code will have to be copyed.

**Comment by v1k45** [comment]
I edited the ImageUploadView:
```python
try:
    backend.image_verify(upload)
except utils.NotAnImageException:
    # pass
    return HttpResponse("""
    <script type='text/javascript'>
        alert('Must be an image file.');
    </script>
    """)
```
