### ISSUE TITLE
Can't set extraPlugins

### ISSUE THREAD

**Issue by pbassut** [django-ckeditor/django-ckeditor#210]
Something weird is happening to me.
I was trying to set extraPlugins on my development enviroment and it was working at all. I had a really bad time trying to do this. And then, suddenly when I refresh the page the plugin I was trying to add(mathAjax) was there. It couldn't be cache because I did a hardreload and even changed browsers(I was going crazy, yeah).

And then I deployed my code and for my surprise the button is gone. Not even a little change happened(I added another button I can't remember). I went to the JSON that gets rendered along with the widget template and my plugin is not there. So looks like it's not CKEditor's fault.

Any tips of what might be the problem on my prod env?

**Comment by riklaunim** [comment]
Did that example from another issue helped?

**Comment by pbassut** [comment]
It did! Thanks
