### ISSUE TITLE
unreleased 4.5.3 version not include all plugins

### ISSUE THREAD

**Issue by luzfcb** [django-ckeditor/django-ckeditor#212]
hello, after I send the pull-request https://github.com/django-ckeditor/django-ckeditor/pull/208 , I realized that was not included on all available plugins: https://github.com/ckeditor/ckeditor-dev/tree/4.5.3/plugins

it happened because the [ckeditor build script](https://github.com/ckeditor/ckeditor-dev/blob/4.5.3/dev/builder/build.sh) does not include all plugins.

I tried to include the names of all the plugins in [this configuration file](https://github.com/ckeditor/ckeditor-dev/blob/4.5.3/dev/builder/build-config.js), and run the build script again, however, it again did not include all the plugins.

I have not figured out how to set up [build.sh](https://github.com/ckeditor/ckeditor-dev/blob/4.5.3/dev/builder/build.sh), to make it include all the plugins

step by step than I did:

``` bash
luzfcb@luzfcb:~$ git clone https://github.com/ckeditor/ckeditor-dev.git
luzfcb@luzfcb:~$ cd ckeditor-dev
luzfcb@luzfcb:~/ckeditor-dev$ git checkout 4.5.3
luzfcb@luzfcb:~/ckeditor-dev$ # count number of plugins
luzfcb@luzfcb:~/ckeditor-dev$ ls -1 plugins/ | wc -l
101
luzfcb@luzfcb:~/ckeditor-dev$ cd dev/builder/
luzfcb@luzfcb:~/ckeditor-dev/dev/builder$ ./build.sh
luzfcb@luzfcb:~/ckeditor-dev/dev/builder$ # count number of minified plugins 
luzfcb@luzfcb:~/ckeditor-dev/dev/builder$ ls -1 release/ckeditor/plugins/ | wc -l
58
```

**Comment by riklaunim** [comment]
Do we need all plugins that much? If they don't build them for some reason?

**Comment by matthiask** [comment]
I think we just ship the full package from http://ckeditor.com/download . If some plugins are missing, there's always extra_plugins and external_plugin_resources to help. 

Please reopen if you disagree strongly and are willing to do the work of building a custom CKEditor package. Thanks.
