### ISSUE TITLE
No module named "ckeditor.urls" in release 4.5.3

### ISSUE THREAD

**Issue by jungornti** [django-ckeditor/django-ckeditor#219]
Today we had some problems with few of our websites after updating django-ckeditor to 4.5.3 with error:

No module named "ckeditor.urls" in release 4.5.3

**Comment by riklaunim** [comment]
Now they are in: ckeditor_uploader.urls - all of file uploading code was moved to separate app.

**Comment by SalahAdDin** [comment]
I don't understand it.

**Comment by riklaunim** [comment]
What you don't understand? The code was moved, and it was a backward incompatible change - to extract all of file upload logic from the vanilla ckeditor form filed.

**Comment by SalahAdDin** [comment]
then, how can we put ckeditor upload logic in this release version?

**Comment by riklaunim** [comment]
I was only moved inside the package so only imports change. All the functionality is there, just people that want ckeditor-only have easy way to using it without file upload.

**Comment by jungornti** [comment]
Thank you for reply.

You did backward-incompatible change in minor release. You should consider to release version 4.6.0 and write and upgrade guide, or at least fix the readme:

    Add CKEditor URL include to your project's urls.py file:

    (r'^ckeditor/', include('ckeditor.urls')),


According to semver minor release should contain only fixes and not backward incompatible changes.
If you do not using semver, u should mention it in documentation, so people will know how to update your software.

**Comment by riklaunim** [comment]
Yes, there is a problem with versioning, as I'm trying to stick to CKEditor version. Will have to change that I guess.

**Comment by riklaunim** [comment]
Ok, versioning fixed: https://pypi.python.org/pypi/django-ckeditor/

**Comment by jungornti** [comment]
Perfect, thank you.
