### ISSUE TITLE
[SOLVED] Syntax highlighter plugin?

### ISSUE THREAD

**Issue by alzearafat** [django-ckeditor/django-ckeditor#220]
Hi,

First, thank you for this awesome app, it's really helpful... :)

How I can enable Syntax/Code Highlighter plugin?

Thank you,
Regards

**Comment by dafriis** [comment]
I came here to ask the same question but got it working. You can add configuration for the plugin in settings.py. The 'full' toolbar isn't needed, it's just an example:

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'extraPlugins': ','.join(
            [
                'codesnippet',
            ]),
    },
}

Further work is needed for the code to be properly highlighted on the front end ofc.
You can get more info for the plugin at http://docs.ckeditor.com/#!/guide/dev_codesnippet

**Comment by alzearafat** [comment]
Hi,

Thanks for reply, unfortunately it's not working on mine :(

The RichTextField become blank... The editor is gone somehow. Do you have another solution?

Thanks in advance,
Please excuse my English

**Comment by luzfcb** [comment]
@alzearafat full working sample config

```python
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'toolbar_MyCustomToolbar': [
            {'name': 'basic', 'items': [
                'Source',
                '-',
                'Bold',
                'Italic',
                'CodeSnippet'  # add the codesnippet button name
            ]}
        ],
        # https://github.com/django-ckeditor/django-ckeditor/tree/master/ckeditor/static/ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles
        # https://github.com/isagalaev/highlight.js/tree/master/src/styles
        'codeSnippet_theme': 'railscasts',
        # uncomment to restrict only those languages
        # 'codeSnippet_languages': {
        #     'python': 'Python Guru',
        #     'javascript': 'JavaScript Fu',
        #     'php': 'PHP Ninja',
        #     'c': 'You custom language name'
        # },
        'toolbar': 'MyCustomToolbar',
        'extraPlugins': ','.join(
            [
                # add the follow plugins
                'codesnippet',
                'widget',
                'dialog',
            ]),
    }
}
```

**Comment by riklaunim** [comment]
If there is no editor then you got a JavaScript error - check your browser JS console for it.

**Comment by dafriis** [comment]
I hope I include all the necessary steps here. Ofc you've already did a few of the steps since you got the editor working but I include everything just in case.

In settings.py:
Include 'ckeditor', under INSTALLED_APPS
Add the line CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'

In your template file:
Add:
```
<link rel="stylesheet" href="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/default.css' %}" />
<script src="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js' %}"></script>
```
Also include this script tag just before the `</body>` tag to get script fired up on the "frontend":
```
<script>hljs.initHighlightingOnLoad();</script>
```
DISCLAIMER: I'm also new to Django so I don't know if it's kosher to add script tags like this. But at least you get to see if it's working.

**Comment by alzearafat** [comment]
@luzfcb & @riklaunim : Ok, I found this error 

```
uncaught exception: [CKEDITOR.resourceManager.load] Resource name "codesnippet" was not found at "http://localhost:8000/static/ckeditor/ckeditor/plugins/codesnippet/plugin.js?t=F62B".
```

Acctually, there's no ckeditor inside static folder... :/

Thanks in advance

**Comment by dafriis** [comment]
After you've installed the editor per the instructions you have to collect the static files by running `./manage.py collectstatic`. Do that and if it's still not working I would go through the installation instructions again, twice.

**Comment by alzearafat** [comment]
[SOLVED]

Hi,

I already solved this issue. Simply by run collectstatic command... Thank you! :D

**Comment by luzfcb** [comment]
@alzearafat if is solved, please, close this issue.

**Comment by Prakalpit** [comment]
Hi, how do I make the code block copyable ?

**Comment by desphixs** [comment]
I want to highlight the code in the frontend??
