### ISSUE TITLE
MANIFEST.in doesn't included the ckeditor_uploader/templates/ckeditor/browse.html

### ISSUE THREAD

**Issue by lefterisnik** [django-ckeditor/django-ckeditor#221]
Today I tried the new django-ckeditor 5.0.1.

It seems that in MANIFEST.in file doesn't included the ckeditor_uploader/templates, which leads to the following error:

    TemplateDoesNotExist at /ckeditor/browse/

when you try to access, localhost:8000/ckeditor/browse/. I am supposing that, adding:
    
    recursive-include ckeditor_uploader/templates *

at MANIFEST.in the malfunction will be fixed.

**Comment by PhorlarinDjango** [comment]
I keep getting this error when I clink on browse in the image info tab please help and I get import error at ckeditor/upload in the upload tab when I click on send to server. please help. thanks.

**Comment by riklaunim** [comment]
Do you have the ckeditor and ckeditor_uploader in INSTALLED_APPS?

**Comment by PhorlarinDjango** [comment]
I have ckeditor_uploader in installed apps but I still get import error in the upload tab. Thanks for your help

**Comment by riklaunim** [comment]
you may need both, and check what the exception is saying. maybe it's something else too

**Comment by PhorlarinDjango** [comment]
I get the error 'ImportError at /ckeditor/upload/'  No module named image..
Might it have something to do with my file path?

**Comment by riklaunim** [comment]
Pillow not installed

**Comment by PhorlarinDjango** [comment]
Sorry for troubling you. I have the CKEDITOR_IMAGE_BACKEND = "pillow"
