### ISSUE TITLE
How can I make editor disable conditionally in django-ckeditor ?

### ISSUE THREAD

**Issue by nishuk0007** [django-ckeditor/django-ckeditor#222]
I have implemented ckeditor succesfully, but now looking for disable editor conditionally in django-ckeditor. I take a deep look at code but didn't find any option to make it disable. like I find in tinymce `TinyMCE(attrs={'cols': 120, 'rows': 30}, mce_attrs={'readonly' : 1})`.

Please guide me.

**Comment by matthiask** [comment]
The first hit on Google for "ckeditor readonly" is http://docs.ckeditor.com/#!/guide/dev_readonly

I just tested this, setting `readOnly` in a `CKEDITOR_CONFIGS` block works perfectly.
