### ISSUE TITLE
Include templatags or something like this in editor

### ISSUE THREAD

**Issue by V1ce** [django-ckeditor/django-ckeditor#224]
Hi,

I try to include a templatetags or an include tag in the admin editor widget but i can't, i think its normal that's a different lvl than the templates, so i try to find some advice about my need.

Context : 

My users will edit content of pages in the admin interface with ckeditor.

I have make a templatetags for include a picture gallery very easily, at list i have just to put something like {% gallery %} and its good.

For the moment the best way i have find is this : 
- When the content will show i have a templates for exemple with this 

{{ article.description | safe }}
and the content edited by the user with ckeditor is show
- So if they need to put a picture gallery they will open the template, delete this line {{ article.description | safe }} , copy past source code from the ckeditor admin editor and include the templatetags where they want.
- This is not very difficult but if i can not oblige them to manipulate html will better^^, but don't find a way for do this.

Hope im clear

Thanks for your advice.

**Comment by matthiask** [comment]
I think you should probably look into something more structured than a rich text editor if you need advanced functionality such as this. Sorry for the plug but I really think you should take a look at http://django-content-editor.readthedocs.io/en/latest/
