### ISSUE TITLE
Uploading image right from CKEditor

### ISSUE THREAD

**Issue by pbassut** [django-ckeditor/django-ckeditor#225]
Is this supported? Looks like there was a big change on the last version that moved everything to another app(Though I think this wasn't necessarily. Was there a discussion on this?). How can I upload images right from the editor?

**Comment by pbassut** [comment]
Nevermind, got it working by changing the ```CKEditorWidget``` to the new ```CKEditorUploadingWidget```

**Comment by bomba1990** [comment]
thanks!! for this comment, i think will be useful if add this to the docs. in the widgets section. like Field

**Comment by riklaunim** [comment]
It's already there ;)
