### ISSUE TITLE
AttributeError at /ckeditor/browse/

### ISSUE THREAD

**Issue by lciolecki** [django-ckeditor/django-ckeditor#227]
Hi!

When I try use search file option, then app raise error:

```python
Request Method:	POST
Request URL:	http://localhost:8000/ckeditor/browse/?CKEditor=id_content&CKEditorFuncNum=0&langCode=pl
Django Version:	1.8
Exception Type:	AttributeError
Exception Value:	'NoneType' object has no attribute 'lower'
Exception Location:	/home/vagrant/.virtualenvs/xyz/local/lib/python2.7/site-packages/ckeditor_uploader/views.py in <lambda>, line 164
Python Executable:	/home/vagrant/.virtualenvs/xyz/bin/python
```

I check this, and in file ckeditor_uploader/views.py on line 162:
 
```python
files = filter(lambda d: form.cleaned_data.get('q', '').lower() in d['visible_filename'].lower(), files)
```

And variable d['visible_filename'] is None. Maybe We can exclude / filter this variables with d['visible_filename'] == None?

My best regards,

**Comment by riklaunim** [comment]
Will look at it / fix it.

**Comment by Grimaldum** [comment]
I fixed the problem by myself, filling the 'visible_filename' value by simply assigning it the last part of the src value (the file name, actually). It works like a charm :)

ckeditor_uploader/views.py after line 140, in the else statement :
else:
            thumb = src
	    visible_filename = os.path.split(filename)[1]

I will try to do a pull request, will try to figure how to do it :)

**Comment by riklaunim** [comment]
fixed in master
