### ISSUE TITLE
How to enable other themes?

### ISSUE THREAD

**Issue by pythad** [django-ckeditor/django-ckeditor#228]
Is there a way to enable other themes? There is `office2013` in configs but I can't enable it also, I am getting white block only.

**Comment by luzfcb** [comment]
django-ckeditor is shipped only with the ``moono`` skin. you need to download the skin that you want, and put it on your static dir:

%STATIC_DIR%/ckeditor/ckeditor/skins/

**Comment by luzfcb** [comment]
django-ckeditor is shipped only with the ``moono`` skin. you need to download the skin that you want, and put it on your static dir:

%STATIC_DIR%/ckeditor/ckeditor/skins/

**Comment by pythad** [comment]
And then I just need to set 'skin': '****' in CKEDITOR_CONFIGS?

**Comment by luzfcb** [comment]
yes

**Comment by pythad** [comment]
This worked, thanks!
