### ISSUE TITLE
Content css

### ISSUE THREAD

**Issue by Kurdakov** [django-ckeditor/django-ckeditor#230]
it will be good to get an example to configure django-ckeditor to use additional css files
via
http://docs.ckeditor.com/#!/api/CKEDITOR.editor-method-addContentsCss

as far as I understand  - it is currently not possible to set custom css via config

**Comment by zabaat** [comment]
+1

**Comment by riklaunim** [comment]
If you set a path to a file in statics folder then it should just work.

**Comment by Kurdakov** [comment]
@riklaunim that sounds  something similar to offer to use html editor to make a site. Ofcause it is possible.
but the reason is the same why ckeditor has that method in a first place.  think of the feature is for cms where there is need to have css which is not known to admin site before hand and settings are configured in a page plugin which are added to main cms on occasion, and that plugin knows exactly which css it will use and can push it to admin configs

**Comment by riklaunim** [comment]
If it's not known when deploying the application then noting can be done on the Python side. You can play with using JavaScript code that will dynamically set some CSS file path when needed.

**Comment by Kurdakov** [comment]
@riklaunim 

it is known at deploy time. But django admin interface won't access arbitrary css file in static. So to allow to edit text in ckeditor in admin as it will appear on specific dynamically constructed page - there is need to configure ckeditor for specific page - letting it it know to use specific css.

**Comment by luzfcb** [comment]
Full working sample

```python
# settings.py
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'toolbar': 'Basic',
        'toolbar_Basic': [
            {'name': 'document', 'items': ['Save', ]},
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat', '-',
                       'PasteFromWord']},

            {'name': 'paragraph',
             'items': ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', 'NumberedList', 'BulletedList',
                       '-', 'Outdent', 'Indent', '-', 'Blockquote', '-',
                       ]},
            {'name': 'insert',
             'items': ['Table', 'HorizontalRule', 'SpecialChar', 'PageBreak']},

        ],
        'extraPlugins': ','.join(['sharedspace', 'save', 'autolink', ]),
        'removePlugins': ','.join(['resize', ]),
        'width': '21.0cm',
        'sharedSpaces': {
            'top': 'id-top-ckeditor-toolbar',
            'bottom': 'id-bottom-ckeditor-toolbar'
        },
        'contentsCss': 'html, iframe, body {overflow:hidden;outline: none;}',
    }
}
```

sample django template:
```html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div id="id-top-ckeditor-toolbar" class="foo-top-class">
    <!-- TOP toolbar CKEditor -->
</div>

<div id="content">
    {% if form %}
        <form method="post">
            {% csrf_token %}
            {{ form }}
        </form>
    {% endif %}

</div>

<div id="id-bottom-ckeditor-toolbar" class="foo-botton-class">
    <!-- Bottom toolbar CKEditor -->
</div>


<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>

<script src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>



{% if form %}
    {{ form.media }}
{% endif %}


</body>
</html>
```

**Comment by Kurdakov** [comment]
@luzfcb thanks - 

but could you please edit contentCss so that it assept css files?

@riklaunim 

it is known at deploy time. But django admin interface won't access arbitrary css file in static. So to allow to edit text in ckeditor in admin as it will appear on specific dynamically constructed page - there is need to configure ckeditor for specific page - letting it it know to use specific css.

edit: it might be possible to accomplish the task  using class Media in specific admin class in plugin though, but might be easier to use ckeditor config fo automatically constructed admin

**Comment by luzfcb** [comment]
@Kurdakov the original ckeditor contentsCss configuration assepts css files

http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-contentsCss

but I never tried to do this with django-ckeditor

**Comment by Kurdakov** [comment]
@luzfcb thanks a lot - I will try it

**Comment by filias** [comment]
I have tried to add my custom css file and still I can't see it overriding the original styles.
I have added it to my CKEDITOR_CONFIGS setting like this:
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'toolbar': [['Format'],
                    ['Bold', 'Italic', 'Undo', 'Redo'],
                    ['Link', 'Unlink'],
                    ['Image'],
                    ['SpecialChar'],
                    ['Source']],
        'tabSpaces': 4,
        'contentsCss': '/static/css/uploader.css',
    }
}

Any idea what am I doing wrong?

**Comment by matthiask** [comment]
Not sure why that wouldn't work apart from caching problems or the CSS file not being there at all. `contentsCss` works perfectly here.

@filias what do you get when you access `/static/css/uploader.css` in the browser?

**Comment by Harteg** [comment]
A possible workaround is to add the css with javascript

```
$(function() {
            setTimeout(function() {
                var $head = $(".cke_wysiwyg_frame").contents().find("head");
                var url = "{% static '<PATH-TO-YOUR-CSS>' %}";
                $head.append($("<link/>", { rel: "stylesheet", href: url, type: "text/css" } ));
            }, 2000); // Wait for CKEditor to init
        });
```

Where `.cke_wysiwyg_frame` is the class of the iframe.

**Comment by rmuktader** [comment]
@filias did you ever figure it out?

**Comment by filias** [comment]
@rmuktader not really, I didn't work on that project anymore... I hope you find out.

**Comment by rmuktader** [comment]
@filias doing this in the admin class is the only thing that worked for me.

`
    class Media:
        css = {
                'all': ('/static/css/rich-text-editor.css',)
            }`

**Comment by matthiask** [comment]
Yes. I'd recommend using `"all": ("css/rich-text-editor.css",)` and not adding the `/static/` prefix though. When using the former the name is mangled by `ManifestStaticFilesStorage` or other storages which may want other prefixes, such as when storing static files or S3 or so.

**Comment by saleemcoder** [comment]
> I have tried to add my custom css file and still I can't see it overriding the original styles.
> I have added it to my CKEDITOR_CONFIGS setting like this:
> 
> ```
> CKEDITOR_CONFIGS = {
>     'default': {
>         'skin': 'moono',
>         'toolbar': [['Format'],
>                     ['Bold', 'Italic', 'Undo', 'Redo'],
>                     ['Link', 'Unlink'],
>                     ['Image'],
>                     ['SpecialChar'],
>                     ['Source']],
>         'tabSpaces': 4,
>         'contentsCss': '/static/css/uploader.css',
>     }
> }
> ```
> 
> Any idea what am I doing wrong?

You need to add !important in your css that overwrite any other css

**Comment by jmfederico** [comment]
This is actually possible right now. You just need a lazy string:

```python
from django.templatetags.static import static
from django.utils.functional import lazy

CKEDITOR_CONFIGS = {
    "yourConfig": {
        ...
        "contentsCss": lazy(static, str)("custom/styles.css"),
        ...
    }
}
```
