### ISSUE TITLE
Best way to customize plugin

### ISSUE THREAD

**Issue by pacahon** [django-ckeditor/django-ckeditor#231]
Hello. Is there any way to customize plugin config? As I can see I can't do it with `CKEDITOR_CONFIGS`.

**Comment by nikolas** [comment]
I can't get `CKEDITOR_CONFIGS` to work either. For example, putting this in `settings.py` doesn't work, using django-ckeditor 4.5.1:

```python
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar': 'Basic',
    }
}
```

**Comment by matthiask** [comment]
Works for me. Also, this is a really old bug report. Please reopen if this still doesn't work.
