### ISSUE TITLE
Improve documentation for file uploader

### ISSUE THREAD

**Issue by shaung** [django-ckeditor/django-ckeditor#234]
It took me some time to figure out how to use the uploader to allow users uploading images.

Basically what I needed was to add the following items to `CKEDITOR_CONFIGS`:
```
'filebrowserImageBrowseUrl': '/ckeditor/browse/',
'filebrowserImageUploadUrl': '/ckeditor/upload/',
```

As this might be trivial for those who are familiar with ckeditor, including the description into the documentation would make a new-comer's life easier IMHO.

**Comment by riklaunim** [comment]
As far as I know no extra configuration is required (unless you are trying to use some other upload method).

**Comment by shaung** [comment]
@riklaunim That's weird.
I'm using and `django-ckeditor==5.0.2` with `django==1.8.5`.
With an empty config, upload tab is hidden in the image property dialog.
The browse button is not displayed either unless `filebrowserImageBrowseUrl ` is set.

**Comment by riklaunim** [comment]
is it in /admin/ or on custom views (that needs {{form.media}}) ?

**Comment by shaung** [comment]
@riklaunim It's in admin. My model is like,
```
from ckeditor.fields import RichTextField
class MyModel(models.Model):
    body = RichTextField()
```

**Comment by riklaunim** [comment]
RichTextField is non uploading. while RichTextUploadingField is with upload enabled.

**Comment by SalahAdDin** [comment]
:+1: Put these in the docs please.

**Comment by riklaunim** [comment]
It is, read it will you.

**Comment by shaung** [comment]
@riklaunim Wow thanks! Truly it is in the docs (and bolded). Can't believe I missed that...
