### ISSUE TITLE
Missing upload image option

### ISSUE THREAD

**Issue by TheDrifter254** [django-ckeditor/django-ckeditor#237]
![snapshot](https://cloud.githubusercontent.com/assets/1306817/11076670/0ff95b10-880d-11e5-9b01-54fd1b82a17e.jpg) I upgraded from django 1.5 to 1.7 and ckeditor 5.0.2 it works but the image tab for upload is missing.

**Comment by riklaunim** [comment]
5.X has moved file upload support to new classes (allowing to use CKEditor with or without it). Check the readme for new class names.

**Comment by m-thielen** [comment]
@riklaunim Maybe you should mention CKEditorUploadingWidget in the readme... ;-)

**Comment by riklaunim** [comment]
RichTextUploadingField is mentioned ;) But CKEditorUploadingWidget could be too.

**Comment by riklaunim** [comment]
added.
