### ISSUE TITLE
Removing auto-paragraph feature

### ISSUE THREAD

**Issue by pbassut** [django-ckeditor/django-ckeditor#238]
I don't want to include a p if there's only one line. 

In practice I want that when I type ``` text here``` it becomes exactly that instead of ```<p>a text here</p>```.
And if I press enter it would include the p.

If only removing the p can be done it's fine.

Thanks.

**Comment by luzfcb** [comment]
Try ckeditor enterMode configuration:

docs.ckeditor.com/?mobile=/api/CKEDITOR.config#cfg-enterMode
Em 11/11/2015 22:33, "Patrick Bassut" <notifications@github.com> escreveu:

**Comment by pbassut** [comment]
I tried it using the django ckeditor settings. And it didn't work. It keeps outputting p's.

Should I set it some other way?

Enviado do meu iPhone

**Comment by pbassut** [comment]
Any tips on this?

**Comment by pbassut** [comment]
Sorry. It wasn't working because I was using ```EnterMode``` instead of ```enterMode```. It's case sensitive.

**Comment by FabrizioA** [comment]
It doesn't works for me.. :'(
Can you provide an example for settings.py usage?
Thank you.

**Comment by Evert-Arends** [comment]
This doesn't work for me neither, is there a solution?

**Comment by yashas123** [comment]
@FabrizioA @Evert-Arends 
In settings.py it's something like this: 
```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
        'enterMode': 2
    },
}
```
The values for `enterMode` are:
1 – New <p> paragraphs are created.
2 – Lines are broken with <br> elements.
3 – New <div> blocks are created.
