### ISSUE TITLE
Upload doesn't complete

### ISSUE THREAD

**Issue by TheDrifter254** [django-ckeditor/django-ckeditor#239]
When I  try to upload an image I get the red X icon look at this video https://youtu.be/OVGncD73RIk for a screen record of it.

**Comment by pbassut** [comment]
Looks like you're using '/home/something' as your CKEDITOR_UPLOAD_PATH. 
Mine looks like this:
```CKEDITOR_UPLOAD_PATH = "uploads/"```

**Comment by TheDrifter254** [comment]
Fixed the issue

On Sat, Nov 14, 2015 at 10:04 AM, Patrick Bassut <notifications@github.com>
wrote:

> Looks like you're using '/home/something' as your CKEDITOR_UPLOAD_PATH.
> Mine looks like this:
> CKEDITOR_UPLOAD_PATH = "uploads/"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-ckeditor/django-ckeditor/issues/239#issuecomment-156657472>
> .
>



-- 

Best Regards,

Samuel Muiruri.

--------------------------------------------

Samuel Muiruri, Web Designer & Software Designer

0732219754/0720812159 | muiruri.samuel@gmail.com
