### ISSUE TITLE
Doesn't work with django 1.9rc1.

### ISSUE THREAD

**Issue by Dharmik8478** [django-ckeditor/django-ckeditor#240]
While updating my project to the 1.9rc with python 3.4 ckeditor calls for util indjango.forms but there is no util file inside that folder it gives me this error.

>   from ckeditor.widgets import CKEditorWidget
  File "/opt/pyvirtual/py_3.4-dj_1.9/lib/python3.4/site-packages/ckeditor/widgets.py", line 10, in <module>
    from django.forms.util import flatatt
ImportError: No module named 'django.forms.util'

**Comment by riklaunim** [comment]
I'll fix that.

**Comment by Dharmik8478** [comment]
Ok thanks in advance.
Let me know when it is done.
