### ISSUE TITLE
Formatting tweets

### ISSUE THREAD

**Issue by Six-wars** [django-ckeditor/django-ckeditor#243]
I used to use ckeditor 4.0.2 now upgraded to 5.0.2 and the format of tweets have changes from this http://www.kenyabuzz.com/lifestyle/cnn-faces-the-wrath-of-kenyans-on-twitter to this http://www.kenyabuzz.com/lifestyle/kenya-corruption-president-address (old articles render with the old look but when any changes are done they take on the new look) I prefer the older look, how can I tweek it to the old look?

**Comment by riklaunim** [comment]
I don't know if it's ckeditor related. There are some JS error in console, which may breake Twitter widget rendering.

**Comment by matthiask** [comment]
Closing beacuse of inactivity. If there's an issue in *django-ckeditor* please reopen. This sounds more like a change in CKEditor, and not django-ckeditor.
