### ISSUE TITLE
Allow Script tags in ckeditor

### ISSUE THREAD

**Issue by sam-thecoder** [django-ckeditor/django-ckeditor#245]
I want to allow script tags in the content since it's needed to render tweets correctly, how can I edit the ckeditor so it doesn't remove script tags when you switch from source.

**Comment by Rulox** [comment]
+1

**Comment by matthiask** [comment]
Hey; do you know how to do this with a standalone CKEditor installation? And if yes, what feature or misfeature of django-ckeditor stops you from using this in your own project?

**Comment by Rulox** [comment]
Just a fyi, I solved it using "allowedContent": True in the ckeditor config.
```python
CKEDITOR_CONFIGS = {
    'default': {
        'allowedContent': True,
    },
}
```

**Comment by CARocha** [comment]
not this allowedContent not render correctly the tweet see image
![captura de pantalla de 2017-05-09 10-46-40](https://cloud.githubusercontent.com/assets/168115/25865148/8bc57582-34b7-11e7-8087-6c06f3ebe0f1.png)
how to show render correctly tweet inside editor??
any tips or trick

**Comment by riklaunim** [comment]
CkEditor does a lot of HTML cleaning and it's hard to disable it (putting paragraphs everywhere and changing tags). In some cases it may be easier to use summernote.

**Comment by matthiask** [comment]
Indeed. Anyway, that's a issue concerning CKEditor not django-ckeditor therefore that's not the best place to discuss this.
