### ISSUE TITLE
stylesSet.add

### ISSUE THREAD

**Issue by felixSchl** [django-ckeditor/django-ckeditor#246]
As per [the CKEdtor docs](http://docs.ckeditor.com/#!/guide/dev_howtos_styles-section-2), one has to mutate `stylesSet` to add custom styles. There appears to currently be no other way than re-defining the whole default array and then adding extras on top using this app.

**Comment by riklaunim** [comment]
Are you sure you can't do this by config: https://github.com/django-ckeditor/django-ckeditor#example-ckeditor-configuration ?

**Comment by felixSchl** [comment]
Not that I can tell and there's nothing in the source code that would suggest it's possible from what I have seen. The linked docs above show how to layout the toolbar to include a dropdown for the styles, but it does not give me a way to define what will be inside the styles dropdown.

**Comment by felixSchl** [comment]
I wonder how one would solve this anyway... there's a somewhat related issue that I cannot pass down [stylesheetParser_validSelectors](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-stylesheetParser_validSelectors) because the api actually expects a RegExp which is not serializable. Unless we have some js-side plugin that unpacks the config and runs some code on it, I don't think we will able to do either of these. What do you think? I am happy to contribute since I need this functionality soonish.

**Comment by riklaunim** [comment]
You could paste the extra configuration in JS just after the generated config JS file.

**Comment by filias** [comment]
I would also like to customize the styles of the insert image widget but can't really understand how to do it. Is there any documentation with examples?

**Comment by riklaunim** [comment]
it's a ckeditor plugin. You would have to modify it directly.

**Comment by filias** [comment]
which plugin? how to install it? can you point me to some specific docs? Thanks!

**Comment by soulraven** [comment]
same problem now in 2020, 
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_howtos_styles.html#how-do-i-customize-the-styles-drop-down-list

is not possible to use add for existings configs. a python way is a good option

**Comment by niccolomineo** [comment]
I hope redefining styles will be made actually usable at some point.

**Comment by matthiask** [comment]
Well, you could always submit a pull request or pay someone to develop this functionality.

**Comment by some1ataplace** [comment]
To add custom styles to the stylesSet in Django-CKEditor, you can follow these steps:

1. Open the ckeditor/config.js file in your project directory.
2. Add the following code to the file:

```
CKEDITOR.stylesSet.add( 'my_styles', [
    { name: 'My Custom Style', element: 'p', styles: { 'color': 'red', 'font-size': '20px' } }
] );
```


This code adds a new style called "My Custom Style" to the stylesSet, which applies a red color and 20px font size to the p element.

3. Modify the config.js file to use the new stylesSet:

```
CKEDITOR.editorConfig = function( config ) {
    config.stylesSet = 'my_styles';
};
```


This code sets the stylesSet to the newly created my_styles set.

***

1. In your Django project, create a folder named static in the root directory if it does not exist already.
2. Inside the static folder, create another folder named js.
3. Download the ckeditor.js and config.js files from the CKEditor website.
4. Save both files in the static/js folder.
5. Open the config.js file and add the following code to it:

```
CKEDITOR.stylesSet.add( 'my_styles', [
    { name: 'Custom Style 1', element: 'span', styles: { 'background-color': 'green' } },
    { name: 'Custom Style 2', element: 'p', styles: { 'color': 'red' } },
]);

// Then set the 'stylesSet' option to use your custom style set

config.stylesSet = 'my_styles';
```


6. In your Django settings.py file, add the following code to the STATICFILES_DIRS list:


```
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
```
