### ISSUE TITLE
ImportError: No module named 'ckeditor.urls'

### ISSUE THREAD

**Issue by SalahAdDin** [django-ckeditor/django-ckeditor#248]
I put the normal ckeditor urls in the urls.py and the shell send me this error. Why?

**Comment by riklaunim** [comment]
(r'^ckeditor/', include('ckeditor_uploader.urls')),

**Comment by SalahAdDin** [comment]
I have the dude, why did you do this change?

**Comment by riklaunim** [comment]
To separate file management from ckeditor form widget code (where not everyone wanted or could use it), and to make using that code explicit instead of just adding potential remote file upload functionality to unaware users.

**Comment by SalahAdDin** [comment]
Ah, ok man, very useful, thanks!
