### ISSUE TITLE
How to restrict the filesize of uploaded file(s)?

### ISSUE THREAD

**Issue by dzhuang** [django-ckeditor/django-ckeditor#249]
Is there a way to restrict the size of a single file or all files of a single submit?

**Comment by riklaunim** [comment]
Single file can be limited by server configuration.

**Comment by some1ataplace** [comment]
1. Open your Django project's settings.py file and add the following configuration:

```
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_RESTRICT_FILE_SIZE = 5242880  # Restrict file size to 5MB
```


CKEDITOR_UPLOAD_PATH is the path where uploaded files will be stored, CKEDITOR_IMAGE_BACKEND is the image processing backend to use, and CKEDITOR_RESTRICT_FILE_SIZE is the maximum file size in bytes allowed for uploads.

2. Create a new file named validators.py in your Django app folder and add the following content:

```
from django.core.exceptions import ValidationError
from django.conf import settings

def validate_file_size(value):
    filesize = value.size

    if filesize > settings.CKEDITOR_RESTRICT_FILE_SIZE:
        raise ValidationError("The maximum file size that can be uploaded is 5MB")
    else:
        return value
```


This function checks the size of the uploaded file and raises a validation error if the file size is greater than the allowed limit.

3. Open your Django app's models.py file and add the following code:

```
from django.db import models
from ckeditor.fields import RichTextField
from .validators import validate_file_size

class MyModel(models.Model):
    content = RichTextField()
    image = models.ImageField(upload_to='uploads/', validators=[validate_file_size])

```
Replace MyModel with the name of your model. This code defines a model with a RichTextField and an ImageField. The ImageField uses the validate_file_size` function as a validator to check the uploaded file size.

4. In your Django app's forms.py file, import the model and create a form for it:

```
from django import forms
from .models import MyModel

class MyModelForm(forms.ModelForm):
    class Meta:
        model = MyModel
        fields = ['content', 'image']
```

This code creates a form based on the MyModel model, including the content and image fields.

5. In your views.py file, import the form and handle the file upload:

```
from django.shortcuts import render
from .forms import MyModelForm

def my_view(request):
    if request.method == 'POST':
        form = MyModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'success.html')
    else:
        form = MyModelForm()

    return render(request, 'form.html', {'form': form})
```

This view handles the form submission, including the file upload, and saves the model instance if the form is valid.

6. Create the necessary templates (form.html and success.html) to display the form and show a success message after a successful upload.

7. Finally, update your urls.py file to include the view and make sure your MEDIA_URL and MEDIA_ROOT settings are properly configured in settings.py to serve uploaded files during development.

With these steps, you should now have a working CKEditor file upload with file size restrictions in place. Make sure to adjust the CKEDITOR_RESTRICT_FILE_SIZE setting to the desired maximum file size in bytes.
