### ISSUE TITLE
Image Browser: "Embed Image" button and Image Preview alignment issues 

### ISSUE THREAD

**Issue by radiovisual** [django-ckeditor/django-ckeditor#250]
In my version of the package (pip reports version `5.0.2`, but [there might be some versioning issues at the moment](https://github.com/django-ckeditor/django-ckeditor/issues/211#issuecomment-165086488)), when I use the Image Browser (after pressing the "Browse Server" button), the large image preview and the "Embed Image" button are too far off to the right. I have to enlarge the Browser window that launches to see the entire image, as well as press the "Embed Image" button. 

I get the same behavior in Firefox, Chrome and Safari (haven't checked Opera or IE). I am able to fix the problem by removing `min-width:980px` (using Chrome's Inspect Tools) on the `#container` element: 

```css
#container {
    position: relative;
    width: 100%;
    /* min-width: 980px; */
    padding: 0;
}
```

There is no need for the `min-width` style in the css because you set an explicit inline style on [line #24 of `browse.html`](https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/templates/ckeditor/browse.html#L24): `<div id="container" style="width: 880px">`

So it seems that maybe these conflicting widths are causing the problem?

**UPDATE:** The `min-width` style is being loaded in via the django admin's bass.css file. [See my comment below for more info](https://github.com/django-ckeditor/django-ckeditor/issues/250#issuecomment-165110242).

**Comment by radiovisual** [comment]
Alternatively, you can get things to align properly if you set the min-width to match the explicit width set on the container element:

```html
<div id="container" style="width: 880px">
```

```css
#container {
    position: relative;
    width: 100%;
    min-width: 880px; /* <-- set to match the inline width */
    padding: 0;
}
```

**Comment by luzfcb** [comment]
this looks like a problem with ckeditor and not with django-ckeditor .

ckeditor issue tracker is https://dev.ckeditor.com/

**Comment by radiovisual** [comment]
@lqez , is this file included in every installation of CKEditor?:

[django-ckeditor/ckeditor_uploader/templates/ckeditor/browse.html](https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/templates/ckeditor/browse.html)

because the problem is originating there.

 The styles loaded on [line #6](https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/templates/ckeditor/browse.html#L6):

```html
<link rel="stylesheet" href="{% static "admin/css/base.css" %}" type="text/css" />
```
are conflicting with this inline style on [line #9](https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/templates/ckeditor/browse.html#L9)

```html
<div id="container" style="width: 880px">
```

From what I can tell, the `browse.html` template is under version control on this repo only, and [can't be found anywhere on CKEditor's repo](https://github.com/ckeditor/ckeditor-dev/search?utf8=%E2%9C%93&q=browse.html+extension%3A.html&type=Code)

**Comment by radiovisual** [comment]
I fixed the issue in the Pull Request mentioned above this comment. The solution was to simply add this line to the css in `browse.html`:

```css
#container { min-width: 880px; }
```

This way, the widths no longer conflict.

**Comment by lqez** [comment]
@radiovisual aha? did you mention to me? it looks like I just popped up beside @luzfcb :$ lol

**Comment by radiovisual** [comment]
Oops! Sorry @lqez! haha. I corrected the mention in my comment. :santa: :cake:

**Comment by radiovisual** [comment]
Any news on this? I have to keep applying a patch manually to get the Gallery to display correctly...meanwhile, my [PR](https://github.com/django-ckeditor/django-ckeditor/pull/251) is just waiting to save the day.
