### ISSUE TITLE
Problem with '[img]' tag on templates

### ISSUE THREAD

**Issue by dpineiden** [django-ckeditor/django-ckeditor#255]
Hello
I'm using the ckeditor field (with uploader) and i try to render on a view the model but the ckeditor field doesn't filter the img tag to show the image, and give me the path.
What i have to do? some special filter?

Thanks!

**Comment by riklaunim** [comment]
The editor should insert HTML img tag, not [img] BBCode.

**Comment by dpineiden** [comment]
Thanks, that's was the problem, bbcode plugin was activated,so i erase and works fine ;)
