### ISSUE TITLE
Thumbnail uploaded image, and using the thumbnail separate from the content

### ISSUE THREAD

**Issue by lip365** [django-ckeditor/django-ckeditor#258]
Hello, thanks for making this awesome app. 
It meets all my requirements, but I was hoping if there's a way I can use the user posted image separate from the content. Currently, all the contents(image+text) are shown as {{content}} but I want to use {{post.image}} if it's possible. Could you please tell me if there's any way I can achieve this this functionality with django-ckeditor?

**Comment by riklaunim** [comment]
You could make a property on the model class that looks through content and returns the first link to img src.

**Comment by lip365** [comment]
that sounds too advanced for me... so I have 
class Post(models.Model):
	content = RichTextUploadingField(config_name='default')
       def get_content(self):  
[some code...../I have no idea what I should write here......
return image......] hmmm how do I make this function without knowing any variable for the content?little help? :)

**Comment by riklaunim** [comment]
```
@property
def image(self):
    return self.content
```

Where self.content will have be replaced by something that looks through html code and extracts image url from it. beautifulsoap, regexp and so on.

**Comment by lip365** [comment]
ah ok, thank you. I have to extract image from the content eh...you don't have any example I can take a look at do you?

**Comment by matthiask** [comment]
Ask on django-users or some beautifulsoup forum for help if you still need it. Thanks!
