### ISSUE TITLE
Docs: What to do, if a plugin is missing?

### ISSUE THREAD

**Issue by guettli** [django-ckeditor/django-ckeditor#261]
Please provide docs what you should do if you miss a plugin.

The list of installed plugins is long:
https://github.com/django-ckeditor/django-ckeditor#plugins

 ... but my favorite (blockquote) is missing.

What to do?

**Comment by riklaunim** [comment]
You add it like if it was a normal ckeditor case and you add that plugin name to the configuration dict of the editor (that is mapped to ckeditor JS configuration.

**Comment by guettli** [comment]
The instructions on how to install a ckeditor. Source: http://docs.ckeditor.com/#!/guide/dev_plugins

> ...
> 1. Extract the plugin .zip archive.
> 2. Copy the plugin files to the plugins folder of your CKEditor installation. Each plugin must be placed in a sub-folder that matches its "technical" name.
> For example, the Language plugin would be installed into this folder: <CKEditor folder>/plugins/language.

django-ckeditor was installed via pip into its own directory. I don't want to copy the plugin `blockquote` there.

Where should I unzip the plugin?

**Comment by riklaunim** [comment]
to one of your django static directories. to STATIC_FOLDER/ckeditor/plugins

**Comment by guettli** [comment]
I see: `collectstatic` helps me here. 

I copied `blockquote` to my app like this `djangotools/static/ckeditor/ckeditor/plugins/blockquote`

I run `collectstatic`. The symlinks got created.

I updated the config:

```

CKEDITOR_CONFIGS = {
    'default': {
        'extraPlugins': 'blockquote',
    }
}
```
The HTML contains the `blockquote`: `<textarea cols="40" id="id_body" name="body" rows="10" data-processed="0" data-config='... "extraPlugins": "blockquote", ...' data-external-plugin-resources='[]' `


But the plugin does not get loaded. I looked checked it with the firefox network debugger. These file gets loaded `ckeditor-init.js`, `ckeditor.js`, `config.js', but not a single file of `blockquote`.

Does `data-external-plugin-resources` need to be set?

**Comment by guettli** [comment]
I got "blockquote" working with this answer from StackOverlfow: http://stackoverflow.com/questions/36028699/load-blockquote-plugin-in-ckeditor

Still I don't get it: It seems that you don't need the blockqoute plugin at all. Adding "Blockquote" to the toolbar helped.

Why does the blockquote plugin exist?

I guess this question is not the topic of django-ckeditor. You can close the issue if you want to.

**Comment by matthiask** [comment]
Thank you!
