### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by Anshik** [django-ckeditor/django-ckeditor#262]
Hi, I'm trying to implement file upload on site (not in admin interface), and have some problems:
1. I don't want provide to users ability browsing server files, just upload file on server, and put the link in editor area
2. Can I show progress bar for large file uploads?

I want to make, like in git hub Issues. Just drug and drop file, and it uploads to server.

**Comment by riklaunim** [comment]
You would have to modify the code and remove the browse view from urls.py
