### ISSUE TITLE
Multiple widgets on same page fail to load second all the time

### ISSUE THREAD

**Issue by marc-gist** [django-ckeditor/django-ckeditor#264]
When I have more than one CKEditorWidget(config_name='full') and CKEditorWidget(config_name='basic'), the page loads, but usually the second CKEditor doesn't load.
Reloading the page will eventually get both to show.

Setting both to the same config seems to work fine.

**Comment by Ryuno-Ki** [comment]
I was able to initialise two widgets with different `config_name`s by assigning the widget not in `class Meta`, but later to `self.fields['field_name'].widget`.

Feels hacky.
While debugging I noticed that my `config_name`s didn't show up [at overwrite](https://github.com/django-ckeditor/django-ckeditor/blob/182d484c9e29a0859e431b8704994ba167eb025d/ckeditor/widgets.py#L92). Only a single instance was loaded (with an entirely different `config_name`).
