### ISSUE TITLE
allow option to have full url for upload images and files

### ISSUE THREAD

**Issue by chhantyal** [django-ckeditor/django-ckeditor#266]
I can't find any issues related to this.

When you need to use RichTextField with uploader for things like newsletter, uploaded images and documents need to have full url. Currently, CKeditor uses relative urls and it doesn't work outside of normal request/response cycle.

**Comment by riklaunim** [comment]
In what way it doesn't work?

**Comment by chhantyal** [comment]
Sorry that I wasn't clear. Ckeditor uses relative path for uploaded images. When you send rich text email made with ckeditor, it can't load images/docs because it doesn't have full url.

**Comment by riklaunim** [comment]
It uses Django file storage. If you want full URLs then set MEDIA_URL to an URL.

**Comment by chhantyal** [comment]
Thanks. that works.

**Comment by darkkase** [comment]
common... add  absolute option.. i dont like  to use absolute path in all my   imgs,  but i what to see the image  in the textfield editor

**Comment by riklaunim** [comment]
Django doesn't use relative paths and in most cases you set MEDIA_URL to an absolute path or an url.

**Comment by darkkase** [comment]
you can map with your server the  /static/  to  other static only* servers... is not dificult, and you can use relative paths. Its only one if

**Comment by riklaunim** [comment]
Images use django file storage API. You get what you configure it with. There are no hardcoded paths or urls.
