### ISSUE TITLE
upgrade to CKEditor v4.5.7

### ISSUE THREAD

**Issue by radiovisual** [django-ckeditor/django-ckeditor#268]
The current version of CKEditor packaged in django-ckeditor is `v4.5.3`. I am getting some buggy behavior in `v4.5.3` of CKEditor, and my problem gets solved when I switch to `v4.5.7`. I won't report the buggy behavior here, since its a problem with CKEditor, and not with django-editor directly, but if upgrading the version of CKEditor helps me solve my problem, then I am sure users of django-ckeditor can equally benefit from having the latest version. 

If you can't upgrade the library in this repo for some reason, then at the very minimum, you could list the the steps (a "recipe") to instruct users of django-ckeditor how to manually upgrade the version themselves. 

Thanks!

**Comment by riklaunim** [comment]
I'll do a update package soon if it's needed. You can copy-paste the ckeditor package to you static folder as ckeditor/ckeditor/ and it will overwrite django-ckeditor version (if the static folder you used is used after django-ckeditor in collectstatic operations)

**Comment by radiovisual** [comment]
Ok, thanks for the tip. I did a manual update. :+1: I am going to close my PR #269 which attempts to help you update the version, because (1) it sounds like you have a special process for the updates (an "update package"), and (2) I won't have the time to push any new commits to that PR in case I did something wrong. 

But I appreciate the help! Thanks for this awesome tool!

**Comment by tisdall** [comment]
@riklaunim - we're at v4.6.1 now.  I think the issue can be closed.
