### ISSUE TITLE
in development, any users can upload images. But now that I'm using elastic beanstalk and s3, non-staff members can't upload image. Am I the only one having this issue?

### ISSUE THREAD

**Issue by lip365** [django-ckeditor/django-ckeditor#273]
Hello,

I made the way all users to be able to upload images. this has been successful in development, but in production non-staff members can't upload any image.

I don't think this is a problem of amazon s3, because in development even when the image gets saved in s3 non staff members can upload images.

Am I the only one having this problem? can some one please help me out?

**Comment by lip365** [comment]
even after I removed this staff_member_required

**Comment by lip365** [comment]
this is my setting


        #ckeditor
        CKEDITOR_UPLOAD_PATH = "media/"
        CKEDITOR_IMAGE_BACKEND = "pillow"
        CKEDITOR_ALLOW_NONIMAGE_FILES = False 
        CKEDITOR_RESTRICT_BY_USER = True
        CKEDITOR_REQUIRE_STAFF=False
        CKEDITOR_CONFIGS = {
            'default': {
        'toolbar': [["Format", "Bold", "Italic", "Underline", "Strike", "SpellChecker"],
                        ['NumberedList', 'BulletedList', "Indent", "Outdent", 'JustifyLeft', 'JustifyCenter',
                         'JustifyRight', 'JustifyBlock'],
                        ["Image", "Table", "Link", "Unlink", "Anchor", "SectionLink", "Subscript", "Superscript"], ['Undo', 'Redo'], ["Source"],
                        ["Maximize"]],
                'uiColor': '#9AB8F3',
        
        
            },
        }
        AWS_DEFAULT_ACL = 'public-read'
        
        AWS_QUERYSTRING_AUTH = False
    
    
    
    AWS_FILE_EXPIRE = 200
    AWS_PRELOAD_METADATA = True
    AWS_QUERYSTRING_AUTH = True
    
    DEFAULT_FILE_STORAGE = 'ebagu.utils.MediaRootS3BotoStorage'
    STATICFILES_STORAGE = 'ebagu.utils.StaticRootS3BotoStorage'
    AWS_STORAGE_BUCKET_NAME = 'realebagu'
    S3DIRECT_REGION = 'ap-northeast-2'
    AWS_S3_HOST = "s3-ap-northeast-2.amazonaws.com"
    S3_URL = '//%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME
    MEDIA_URL = '//%s.s3.amazonaws.com/media/' % AWS_STORAGE_BUCKET_NAME
    MEDIA_ROOT = MEDIA_URL
    STATIC_URL = S3_URL + 'static/'
    ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'
    
    import datetime
    
    date_two_months_later = datetime.date.today() + datetime.timedelta(2 * 365 / 12) 
    expires = date_two_months_later.strftime("%A, %d %B %Y 20:00:00 GMT")
    
    AWS_HEADERS = { 
        'Expires': expires,
        'Cache-Control': 'max-age=86400',
    }

**Comment by dezinfo** [comment]
I have the same problem. Only super user can upload files.

**Comment by riklaunim** [comment]
And what's the exception when non admin tries to?

**Comment by dezinfo** [comment]
to riklaunim 

Appears standard django authorization dialog. But I found a solution. I deleted a staff_member_required decorator from ckeditor_uploader urls.py file.

**Comment by riklaunim** [comment]
And then it works? Odd that staff isn't able to use it with non-standard file backend - maybe the backend also has some permission checks?

**Comment by dezinfo** [comment]
Yes, after deleted decorator, there isn't any problem with upload files by non-staff users.

**Comment by riklaunim** [comment]
non staff is obvious. With the decorator staff but not superuser should also be able. If you just want to allow upload to anyone then you just hook up those views directly in yours urls.py without the decorator.
