### ISSUE TITLE
[Question] Support for `CKEDITOR.plugins.addExternal`

### ISSUE THREAD

**Issue by radiovisual** [django-ckeditor/django-ckeditor#277]
In JavaScript, if I want to attach an external plugin location to my instance of CKEditor, I can just use:

``` js
CKEDITOR.plugins.addExternal('somePlugin', 'path/to/custom/location');
```

Is there a way to do this with django-ckeditor?

Something like:

``` python
CKEDITOR_CONFIGS = {
    'plugins' : {
        'addExternal': [{'somePlugin', 'path/to/custom/location'}]
    },
```

???

Thanks for your help.

**Comment by mykljohn** [comment]
I would like to do this as well, trying to add ckwebspeech.  I've tried adding it in the js and in settings.py, but it will not add it to the menu.

**Comment by matthiask** [comment]
Yes there is a way to do this with django-ckeditor since 2014, but it was not documented. The oversight has been fixed with https://github.com/django-ckeditor/django-ckeditor/commit/4fba4699c45921e0fa07f68fed639a3e28923568
