### ISSUE TITLE
Documentation imprecise

### ISSUE THREAD

**Issue by sedrubal** [django-ckeditor/django-ckeditor#278]
I've 2 questions/proposals for documentation:

> django-ckeditor uses jQuery in ckeditor-init.js file. You must set `CKEDITOR_JQUERY_URL` to a jQuery URL that will be used to load the library. If you have jQuery loaded from a different source just don't set [CKEDITOR_JQUERY_URL] and django-ckeditor will not try to load its own jQuery.

Does django-ckeditor load jQuery from ckeditor-init.js when `CKEDITOR_JQUERY_URL = ''` or does it load nothing?

> Note that by adding those URLs you add views that can upload and browse through uploaded images. Since django-ckeditor 4.4.6 those views are staff_member_required. If you want different permission decorator (login_required, user_passes_test etc.) then add views defined in ckeditor.urls manualy to you urls.py.

Do you mean `ckeditor_uploader.urls`? Can you give an example urls.py with custom decorators?

**Comment by riklaunim** [comment]
1. it does nothing (it would add "script" tag with that jquery url)
2. https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/urls.py
