### ISSUE TITLE
filebrowserImageUploadUrl not being set

### ISSUE THREAD

**Issue by hcastilho** [django-ckeditor/django-ckeditor#286]
ckeditor_uploader should set filebrowserImageUploadUrl in the widget config.
Currently we need to add it to CKEDITOR_CONFIGS or to the ckeditor config.js

**Comment by Kurdakov** [comment]
the related problem  is that is  quite inconvenient that django filebrowser ( https://github.com/smacker/django-filebrowser-no-grappelli )  and django ckeditor have different conventions  where to place thumbnails. django filebrowser puts them into VERSIONS_BASEDIR location, while django ckeditor has no comparable setting - thus when using both packages ( django filebrowser and django-ckeditor ) two sets of thumbnails might be generated

**Comment by tisdall** [comment]
The code is currently setting `filebrowserUploadUrl` and CKEditor says that if `filebrowserImageUploadUrl` is not set that it reverts to using `filebrowserUploadUrl`.  I don't think this is an issue any more.
