### ISSUE TITLE
HTTP error occurred during file upload (error status: 500)

### ISSUE THREAD

**Issue by mgarc** [django-ckeditor/django-ckeditor#287]
I´m using the `uploadimage` plugin but when I try to drag and drop or copy and paste some image gives me this error
![error uploadimage](https://cloud.githubusercontent.com/assets/17034824/15404191/f3a65cc4-1dc1-11e6-8965-65ba2c23caed.jpg)

and this message in the console

> raise MultiValueDictKeyError(repr(key)) MultiValueDictKeyError: "'CKEditorFuncNum'"

**Comment by riklaunim** [comment]
The upload functionality was tailored to the upload widget django-ckeditor comes with. It doesn't handle the newer upload API from drag and drop actions.

**Comment by mgarc** [comment]
Thank you for the info

**Comment by istommao** [comment]
When to support paste image for uploadimage api, i encounter this error when paste image
