### ISSUE TITLE
Is the div block around textarea in template necessary?

### ISSUE THREAD

**Issue by ablo1st** [django-ckeditor/django-ckeditor#288]
Hi, Thanks for this awesome ckeditor integrator with django. I had some issues with the width setting of the textarea which was not being enforced and I found that the reason was the textarea was surrounded by a div block. Is this div block necessary? I removed it and the code seemed to work fine.

**Comment by matthiask** [comment]
Maybe it's not strictly necessary, but we'd need more justification for removing this. Thanks, and please reopen if you want to continue the discussion!
