### ISSUE TITLE
Prevent javascript input

### ISSUE THREAD

**Issue by matheusjardimb** [django-ckeditor/django-ckeditor#290]
In order to display the formatted content, I'm using something like this
`{{ obj.field|safe }}`

Is there any way to ensure that the user can only add html in the editor? Is there any validation available in the server side?

I want to prevent users adding malicious code.

**Comment by luzfcb** [comment]
use: https://pypi.python.org/pypi/django-bleach 

https://docs.djangoproject.com/en/dev/ref/templates/builtins/#striptags

I also believe that `safe` does not do what you think does
https://docs.djangoproject.com/en/dev/ref/templates/builtins/#safe

**Comment by luzfcb** [comment]
to prevent a user to insert javascript code in the ckeditor field, you probably have to create your validation rules using:  http://docs.ckeditor.com/#!/guide/dev_acf

**Comment by matheusjardimb** [comment]
Hello @luzfcb 

I'm not sure if I get what you meant, but `|striptags` and did not output what I expected. It just removes html tags.
Instead, by using `|safe` I've got the proper visual output. 

`django-bleach` seems to make the proper sanitization in the server side, in order to avoid even storing js content. 

I'll check it out. Thanks!
