### ISSUE TITLE
"Browse server" have some troubles.

### ISSUE THREAD

**Issue by LauGau** [django-ckeditor/django-ckeditor#292]
Hi ;

I don't found answers on this, please note that I'm on amazon S3.
So, I don't have any problems with file upload. Everything works fine.

The problem is when I try to select a file with a "browse server" button... Each time I have that : 
![bug](https://cloud.githubusercontent.com/assets/9392592/15929753/1d3855a4-2e4f-11e6-9a08-544edb94c7fe.JPG)

So the loader never stop... File extension icons doesn't appear (staticfiles error ?)...
I don't understand because my files displays correctlty everywhere else...
Any idea ? Thanx a lot ! :)

**Comment by riklaunim** [comment]
Check what happens when you open one of those broken images in the browsers, check if the url is good.

**Comment by LauGau** [comment]
Broken images are for file icon.

Here is the <img> tag :
`<img src="/static/ckeditor/file-icons/pdf.png" style="max-width: 75px;">`

And here is the generated URL adress :
`http://wailing-trees.herokuapp.com/static/ckeditor/file-icons/pdf.png`

But I need this adress :
`https://wailing-trees.s3.amazonaws.com/static/ckeditor/file-icons/pdf.png`

So yes, it's a URL problem, but I don't understand how it can work perfecly with uploads and image preview... All my other static files and media files works perfectly... Strange no ?

**Comment by LauGau** [comment]
I had this problem because, django-ckeditor can't find any img to display (not the thumbnail et not the file-icon). So I just add the adress of my S3 static files in my STATICFILES_DIRS to force the search:
`STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'wt/wt/static'),
    "https://wailing-trees.s3.amazonaws.com/static",
]`
Well...it's just a quick fix. I still don't have the thumbnails displayed..And I still don't know wyh. But now I have the file extension icon, and, I can Embed previously uploaded file.
