### ISSUE TITLE
switch to source remove awesome icons

### ISSUE THREAD

**Issue by shtalinberg** [django-ckeditor/django-ckeditor#293]
I try add icons to text in editor via "Source" button, my code :
`<i class="fa fa-file-pdf-o" aria-hidden="true"></i>`
after switch to preview and back to source  this code removed

how fix this rule  ?

**Comment by riklaunim** [comment]
That's something CKEditor related.

**Comment by shtalinberg** [comment]
I found this solution:
`
         // ALLOW <i></i>
           config.protectedSource.push( /<i[\s\S]*?\>/g ); //allows beginning <i> tag
           config.protectedSource.push( /<\/i[\s\S]*?\>/g ); //allows ending </i> tag
        // or  ALLOW <i></i>
        'protectedSource.push(/<i[^>]*><\/i>/g);
`
but how I can add this to django-ckeditor settings?
