### ISSUE TITLE
ckeditor already attached to the provided element

### ISSUE THREAD

**Issue by jlariza** [django-ckeditor/django-ckeditor#301]
Hello,

I am using your library and I am getting a "The editor instance "id_content" is already attached to the provided element" error.

Apparently, it is trying to load CKEditor twice, failing the second time and breaking the other js in the page.

Could you check it out?

ty

**Comment by KarloxMartinez** [comment]
+1

**Comment by riklaunim** [comment]
Where and when does it shows up? What browser are you using?

**Comment by jlariza** [comment]
It shows ups whenever I create a ckeditor field and it gets rendered. I test it using chrome and using firefox. It tried to load the CKEditor object twice, failing the second time.

Ty

**Comment by gusarg81** [comment]
Hi, same thing is happening to me:

> "message_html" is already attached to the provided element.

Versions:

- Django-1.10.3
- django_ckeditor-5.1.1

Thanks.

**Comment by darshit7** [comment]
Same issue occurred to me.
I have get html content in AJAX response and try to attached it to div, but it will trigger error "The editor instance "id_content" is already attached to the provided element".

**Comment by matthiask** [comment]
Editor instances have to be destroyed explicitly first. 

I don't think this particular error has anything to do with django-ckeditor
