### ISSUE TITLE
can't apply width 100%

### ISSUE THREAD

**Issue by nvcken** [django-ckeditor/django-ckeditor#302]
```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'width': '100%',
        'height': 520,
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList'],
..........
        ],
    }
}
```

But width of editor still not 100% in admin page.
If I change `inline-block` to `block` on "django-ckeditor-widget", it will work

```
<div class="django-ckeditor-widget" data-field-id="{{id}}" style="display: inline-block;">
```

Any the right way plz?
Another way is adding width 100% style to "django-ckeditor-widget" still work.
But any correct config that ?

**Comment by admed** [comment]
your_app/templates/ckeditor/widget.html
create in your app template directory ckeditor and add to it file widget.html than past the code to file:

`<div class="django-ckeditor-widget" data-field-id="{{id}}" style="display: block;">
    <textarea{{ final_attrs|safe }} data-processed="0" data-config='{{config|safe}}' data-external-plugin-resources='{{external_plugin_resources|safe}}' data-id="{{id}}" data-type="ckeditortype">{{ value }}</textarea>
</div>`

**Comment by nvcken** [comment]
Cool. Will try it.
My urgent way is add css style to ckeditor dev element.

**Comment by denisjul** [comment]
@admed: it works well

**Comment by soerendip** [comment]
It is not working.

**Comment by marcosguedes** [comment]
It does (using django-ckeditor 6.1.0). Please ensure the app where you place the overriding folder comes _before_ `'ckeditor'` in your `INSTALLED_APPS`

```
INSTALLED_APPS = [
    ....
    "ckeditor_overrides",
    "ckeditor",
    ...
]
```

Sorry for necro'ing but this is the first google result when searching for "django-ckeditor-widget inline-block" on google
