### ISSUE TITLE
Django CKEditor Title In Chart and Fixed Line

### ISSUE THREAD

**Issue by JIJOSEPH** [django-ckeditor/django-ckeditor#303]
Dear Nicolas;

I have to questions that I am sure that that you can answer.

1)  In one of my charts I have a line which shows a fixed value of 9 to show the threshold of some products. How do I represent this in my data or chart as show in the image below.

2) How do I change the default title for my chart (it currently makes it up based on the selection. I would like to put some more user friendly option.

Thanks.

JIm

![mean_yls](https://cloud.githubusercontent.com/assets/1042916/16787777/119e6778-486d-11e6-998b-c627a06a71f7.jpg)

**Comment by luzfcb** [comment]
@JIJOSEPH you probably reported it in the wrong issue tracker, because your question is not related to ckeditor or django-ckeditor

**Comment by JIJOSEPH** [comment]
Apologies. Meant javascript pivot table.
