### ISSUE TITLE
Title In Chart And FIxed Value Line in Chart

### ISSUE THREAD

**Issue by JIJOSEPH** [django-ckeditor/django-ckeditor#304]
Dear Nicolas;

I have to questions that I am sure that that you can answer.

1) In one of my charts I have a line which shows a fixed value of 9 to show the threshold of some products. How do I represent this in my data or chart as show in the image below.

2) How do I change the default title for my chart (it currently makes it up based on the selection. I would like to put some more user friendly option.

Thanks.

JIm
![mean_yls](https://cloud.githubusercontent.com/assets/1042916/16788828/2d50d894-4876-11e6-97b0-1cececb5e1d9.jpg)
![mean_yls](https://cloud.githubusercontent.com/assets/1042916/16788861/69099b32-4876-11e6-9bd4-d2ede1b5c51a.jpg)

**Comment by riklaunim** [comment]
Wrong project ;)
