### ISSUE TITLE
Is django-ckeditor support Gist embed

### ISSUE THREAD

**Issue by quki** [django-ckeditor/django-ckeditor#305]
Hi,
Thank you for awesome markdown editor, It is so helpful for my django blog.
I've been using  'codesnippet' plugin very well,

But I want to enable **Gist embed** using only url paste.
like `<script`  src="https://gist.github.com/quki/3ad779e0b7cf80122814e986b8b12822.js"></script>

**Is django-ckeditor support Gist embed?**

And If no support, Is there any way to post codes more convenient except code snippet.

Thank you,
Regards

**Comment by riklaunim** [comment]
django-ckeditor is just a form wrapper around ckeditor. It does not affect what ckeditor can and can't do. So it should work with proper config.

**Comment by quki** [comment]
Thank you for your advice!
