### ISSUE TITLE
Possible to change BrowseImageURL to subdirectory?

### ISSUE THREAD

**Issue by mboisvertUW** [django-ckeditor/django-ckeditor#306]
I am using S3 to store my images.  I have a separate process that is used to upload images via the django admin so I only use CKEditor to use images that are already uploaded.
My application is also multitenant to I need to store images by tenant so that each tenant can only see and use their own files.

I am currently using the structure of 
BUCKET/images/COMPANY_NAME to store the images.  I have the browse path set to /images/ in settings because the subdirectory will vary by tenant.

Is it possible using js or some other method to dynamically change the browse directory to go down to a subdirectory based on the company name?

**Comment by riklaunim** [comment]
You will likely have to modify the URLs for the browse views: https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/views.py and use your version of the view instead of the built in default one.

**Comment by mboisvertUW** [comment]
Is it possible to override that and still use the remainder of the package or do I need to duplicate the package and make my change?

**Comment by riklaunim** [comment]
You only have to change the view - put it in your code and then change the urls.py so that the browse urls point to your views and not the default ones.

**Comment by mboisvertUW** [comment]
Newbie here... 
Thank you for your help.  How would I change the urls to point to my views.py?

**Comment by mboisvertUW** [comment]
I got it!  Thank you so much for pointing me in the right direction :)
