### ISSUE TITLE
Autogrow JS is missing from plugins in django-ckeditor 5.1.0

### ISSUE THREAD

**Issue by peterfarrell** [django-ckeditor/django-ckeditor#311]
It appears that `autogrow/plugin.js` is missing from the plugins directory even though the documentation indicates that `django-ckeditor` ships with this plugin (just not enabled by default).

**Comment by riklaunim** [comment]
It's a full ckeditor package. Maybe they removed it ?

**Comment by peterfarrell** [comment]
@riklaunim Correct, it appears that AutoGrow is no longer in the standard or full packages download for CKEditor now. Don't know when that was removed from the standard / full package download from CKEditor. So it looks like the fix is either:

1.  Use a custom download of CKEditor and include Auto Grow for backwards compat with django-ckeditor
2. Change the documentation in django-ckeditor to not reference Auto Grow as an included plugin.

Typically, I'd vote for the first option. If it's decided to no longer include it in django-ckeditor, then the plugin really should be included for people and deprecated for a while so people know.

**Comment by riklaunim** [comment]
in ideal world bower or node would manage and install ckeditor stuff as desired so that Python package should not carry a copy of it :) but for now it will likely end in a custom package.

**Comment by peterfarrell** [comment]
@riklaunim Yea, however that would expect people to be using bower or node to compile / package their Django projects up.

+1 I'd just use a custom download of CKEditor. You could write a Python test to search the plugin directories for a list of expected plugin names to ensure they aren't forgotten in the future.

**Comment by riklaunim** [comment]
Should be fixed in 5.1.1
