### ISSUE TITLE
Missing plugins

### ISSUE THREAD

**Issue by chasmani** [django-ckeditor/django-ckeditor#312]
Unless I'm mistaken, there seems to be some missing plugins which the docs say should be included. The docs say the following plugins are installed, but not necessarily enabled:

a11yhelp, about, adobeair, ajax, autoembed, autogrow, autolink, bbcode, clipboard, codesnippet, codesnippetgeshi, colordialog, devtools, dialog, div, divarea, docprops, embed, embedbase, embedsemantic, filetools, find, flash, forms, iframe, iframedialog, image, image2, language, lineutils, link, liststyle, magicline, mathjax, menubutton, notification, notificationaggregator, pagebreak, pastefromword, placeholder, preview, scayt, sharedspace, showblocks, smiley, sourcedialog, specialchar, stylesheetparser, table, tableresize, tabletools, templates, uicolor, uploadimage, uploadwidget, widget, wsc, xml

I'm particularly interested in embed, embedbase and embedsemantic. These don't appear to be installed when I run pip install django-ckeditor, and do not appear in 
https://github.com/django-ckeditor/django-ckeditor/tree/master/ckeditor/static/ckeditor/ckeditor/plugins
(which is where I assume they should be).

Am I doing something wrong or are these plugins now missing?

**Comment by fzhukov** [comment]
+1 v5.1.0
on new project after collectstatic it is a problem, some plugins missing.
if do collectstatic on 5.0.3 and then upgrade plugin, errors not appears

**Comment by riklaunim** [comment]
I'll have a look at it. Maybe something changed in the default full package.

**Comment by peterfarrell** [comment]
This seems to be related to #311 .

**Comment by chasmani** [comment]
I fixed my problem by using an older version - version 5.0.0 has a full plugin suite. It seems there are quite a lot of plugins missing moving from 5.0.0 to 5.1.0. Looking through the history, it looks like the plugins disappear on this commit, 16 days ago, 
https://github.com/django-ckeditor/django-ckeditor/commit/25e60c129e9732d7ee7a48f1ca24db0832519b32

That commit is named "Update to CkEditor 4.5.10 full package." so yeah riklaunim it would make sense if the default full package is now smaller. 

Digging a little deeper, if you compare the plugins listed now and in an older version, e.g. 
https://github.com/django-ckeditor/django-ckeditor/tree/229ac1e1ad3a35f8ec5f9b3f930775440bb938b0/ckeditor/static/ckeditor/ckeditor/plugins

You can see that all the plugins that are now missing were added in a separate commit called "add new plugins". So maybe they are extra plugins that are not normally found in ckeditor but were added extra to django-ckeditor? So maybe they just need adding again - as in literally just drop the folders back into ckeditor/static/ckeditor/ckeditor/plugins?

**Comment by riklaunim** [comment]
Should be fixed in 5.1.1
