### ISSUE TITLE
Empty file models.py

### ISSUE THREAD

**Issue by Krejdom** [django-ckeditor/django-ckeditor#314]
Hi, there is an empty file `models.py`. Has it some purpose? It causes an error in rpmlint.

`python2-django-ckeditor.noarch: E: zero-length /usr/lib/python2.7/site-packages/ckeditor_uploader/models.py`

**Comment by riklaunim** [comment]
Rather from historic reasons - being required for a django app. You really want to distribute Python code as RPM?

**Comment by Krejdom** [comment]
Thanks.
It is already done, I am just updating the version. https://admin.fedoraproject.org/pkgdb/package/rpms/python-django-ckeditor/

**Comment by matthiask** [comment]
It's probably not required anymore (`django.apps` was introduced with Django 1.7, and django-ckeditor requires `Django>=1.8`)
