### ISSUE TITLE
widget i don't see upload image

### ISSUE THREAD

**Issue by CARocha** [django-ckeditor/django-ckeditor#315]
Hi, i use RichTextUploadingField for upload image in my model fields
but i use the widget 
from ckeditor.widgets import CKEditorWidget

class FlatpageForm(FlatpageFormOld):
    content = forms.CharField(widget=CKEditorWidget())
it good but i don't upload any imagen, what is the way for activate
the option upload imagen or put extraplugin like youtube plugin ???

thank a lot for any help or idea

**Comment by riklaunim** [comment]
There are two versions - without and with file upload ;) Those with upload are in ckeditor_uploader app.

**Comment by CARocha** [comment]
@riklaunim i put this in my setting installed apps
 'ckeditor',
  'ckeditor_uploader',
and my urls.py
url(r'^admin/', include(admin.site.urls)),
url(r'^ckeditor/', include('ckeditor_uploader.urls')),
and my flatpage equal the above code
from ckeditor.widgets import CKEditorWidget

class FlatpageForm(FlatpageFormOld):
    content = forms.CharField(widget=CKEditorWidget())
but i don't see any way for upload image :( :/ 
when i clic in image button only appear this
<img width="303" alt="captura de pantalla 2016-09-18 a las 9 04 25 p m" src="https://cloud.githubusercontent.com/assets/168115/18621635/adc471c8-7de3-11e6-9dbd-e0e2a6d4e343.png">

thank for you help!

**Comment by CARocha** [comment]
@riklaunim ok i now how to activate :) only import CKEditorUploadingWidget :)
thank for all !
