### ISSUE TITLE
Browse server images by path

### ISSUE THREAD

**Issue by abhinavnair** [django-ckeditor/django-ckeditor#316]
I am using the default img plugin and settings for ckeditor. What I would like is to restrict folder access while browsing server images through img plugin. So that means the browsable directory and the upload directory should dynamically change for a user.
How can I achieve this?

**Comment by riklaunim** [comment]
CKEDITOR_RESTRICT_BY_USER maybe?

**Comment by abhinavnair** [comment]
But I am not exactly talking about restriction per user. Something like, for some criteria only show data in /mydata/folder1/ and for other criteria show data in /mydata/folder2/

**Comment by riklaunim** [comment]
Then you would have to write a custom view that browse through folders and use that one instead of the built-in one.

**Comment by abhinavnair** [comment]
Custom view as in custom img plugin?
