### ISSUE TITLE
Travis not running?

### ISSUE THREAD

**Issue by adamchainz** [django-ckeditor/django-ckeditor#320]
I see the `.travis.yml` in the repo but https://travis-ci.org/django-ckeditor/django-ckeditor doesn't exist and there is no record of completed checks on pull requests. Has travis been disabled because the tests all use selenium and it doesn't work there?

**Comment by riklaunim** [comment]
I didn't set it up in the end, as at that time I didn't had all the permissions on the original repo. Should be doable now (and some test fixing too).

**Comment by matthiask** [comment]
I got a successful test run in my fork (which is exactly the same as django-ckeditor@master with https://github.com/matthiask/django-ckeditor/commit/4f7a11bc3c99337ca0894f402499afc8c998fda0 on top)

I used Saucelabs for the Selenium tests: https://travis-ci.org/matthiask/django-ckeditor/builds/234266842

It was really quite straightforward (even for a first time Saucelabs user). I can set up Saucelabs testing for this repository as well (if you want me to), but I'd probably need admin access for this. Or you can use my changes to do that yourself riklaunim.

**Comment by riklaunim** [comment]
Is Saucelabs available as free for open source projects? I see only free trial option there.

**Comment by matthiask** [comment]
They don't advertise it too much, but yes: https://saucelabs.com/open-source

**Comment by matthiask** [comment]
It seems to be working fine these days.
