### ISSUE TITLE
CTRL+ENTER --> submit

### ISSUE THREAD

**Issue by guettli** [django-ckeditor/django-ckeditor#322]
I would like to submit the form if the user enters CTRL+ENTER.

I found a solution here: https://dev.ckeditor.com/ticket/1533

> You can do it by adding [ CTRL + 13 /_Enter_/, 'Save' ] to the FCKConfig.Keystrokes. 

How to do this config in settings.py?

Is there a way to import `CTRL` in python?

**Comment by riklaunim** [comment]
you have to do it in JS - alter the config before ckeditor initialisation.

**Comment by guettli** [comment]
@riklaunim I have to do this in JS? Is this not possible in the django settings like the other configurations?

**Comment by guettli** [comment]
I found the solution here: http://stackoverflow.com/a/40693689/633961
```

CKEDITOR.on('instanceReady', function(evt) {
    evt.editor.setKeystroke(CKEDITOR.CTRL + 13, 'save');
})
```
