### ISSUE TITLE
fail to load mathjax

### ISSUE THREAD

**Issue by dborisog** [django-ckeditor/django-ckeditor#323]
I fail to load mathjax 

I'm not sure if this is the right place to write about this, but Source page content allows to assume it might be an issue.

I'll post my virtualenv config, CKEDITOR_CONFIGS, printscreen, and an element from the Source page.

**virtualenv**

```
>pip freeze
Django==1.10.2
django-appconf==1.0.2
django-ckeditor==5.1.1
django-compressor==2.1
django-debug-toolbar==1.6
Pillow==3.4.2
psycopg2==2.6.2
rcssmin==1.0.6
rjsmin==1.0.12
sqlparse==0.2.1
```

**CKEDITOR_CONFIGS**

```
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Custom': [
            {'name': 'document', 'items': [
                'Subscript', 'Superscript', ]},
            {'name': 'source', 'items': [
                'Source', ]},
        ],
        'toolbar': 'Custom',
        'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'height': 200,
        'width': 600,
        'extraPlugins': ','.join(['mathjax', ]),
    },
}
```

According to https://github.com/django-ckeditor/django-ckeditor/issues/256
I've changed ckeditor-init.js , I also tried various combinations, including {'name': 'math', 'items': ['mathjax', ]}, and {'name': 'math', 'items': ['Matjax', ]} in 'toolbar_Custom' list.

**Printscreen**

![screenshot021](https://cloud.githubusercontent.com/assets/4368019/19555522/cb2c3c6e-96c5-11e6-8065-c86f7395969d.jpg)

**Source**
As you can see the panel contains all config I setup in config but mathjax. However, the page source contains the "toolbar_Basic", "toolbar_Full" & "toolbar_Custom". I'm not sure if Basic and Full should be present, according to my config.

`<div class="django-ckeditor-widget" data-field-id="id_false_answer_text" style="display: inline-block;">
    <textarea cols="40" id="id_false_answer_text" name="false_answer_text" rows="10" required data-processed="0" data-config='{"toolbar_Basic": [["Source", "-", "Bold", "Italic"]], "toolbar_Full": [["Styles", "Format", "Bold", "Italic", "Underline", "Strike", "SpellChecker", "Undo", "Redo"], ["Link", "Unlink", "Anchor"], ["Image", "Flash", "Table", "HorizontalRule"], ["TextColor", "BGColor"], ["Smiley", "SpecialChar"], ["Source"]], "filebrowserUploadUrl": "/ckeditor/upload/", "skin": "moono", "filebrowserWindowWidth": 940, "filebrowserWindowHeight": 725, "width": 600, "height": 200, "filebrowserBrowseUrl": "/ckeditor/browse/", "language": "en-us", "toolbar": "Custom", "toolbar_Custom": [{"items": ["Subscript", "Superscript"], "name": "document"}, {"items": ["Source"], "name": "source"}, {"items": ["mathjax"], "name": "mathjax"}]}' data-external-plugin-resources='[]' data-id="id_false_answer_text" data-type="ckeditortype">&lt;p&gt;fa4 q1&lt;/p&gt;</textarea>
</div>
`

**Another config**
All-plugin config (according to a post from web) also shows no mathjax icon. Both with and without change of 'ckeditor-init.js

```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'none',
        'height': 200,
        'width': 600,
    },
}
```

![screenshot022](https://cloud.githubusercontent.com/assets/4368019/19555847/2af868ce-96c7-11e6-8353-f81c001df6c9.jpg)

So as example config from the README.rst

**Static files**
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
![screenshot023](https://cloud.githubusercontent.com/assets/4368019/19555958/97a7adae-96c7-11e6-80f7-6ff9695f9751.jpg)

**The quesiton**

If it is an issue, how can I quickfix it?

If it is related to configuration inexperience, could you please direct me to the config examples/the right config for mathjax?

UPD:
The printscreens come from Django admin, I use RichTextUploadingField in these models.

**Comment by fsharpasharp** [comment]
> I've changed ckeditor-init.js , I also tried various combinations, including {'name': 'math', 'items': ['mathjax', ]}, and {'name': 'math', 'items': ['Matjax', ]} in 'toolbar_Custom' list.

Try 'Mathjax'.

**Comment by dborisog** [comment]
@fsharpasharp thank you for pointing to the typo, I had a look. This typo was a part of this issue report and not of the config.

![image](https://cloud.githubusercontent.com/assets/4368019/20035622/fe700cc2-a3f4-11e6-9ddb-e6b631d34eef.png)

produces

![image](https://cloud.githubusercontent.com/assets/4368019/20035624/1be7e4f0-a3f5-11e6-9cb1-376f734ebce5.png)

(I haven't looked into internal mechanics, so just in case I played with 'name' as well -- no button for Mathjax was loaded in any alternative configs.)

**Comment by fsharpasharp** [comment]
I can't see the mathJaxLib variable in your recent screenshot.

I got it running yesterday, if you still can't see it I can post my config.

**Comment by dborisog** [comment]
@fsharpasharp , yes please, a working config would be highly appreciated.

**Comment by fsharpasharp** [comment]
Tell me if this worked.
```
CKEDITOR_CONFIGS = {
    'default': {
        'entities': False,
        'entities_greek': False,
        'entities_latin': False,
        'skin': 'moono',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YouCustomToolbarConfig': [
            {'name': 'basicstyles',
            'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
            'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                    'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            '/', 
            {'name': 'youcustomtools', 'items': [
                'Maximize',
                'ShowBlocks',
                'Save',
                'Source',
                'Image',
                'Embed',
                'Mathjax',
                'CodeSnippet',
                'Preview',
            ]},
        ],
        'toolbar': 'YouCustomToolbarConfig',
        'mathJaxLib': '//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join(
            [
                'div',
                'autolink',
                'autogrow',
                'widget',
                'lineutils',
                'clipboard',
                'dialog',
                'dialogui',
                'elementspath',
                'mathjax',
                'embed',
                'codesnippet',
                'image2',
            ]),
    }
}
```

**Comment by dborisog** [comment]
@fsharpasharp , thank you! It does work now.

Now I see in the pre-current config I had no `'extraPlugins': ','.join(['mathjax',]),`. 

And in the issue publication time I had `'extraPlugins': ','.join(['mathjax',]),` present, yet `{'name': 'math', 'items': ['Mathjax', ]},` absent. But at no moment of time I had both these parts in the config. 

If I am to replicate my line of thought for 17 days ago, I assumed these two lines as duplication, removed one 'unnecessary' line and failed configuration as the result. This was a misconfiguration issue on my side, sorry for the inconvenience.

**Comment by fsharpasharp** [comment]
All right! Glad to hear.

Yes, extraPlugins specifies the library to load, while the other is adding the item to the toolbar.
