### ISSUE TITLE
easy way to upload multiple images in django admin panel?

### ISSUE THREAD

**Issue by kinganu** [django-ckeditor/django-ckeditor#328]
Hi Im looking for a way to integrate multiple image uploads in my django admin panel.  I found ckeditor, and was able to set up a single image upload.  how to add more singles on top of that or unspecified number of images without too much hassle?

heres what I have working so far:

https://dpaste.de/fFss

**Comment by riklaunim** [comment]
File upload in django-ckeditor is only basic one for single files. There are more dedicated django apps for file upload and those would be a better choice.
