### ISSUE TITLE
upgrade to CKEditor 4.6

### ISSUE THREAD

**Issue by omalled** [django-ckeditor/django-ckeditor#329]
Are there any plans to upgrade to CKEditor 4.6? This would be really helpful for me.

**Comment by riklaunim** [comment]
Yes there are :) I just need a bit of time to do it. I hope to do it no later than weekend and I hope nothing breaks ;)

**Comment by omalled** [comment]
Did you ever get a chance to work on upgrading to 4.6? I'd be happy to pitch in, but would need some guidance. If there's anything I can do to help, please let me know.

**Comment by riklaunim** [comment]
Version updated and it works. With cached storage one GIF file has problem with collectstatic.

**Comment by nikolas** [comment]
This ticket can be closed - looks like django-ckeditor now has ckeditor 4.6.1 included.
