### ISSUE TITLE
Constants for configuration not available

### ISSUE THREAD

**Issue by guettli** [django-ckeditor/django-ckeditor#331]
AFAIK constants for configuration are not available.

This way I need to write this:

```
CKEDITOR_CONFIGS = {
    'default': {
       'enterMode': 2, 
    }
}
```

Today, tomorrow, maybe this whole month I know what `2` means.

But in one year I won't remember (and I don't want to remember) what this magic number means.

Is there a way to use the nice constants (for example `CKEDITOR.ENTER_BR`) in the settings?

Related: https://github.com/django-ckeditor/django-ckeditor/issues/289

**Comment by riklaunim** [comment]
It's Python generating JavaScript so it may not be possible.

**Comment by guettli** [comment]
@riklaunim thank you for your reply. Should I close this issue?

**Comment by tisdall** [comment]
A constant would work, but then this project would have to maintain a python file with constants that matched all the javascript constants.  For me, I'd just do this:
```
CKEDITOR_CONFIGS = {
    'default': {
       'enterMode': 2,  # CKEDITOR.ENTER_BR (2) – Lines are broken with <br> elements.
    }
}
```

**Comment by guettli** [comment]
I follow the programming guideline of the book "clean coder": avoid comments, make the code itself readable ...

Up to now I see no perfect solution for this issue. You could create a python file with constants, but this is not perfect.
