### ISSUE TITLE
New skin not working 

### ISSUE THREAD

**Issue by armsarun** [django-ckeditor/django-ckeditor#332]
I changed the skin in ckeditor 5.1.1

`CKEDITOR_CONFIGS = {
    'default': {
        'skin':'moonocolor',
        'toolbar': 'full',
        ],
    },
}

then ckeditor is not working . It is showing blank screen and getting the below issue

 "GET /static/ckeditor/ckeditor/skins/moonocolor/skin.js?t=G6DE HTTP/1.1" 404 1847
 "GET /static/ckeditor/ckeditor/skins/moonocolor/editor.css?t=G6DE HTTP/1.1" 404 1856

`

**Comment by riklaunim** [comment]
you have to put that additional skin in your static folder under ckeditor/ckeditor/skins/moonocolor/

**Comment by armsarun** [comment]
I put the monocolor in skins directory still i got error in console

 "GET /static/ckeditor/ckeditor/skins/moonocolor/skin.js?t=F7OI HTTP/1.1" 404 1847
"GET /static/ckeditor/ckeditor/skins/moonocolor/editor.css?t=F7OI HTTP/1.1" 404 1856

**Comment by riklaunim** [comment]
Are you sure the paths are correct?

**Comment by armsarun** [comment]
Yes It's working if I give 'skin' : 'moono'. Whenever I change the skin then issue comes

**Comment by riklaunim** [comment]
moono is in django-ckeditor static files. Django can't find your files under such path so it's 404. It's something related with your static files paths or configuration (like missing collectstatic)

**Comment by armsarun** [comment]
I put skin inside the app static directory and it works
