### ISSUE TITLE
How to add imagepaste plugins

### ISSUE THREAD

**Issue by istommao** [django-ckeditor/django-ckeditor#334]
I found i can't paste image from clipboard

**Comment by istommao** [comment]
@riklaunim

**Comment by riklaunim** [comment]
I don't know - the image upload plugin is a third party and may not be integrated with that event.

**Comment by istommao** [comment]
Add paste image feature support #335

**Comment by riklaunim** [comment]
merged

**Comment by istommao** [comment]
![image](https://cloud.githubusercontent.com/assets/5070879/21755336/5bf35036-d64d-11e6-8117-3c6c1491f1b1.png)

Make it work should set extraPlugins in CKEDITOR_CONFIGS

@riklaunim

**Comment by riklaunim** [comment]
I'll add that to readme and/or default config.

**Comment by riklaunim** [comment]
done.
