### ISSUE TITLE
Add youtube plugin to release

### ISSUE THREAD

**Issue by shtalinberg** [django-ckeditor/django-ckeditor#339]
You can add to next release youtube plugin allowed via config.extraPlugins = 'youtube';
http://ckeditor.com/addon/youtube

**Comment by riklaunim** [comment]
You can add any plugin you want to. It doesn't have to be in the Python package.

**Comment by shtalinberg** [comment]
How right do this?  I want use this app  only via  requirements, not copy to project source repo.

**Comment by riklaunim** [comment]
CKEditor is a JS app and thus is in static files. You can add additional static files and just add given pluging to the editor configuration.

**Comment by shtalinberg** [comment]
Ok, thanks.
If not will be add it's useful plugin to release this issue may be closed
