### ISSUE TITLE
a.ui.space is null due to eagerly initialising of CKEditor

### ISSUE THREAD

**Issue by Ryuno-Ki** [django-ckeditor/django-ckeditor#345]
We experienced failures with CKEditor if the page takes longer to load.
The error reads `a.ui.space` being null.

Our workaround was to [initialise](https://github.com/django-ckeditor/django-ckeditor/blob/45b51616736cb7e75eb080490daaa9e16877f106/ckeditor/static/ckeditor/ckeditor-init.js#L11) CKEditor on `$(window).on('load', initialiseCKEditor)`. Especially the `replace` [call](https://github.com/django-ckeditor/django-ckeditor/blob/45b51616736cb7e75eb080490daaa9e16877f106/ckeditor/static/ckeditor/ckeditor-init.js#L35) happened too early.

**Comment by n3storm** [comment]
where do you make the initialise in the page? bottom scripts?

having the same issue

**Comment by Ryuno-Ki** [comment]
Sorry, I left the company. Will close this ticket.

**Comment by n3storm** [comment]
@Ryuno-Ki this is not how this works. You should leave the issue open so somebody else could help or aknowledge there is an issue in certain conditions.

**Comment by Ryuno-Ki** [comment]
@n3storm I would consider that thread hijacking.

**Comment by matthiask** [comment]
It's clearly no thread hijacking. The issue you reported was about a problem with early initialization of the editor instance, and this has nothing to do with you going to work somewhere else.

Thanks @n3storm for reopening this issue. I haven't encountered the problem (yet?) but it clearly still exists somewhere.
