### ISSUE TITLE
Documentation question: S3 image backend?

### ISSUE THREAD

**Issue by nikolas** [django-ckeditor/django-ckeditor#355]
According to the README, `CKEDITOR_IMAGE_BACKEND` only has one valid value:

> Supported backends:
> * pillow: uses PIL or Pillow

Is Amazon S3 supported by django-ckeditor? If so, does the value of `CKEDITOR_IMAGE_BACKEND` matter?

**Comment by riklaunim** [comment]
S3 is supported. The backend system was created to make it usable with like Django on Google App Engine and other cases where PIL/Pillow could not be used (or when thumbnails are not needed).
