### ISSUE TITLE
CkEditor ImportError: No module named ckeditordebug_toolbar

### ISSUE THREAD

**Issue by ddwaraka** [django-ckeditor/django-ckeditor#365]
I was trying to install CkEditor for django. I followed instructions here: https://github.com/django-ckeditor/django-ckeditor. I did a `pip install` and it downloaded the latest version (5.2.1)

And when I do a `python manage.py collectstatic`, I get this error:
`CkEditor ImportError: No module named ckeditordebug_toolbar`

 I have CkEditor listed in `settings.py` under `INSTALLED APPS`. What could be the problem?

**Comment by riklaunim** [comment]
Check if you have a commas on the INSTALLED_APPS  list ;)
