### ISSUE TITLE
Upload the file because the iframe cross-domain js error

### ISSUE THREAD

**Issue by An0nymous0** [django-ckeditor/django-ckeditor#367]
ERROR:
Blocked a frame with origin "localhost:8081" from accessing a frame with origin "localhost:8080". Protocols, domains, and ports must match.

FilebrowserUploadUrl return value can be the same as the uploadUrl JSON value to solve cross-domain execution js problem。

**Comment by riklaunim** [comment]
It's rather something with the django configuration. It should build urls for the same domain.
