### ISSUE TITLE
Restricting image dimensions when uploading it.

### ISSUE THREAD

**Issue by CraigOToole** [django-ckeditor/django-ckeditor#370]
Hoping there's a way to resize an image to a smaller size if it is too big, or the ability to make the height/width auto if possible.

any solutions?

**Comment by appli-intramuros** [comment]
Hello, I have done this feature (set max size for image upload) in a fork.
Take a look: https://github.com/appli-intramuros/django-ckeditor

You just have to set CKEDITOR_IMAGE_MAX_WIDTH and/or CKEDITOR_IMAGE_MAX_HEIGHT
