### ISSUE TITLE
Set max height and width for uploaded image

### ISSUE THREAD

**Issue by predragfalcic** [django-ckeditor/django-ckeditor#371]
Is there a way to set the max width and max height of images that can be uploaded? Because I have this problem, I upload the image with the editor and when I display it later it looks like this: 

![screenshot 6 _li](https://cloud.githubusercontent.com/assets/18352038/23994821/ea22102c-0a46-11e7-93bc-60b42df26466.jpg)

The first picture(the one with the horses) is not uploaded with ckeditor, and it is displayed with html <img> tag, like this:

    {% if post.header_photo %}
        <img src="{{ post.header_photo_url|default_if_none:'#' }}" class="img-responsive" style="width: 100%; height: 300px;">
    {% endif %}

Is there a way that the body picture (picture with the dogs) is automatic resized to fit in the div? Can I add some classes to that img tag? 

Here is my html code():

    <div class="row" style="overflow: hidden; width: 100%; margin-left: 5px; margin-right: 5px; overflow-wrap: break-word;">

        {{ post.body|safe}}

    </div>

this is the code that is displaying the text and the image that I uploaded in the ckeditor and saved to the database.

**Comment by riklaunim** [comment]
You can set styles when inserting the image (width/height) or later change the HTML code in source mode. If needed style images in a CSS file using container class name to limit the style to images in the content.

**Comment by aoviedo92** [comment]
Same issue here. But styling css doesn't fit for me. I've to change the image size and quality for every image I upload with django-ckeditor. Any suggestion?

**Comment by edouarobin** [comment]
Hello, I have done this feature (set max size for image upload) in a fork.
Take a look: https://github.com/appli-intramuros/django-ckeditor

You just have to set CKEDITOR_IMAGE_MAX_WIDTH and/or CKEDITOR_IMAGE_MAX_HEIGHT

**Comment by fivan999** [comment]
Hello. Can I make such thing, that for every image I upload in CKeditor width will be automatically set to 100%, like <img src="some-image" width="100%" />? Width and height attribute for image do not fit for me. Would be grateful for every suggestion

**Comment by fivan999** [comment]
I solved my problem. You just need to paste this code in static/ckeditor/ckeditor/config.js:
`
CKEDITOR.on('instanceReady', function (ev) {
    ev.editor.dataProcessor.htmlFilter.addRules({
        elements: {
            $: function (element) {
                if (element.name == 'img') {
                    var style = element.attributes.style || '';
                    if (!style.match(/max-width/)) {
                        style += ';max-width: 100%';
                    }
                    if (!style.match(/max-height/)) {
                        style += ';max-height: 100%';
                    }
                    element.attributes.style = style;
                }
            }
        }
    });
});
`
and do shift+f5 to reload your browser's cache. Hope it would be helpful for somebody.
