### ISSUE TITLE
Image uploading in ckeditor works only for the superuser

### ISSUE THREAD

**Issue by max11** [django-ckeditor/django-ckeditor#372]
Image uploading works only for the superuser, for other users it shows the login form in the administrative panel. What should I do to give access to all users registered on the site to upload an image in CKEDITOR_UPLOAD_PATH?
![1212](https://cloud.githubusercontent.com/assets/1011961/24355830/1d5e54ca-1300-11e7-88a0-d8bbd6ef6e0b.JPG)

**Comment by riklaunim** [comment]
You have to add those two urls https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/urls.py instead of the include and use login_required decorator instead of staff_member_required
