### ISSUE TITLE
Why the images didn't load?

### ISSUE THREAD

**Issue by ylto** [django-ckeditor/django-ckeditor#373]
![selection_042](https://cloud.githubusercontent.com/assets/1755417/24588610/b73c46e8-17f5-11e7-8011-e75716e3f824.png)
![selection_043](https://cloud.githubusercontent.com/assets/1755417/24588612/b9e7ec58-17f5-11e7-8a3c-9085e5e2291c.png)

I have no problem in uploading images, but the images uploaded didn't even load. I can't figured out what's wrong. did you know why?

**Comment by riklaunim** [comment]
Check the URL you are getting there - likely your media configuration needs a change.

**Comment by ylto** [comment]
on settings.py
`MEDIA_ROOT = os.path.join(BASE_DIR, 'media')`
`MEDIA_URL = 'media/'`

The link is `media/uploads/2017/04/02/blue-square.jpg`

![image](https://cloud.githubusercontent.com/assets/1755417/24589494/8eb23b32-1805-11e7-872c-f599e03a03e3.png)

**Comment by matthiask** [comment]
Your `MEDIA_URL` should probably start with a slash (`MEDIA_URL = '/media/'`)

**Comment by tayler-kemsley** [comment]
I'm having the same problem. I can see the image there in the media/uploads/2017/04/09 directory, but it's not loading on the page.

Did you ever manage to get to the bottom of it?

My settings are the same as ylto.

`MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'`

**Comment by riklaunim** [comment]
Do your media handling actually works in Django? The only reason they are not displayed is because Django isn't handling them (in development).

**Comment by ylto** [comment]
My bad, I forgot to add urlpattern for media. Here's how I solved it 

`from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)`

https://docs.djangoproject.com/en/1.11/howto/static-files/

**Comment by tmikulin** [comment]
my fault was adding the "+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)" in the wrong urls.py file....
