### ISSUE TITLE
A way to set window.CKEDITOR_BASEPATH ?

### ISSUE THREAD

**Issue by crucialfelix** [django-ckeditor/django-ckeditor#374]
I cannot find anything in the docs or source code.

Due to some silliness between angular router and Django  I've needed to explicitly set the base href on my admin pages:

```html
 <base href="/admin/nsmailings/openhousemailing/add/">
```

Now CKEDITOR incorrectly finds the static files, thinking they must be relative to the base:

```
/admin/nsmailings/openhousemailing/add/config.js/change/ Failed to load resource: the server responded with a status of 404 (Not Found)

/admin/nsmailings/openhousemailing/add/skins/moono-lisa/editor.css/change/ Failed to load resource: the server responded with a status of 404 (Not Found)

/admin/nsmailings/openhousemailing/add/lang/en.js/change/ Failed to load resource: the server responded with a status of 404 (Not Found)
```

I now have to set the javascript variable by stuffing this in my admin change_form.html:

```html
<script>
  window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';
</script>
```

TBH I'm not quite sure how django-ckeditor could easily offer some way to pass through django settings like this.  Maybe there isn't anything that you can do that is convoluted.

**Comment by matthiask** [comment]
A similar problem exists when using ``ManifestStaticFilesStorage``. I've opened a pull request containing a documentation patch in #376, maybe this problem could be mentioned as well there?

**Comment by crucialfelix** [comment]
At least with ManifestStaticFilesStorage the non-hashed files are still there, so the webserver should be able to find them. But you don't get content hashing of course.

**Comment by matthiask** [comment]
A fix has been merged (#377)

**Comment by crucialfelix** [comment]
That will work: `data-ckeditor-basepath="{% static 'ckeditor/ckeditor/' %}"`

Thanks for that ! I think we can close now.

**Comment by riklaunim** [comment]
should work now.

**Comment by shashwatbahuguna** [comment]
With s3boto3 django storage backend for AWS S3 the data-ckeditor-basepath attribute of the script tag returns a 403 Forbidden error (since get request location is directory instead of file) which in turn renders ckeditor unusable on django admin panel.
Here content is richtext uploading field:
![image](https://user-images.githubusercontent.com/56976514/128070239-322347eb-726a-4a69-8b79-f4bbd5011168.png)
![image](https://user-images.githubusercontent.com/56976514/128071990-fe507dbf-1fea-44c2-831c-2597bd28de52.png)

**Comment by matthiask** [comment]
The s3boto3 backend behaves differently then and still appends query parameters when using `{% static %}` with a relative folder path.

You should probably set `CKEDITOR_BASEPATH` to the correct value using `https://s3.au-syd.cloud-....` without going through `{% static %}` then.

**Comment by shashwatbahuguna** [comment]
Aah interesting. Actually I've been trying to use ckeditor with django admin panel and couldn't think of a way to declare the variable in the template itself. 
I was able to find a temporary workaround by overriding the default admin template with a custom script tag just for ckeditor. This makes me question whether the basepath attribute is actually used and where exactly.

**Comment by shashwatbahuguna** [comment]
Aah interesting. Actually I've been trying to use ckeditor with django admin panel and couldn't think of a way to declare the variable in the template itself.

I was able to find a temporary workaround by overriding the default admin template with a custom script tag just for ckeditor (which didn't have the basepath attribute) (probably should have tried adding the variable instead in hindsight). 
This makes me question whether the basepath attribute is actually required. 

Regardless I'll try adding the custom variable instead by passing a context variable for the static path instead.
Thanks.
