### ISSUE TITLE
Compatibility: TypeError raised on Django 1.11

### ISSUE THREAD

**Issue by MacLake** [django-ckeditor/django-ckeditor#375]
Hello,

I just tested todeay’s update to Django 1.11 and noticed that I get an exception when there’s a form with a CKEditor from django-ckeditor:

> TypeError at …
> build_attrs() got an unexpected keyword argument 'name'

> virtualenvs/cert/lib/python3.4/site-packages/ckeditor/widgets.py in render

`111        final_attrs = self.build_attrs(attrs, name=name)`

In 1.10 the same code works without any problem.

**Comment by matthiask** [comment]
This has already been fixed in #364, but there's no new release yet.

**Comment by MacLake** [comment]
Okay, thanks!

**Comment by peterfarrell** [comment]
Any ETA on the release with this fix included?

**Comment by agronick** [comment]
So many apps broke because of this one change. I really do not get why they thought such an incompatible change was so important.

**Comment by matthiask** [comment]
It's a change in an undocumented internal function, @agronick.

If you don't agree, you should follow Django's development more closely and/or bring your complaint do the django-developers mailing list.

Not everyone agrees with the view you're expressing that Django is moving too fast.

**Comment by riklaunim** [comment]
I'll try to make a release over the weekend (and maybe add some developers to the team too ;))

**Comment by Arlefreak** [comment]
Meanwhile: 

`pip uninstall django-ckeditor && pip install git+https://github.com/django-ckeditor/django-ckeditor.git@master`

**Comment by riklaunim** [comment]
5.2.2 released

**Comment by Flimm** [comment]
Yay! Thanks for releasing this fix. It works based on my testing.

**Comment by melvyn-sopacua** [comment]
@matthiask It's undocumented, but not internal (not underscore prefixed). It's also completely useless now. The good thing about `build_attrs` was that you can use the much shorter keyword arguments syntax instead of writing a dict. Now, it's just merging two dicts, so I may as well use `atrrs.update()`.
The only reason for keeping it, is backwards compatibility and that fails. Beats me why this was done.

**Comment by matthiask** [comment]
@melvyn-sopacua The Django documentation contains a clear statement about that:

> In general, everything covered in the documentation – with the exception of anything in the internals area is considered stable.

(From https://docs.djangoproject.com/en/1.11/misc/api-stability/)

So it's not about underscores, but about whether it was documented or not. Anyway, if you want to propose the inclusion of a backwards-compatible wrapper this would not be the correct place to do this.

**Comment by allexiusw** [comment]
> 5.2.2 release

Thanks Django 1.11 works nices with Ckeditor 5.2.2.
