### ISSUE TITLE
Can't use colors

### ISSUE THREAD

**Issue by Sibiryakanton** [django-ckeditor/django-ckeditor#386]
Hello. I have a problem with using colors of the text in my site. There is page with my inscriptions.
http://j-star.ru/business/

They should be marked with different colors, but remains black. How you can see, works only part of colors. What am i do wrong?

P.S. Python 3.4, Django 1.11.

**Comment by matthiask** [comment]
Can you elaborate? I'm seeing different colors on the page you linked.

![capture](https://cloud.githubusercontent.com/assets/2627/25311939/161c1d56-280d-11e7-86d4-471e0baa90d7.PNG)

**Comment by Sibiryakanton** [comment]
The hosting's support tried to check that issue, and they do it without problem. I really confused. 

Second example with screenshots.
In editor:
https://yadi.sk/i/sUG2S4gK3HFvP6

On page:
https://yadi.sk/i/6ucrbZXJ3HFvRj
Link on page:
http://j-star.ru/products/54/

That's what i mean.

**Comment by matthiask** [comment]
Sorry for the question, but are you 100% sure that you actually saved the description, and that there is no caching or something else sending out old content? Because further up in the page the text is red, so it seems to work (at least sometimes).

**Comment by Sibiryakanton** [comment]
I check the page in Mozilla (i used Chrome) and used two different profiles in Chrome. The result is same: specifically the title 'Почему зерна YO Coffee имеют более бледный цвет по сравнению с обычным кофе?' is still black. I even added another exactly the same title, and he is works fine, but icant do anything with old text.
Why two identific titles shows in template with different colors?

**Comment by Sibiryakanton** [comment]
I find the reason of bug.
if i write the text with color (without any parameters like bold, italic and underline) and save that, is shows fine, and i in second try i add formatting, is still works fine. But if i do all formatting in one try and save that, the colors will ignoring.

**Comment by matthiask** [comment]
Great to hear it works now. It still sounds like there's a CKEditor issue; the correct place for that is https://dev.ckeditor.com/wiki/Bugs . Thanks!
