### ISSUE TITLE
export to doc or docx

### ISSUE THREAD

**Issue by mrillusion** [django-ckeditor/django-ckeditor#390]
hey, I tried using CKEditor in my django project , and I need to export after editing some text but i can't find any plugin or button to export to doc or docs! what should i do? is CK has any feature for this ?

**Comment by matthiask** [comment]
There's probably no ready-made plugin, certainly not in django-ckeditor (it's also out of scope)

You should be able to put something together using for example html5lib/lxml/Beautifulsoup to parse the HTML, and https://python-docx.readthedocs.io/ or a comparable package to reassemble the parsed document structure.
