### ISSUE TITLE
django-ckeditor图片上传只能在admin里面用吗？

### ISSUE THREAD

**Issue by fuckingsourcecode** [django-ckeditor/django-ckeditor#391]
在前台用图片上传一直有各种问题

**Comment by matthiask** [comment]
I'm sorry, I can read a few languages but this isn't one of them.

**Comment by fuckingsourcecode** [comment]
I want to using django-editor in normal enviroment, not admin, but the upload image always error

**Comment by fuckingsourcecode** [comment]
I want to use django-editor in normal enviroment, not admin, but the upload image always error

**Comment by fuckingsourcecode** [comment]
I want to use django-editor in normal enviroment, not admin, but uploading image from locale always error,

**Comment by matthiask** [comment]
See point 5 here: http://django-ckeditor.readthedocs.io/en/latest/#required-for-using-widget-with-file-upload

By default, upload views are decorated using `@staff_member_required`. You'll have to add the views yourself to a URLconf of your choice.

**Comment by fuckingsourcecode** [comment]
thanks, I will have a try, now, china is midnight.

**Comment by fuckingsourcecode** [comment]
thank you very much, I solved this problem!

**Comment by yslhzj** [comment]
> 非常感谢，我解决了这个问题！

How exactly did you solve it? Can you take a look at the code?
请问您是具体是怎么解决的?能否看一下代码?
