### ISSUE TITLE
How to add custom plugins?

### ISSUE THREAD

**Issue by Xosted** [django-ckeditor/django-ckeditor#392]
Hello,
Sorry if this is not the right place to ask. I am trying to create a custom plugin following [this guide](http://docs.ckeditor.com/#!/guide/plugin_sdk_sample_1). I created the files as indicated and added
`CKEDITOR_CONFIGS = {
    'default': {
        'extraPlugins': ','.join(
            [
                'myplugin'
            ]
        ),
    }
}`
to the settings.py

However, when I try to load the page, the editor doesn't appear and I get the following error:
`GET http://127.0.0.1:8000/static/ckeditor/ckeditor/plugins/myplugin/plugin.js?t=GB8C 404 (NOT FOUND)`
All the files are exactly at the path shown here. I found that other people had this problem with regular plugins if they had not ran:
`manage.py collectstatic`
But I did and STATIC_ROOT is defined. Is there something particular with custom plugins?
I probably did something wrong but I can't find what. I'd appreciate a bit of help thank you.

Cheers

**Comment by riklaunim** [comment]
Are you sure with the path? It's a double ckeditor folder inside one of your static folders.

**Comment by Xosted** [comment]
Yes, I noticed this too. But that is the way the folders are indeed.
The first ckeditor folder contains a ckeditor-init.js file and 3 folders : ckeditor, file-icons, gallerific.
The second (inner) ckeditor folder has a different structure and contains the plugins folder in which I put my custom plugin.

**Comment by matthiask** [comment]
The double ckeditor structure is correct. Does the additional information in 4fba4699c45921e0fa07f68fed639a3e28923568 help?

**Comment by Xosted** [comment]
Hello, sorry for the very long delay of response. I had to put this aside for a while. Now I am back to it I'm not sure to understand what to do with the link you provided. The code sample provided does not match the syntax provided in the official guide. Besides, I don't actually know where I would be expected to put this code.
It's frustrating as I guess this must be a minor configuration issue. The error message has changed slightly this is the exact one that I can find in the Firebug console:

>  Error: [CKEDITOR.resourceManager.load] Resource name "myplugin" was not found at "http://127.0.0.1:8000/static/ckeditor/ckeditor/plugins/myplugin/plugin.js?t=GB8C".
and in Django's console:

> [12/Jul/2017 23:15:27] "GET /static/ckeditor/ckeditor/plugins/myplugin/plugin.js?t=GB8C HTTP/1.1" 404 1866

**Comment by matthiask** [comment]
Maybe you can read the discussion at https://github.com/django-ckeditor/django-ckeditor/commit/4fba4699c45921e0fa07f68fed639a3e28923568 and see whether the comments help?

**Comment by matthiask** [comment]
`plugin.js` seems to be not there when using the builder. I'm not sure I can help much since I'm only using CKEditor with a really minimal configuration.

**Comment by Xosted** [comment]
I am not using the builder. This discussion is useful for whom uses the builder, then adds more plugin. I'm trying to build my own plugin and to do so, I'm following the official guide, as indicated in my original post.
It seems very simple but for some reasons, my plugin is not loaded, something is not found.

**Comment by Xosted** [comment]
This is the content of my plugin.js:
`CKEDITOR.plugins.add( 'myplugin', {
    icons: 'myplugin',
    init: function( editor ) {
        // Plugin logic goes here...
        editor.addCommand( 'myplugin', new CKEDITOR.dialogCommand( 'mypluginDialog' ) );

        editor.ui.addButton( 'myplugin', {
            label: 'My Plugin',
            command: 'myplugin',
            toolbar: 'insert'
        });
    }
});`

It follows, I think, what the guide is indicating. For some reasons, the resource is not found.

**Comment by matthiask** [comment]
Ah I see.

It seems to me that this issue is not specific to django-ckeditor — maybe you'll get better help when you ask in the CKEditor forums?

**Comment by Xosted** [comment]
I actually found the issue. It is not related to CKeditor but to the way Django handles static files. I have put my custom plugin into the ckeditor folder located in the static folder. This s wrong. The static folder designated by the STATIC_ROOT is to be filled only by running collectstatic. Any file added in other ways will be ignored. By putting the files related to the custom plugin into another folder, listed in STATICFILES_DIRS, then running collectstatic, it gets added to the STATIC_ROOT folder and can then be served. I still have errors, but not related to finding the resource.
