### ISSUE TITLE
Save data in custom form?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [django-ckeditor/django-ckeditor#394]
Hello! First of all **THANK YOU** for this project!

I have model **Post**  with field **description**. I am tring to create custom form where user can create new Post object by adding text, picture to description field. I have 2 problems.

1) When I click submit button, it dont create new Post object. It just show my form again. I thought next my code would be create new object and update list of objects (posts) but unfortunatly it didnt work.

2) I cant load picture from computer. Also 'Select from server' redirect me to admin login page. How to fix it?

![default](https://cloud.githubusercontent.com/assets/8999232/26245902/46ca3a0e-3cb8-11e7-9748-b872f3db5485.PNG)

a) I add _ckeditor_ and _ckeditor_uploader_ to _INSTALLED_APPS_ setting.py

b)  I run the collectstatic management command.

**urls.py:**
```
url(r'^ckeditor/', include('ckeditor_uploader.urls')),

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

**settings.py:**
```
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_root')
MEDIA_URL = '/media/'

CKEDITOR_UPLOAD_PATH = "media/uploads/"
CKEDITOR_JQUERY_URL = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_UPLOAD_SLUGIFY_FILENAME = False
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True
```
**models.py:**
```
class Post(models.Model):
    description= RichTextUploadingField(_('Description'))
```

**forms.py:**
```
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('description',)
        widgets = {
           'description': CKEditorUploadingWidget()
        }
```

**views.py:**
```
def post_add(request):
    data = dict()
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False)
           ***Some code***
            specipost ication.save()
            data['form_is_valid'] = True
           posts = Post.objects.all()
           context = {'posts ': posts }
                context.update(csrf(request))
                data['html_post'] = render_to_string('project/post_list.html', context)
        else:
            data['form_is_valid'] = False
    else:
        post_form = PostForm()
    context = {'post_form': post_form}
    data['html_post_form'] = render_to_string('project/post_add.html', context, request=request)
    return JsonResponse(data)
```

**post_add.html:**
```
{% load widget_tweaks %}

  {{ post_form.media }}

  <form method="post" action="">
      {% csrf_token %}

      {% for field in post_form %}
         {% render_field field class="form-control" %}
      {% endfor %}

      <button type="submit">Create</button>
    </form>

<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>

<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
```

**Comment by matthiask** [comment]
Hey; look at the second bullet point here (and reopen the issue if it does not work for you!)

http://django-ckeditor.readthedocs.io/en/latest/#restricting-file-upload

Thanks!

**Comment by NogerbekNurzhan** [comment]
@matthiask Hello! You mean just add `CKEDITOR_ALLOW_NONIMAGE_FILES = False` to setting? I tested it with this setting but it dont work anyway. Do you have any ideas? I really need help pls.

**Comment by matthiask** [comment]
No, the second point:

> By default the upload and browse URLs use staff_member_required decorator - ckeditor_uploader/urls.py - if you want other decorators just insert two urls found in that urls.py and don’t include it.

**Comment by matthiask** [comment]
So you probably want something like:

```
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache

urlpatterns += [
    url(r'^upload/', login_required(views.upload), name='ckeditor_upload'),
    url(r'^browse/', never_cache(login_required(views.browse)), name='ckeditor_browse'),
]
```

.. instead of the `include('ckeditor_uploader.urls')` thing.

**Comment by NogerbekNurzhan** [comment]
@matthiask Thank you! It works but you know I notice that in Firefox its impossible to enter nothing to inputs. Works fine only Chrome. Also what can you say about my first question? What can you advice? My view.py is not correct?

**Comment by matthiask** [comment]
Well... `            specipost ication.save()` does not look valid. However, this has nothing to do with django-ckeditor.

**Comment by NogerbekNurzhan** [comment]
@matthiask well it was mistake in post. In fact that was `post.save()`. Whats the best way to save data to DB from CKEditorUploadingWidget?

**Comment by NogerbekNurzhan** [comment]
@matthiask Do you have any ideas? Pls help me. Why in Firefox it didnt work correct?! How to save data correctly?
