### ISSUE TITLE
Single Quotes in config are not escaped

### ISSUE THREAD

**Issue by ronnievdc** [django-ckeditor/django-ckeditor#398]
Single quotes in the config dict are not escaped.

Code
`'config': json_encode(self.config)`

HTML
`data-config='{{config|safe}}'`

json_encode does not escape single quotes, therefore config dicts with single quotes invalidates the data-config attribute. This leads to default configuration with all the plugins enabled.

Suggested code
`'config': json_encode(self.config).replace('\'', '&apos;')`

**Comment by matthiask** [comment]
Good find. An easier (and probably safer) fix is to simply drop `|safe`, even if this makes the JSON much more verbose.
