### ISSUE TITLE
django-ckeditor with django-pipeline (or other minifier)

### ISSUE THREAD

**Issue by romulocollopy** [django-ckeditor/django-ckeditor#399]
I've been trying to make the `5.2.2` version to work with [django-pipeline](https://github.com/jazzband/django-pipeline) without any success success.

Django-Pipeline is a JS/CSS minifier that changes the way the `{% static %}` tag works, versioning and compressing the statics. The issue is that when it is done, some JS loses the reference to CKEditor's `config.js`.

When I insert the `CKEditorUploadingWidget` in my admin model, it searches from the config.js relative to my url, in `/admin/blog/entry/217/change/config.js` not in `/static/ckeditor/ckeditor/config.js`, and as it doesn't find it, it breaks.

To reproduce, you should use django-pipeline and django-ckeditor in admin, with the pipeline enabled.

The version 5.0.3 works with Django 1.10. It is blocking me to move to Django 1.11.1

I'd appreciate if someone help me to fix it.

**Comment by riklaunim** [comment]
Do you have to have it in the admin panel? 

Similar behaviour can happen with for example django-assets - but there you can write rewrite rules for the paths that change.

**Comment by matthiask** [comment]
Sounds like you have to set `CKEDITOR_BASEPATH`. The full path for `config.js` is constructed using the autodetected basepath of CKEditor, which does not work if there is no script tag with a `src` attribute ending in `ckeditor.js`.

Search http://django-ckeditor.readthedocs.io/en/latest/ for CKEDITOR_BASEPATH  (I now see that the instructions are in the wrong section. Will fix.)

**Comment by matthiask** [comment]
Also: If you can test current django-ckeditor@master and report back whether this fixes the problem without having to set CKEDITOR_BASEPATH manually that would be awesome.
