### ISSUE TITLE
Set a default font family in ckeditor

### ISSUE THREAD

**Issue by Archelunch** [django-ckeditor/django-ckeditor#404]
How can I set a default font family?

**Comment by riklaunim** [comment]
Font family of what? Likely a part of your site layout.

**Comment by Archelunch** [comment]
How can I set font in configs?
`CKEDITOR_CONFIGS = {
       'default': {
           'toolbar':[
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
        ],
           'height': '200px',
           'width': '450px',
           'removePlugins': 'stylesheetparser',
           'extraPlugins': 'codesnippet',
       },
}`

**Comment by riklaunim** [comment]
shouldn't it be set in CSS?

**Comment by Sanjeetkumar163** [comment]
I need the same, how can I set the default font family?

**Comment by HashimJaved09** [comment]
How can I add a specific font in django-ckeditor...???

**Comment by wesleyi23** [comment]
Is there a solution to this?

**Comment by matthiask** [comment]
Sure, use the `contentsCss` setting in `CKEDITOR_CONFIGS["default"]` : https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsCss

**Comment by nkrings-nettersheim** [comment]
Could someone explain this in a deeper way? I need some more fonts in the pulldown menu of fonts in django-cheditor. For example a google font.
Excuse me, but the link to ...cfg-contensCSS doesn't help me :-(

**Comment by matthiask** [comment]
We're all volunteers here. So I'll just offer a few screenshots here.

Excerpt from a `settings.py` from one of my current projects:

![image](https://user-images.githubusercontent.com/2627/92325846-0fb72e80-f04e-11ea-9f29-896922ffd018.png)

The `app/static/app/ckeditorstyles.css` file looks as follows:

![image](https://user-images.githubusercontent.com/2627/92325864-28274900-f04e-11ea-89f7-31c2c04cc374.png)

I hope this gets you started.

**Comment by brahim024** [comment]
Hi guys can I set one size because some user write comment with big text and that Distorts my template can anyone help me ?

**Comment by Kalkulus1** [comment]
> Hi guys can I set one size because some user write comment with big text and that Distorts my template can anyone help me ?

Don't know if you still need it. A way I went around it was to write my content in HTML cards. Example:

```html
<div class="card">
    <div class="card-body">
        <p> Your content here </p>
    </div>
</div>
```
