### ISSUE TITLE
ckeditor/ckeditor_uploader/admin_base.css missing, hence browser will HTTP 500 in production mode

### ISSUE THREAD

**Issue by karolyi** [django-ckeditor/django-ckeditor#405]
hey,

I'm using `django-pipeline` which compiles all the static assets into their versioned files, and then uses a json file to find those files when serving live content. 

When Django is running in live mode, since `ckeditor/ckeditor_uploader/admin_base.css` is missing, the file browser view which uses this css, will result in a `HTTP 500`.

please either remove the file requirement from `ckeditor_uploader/templates/ckeditor/browse.html`, or put the file in place.

cheers,
László

**Comment by matthiask** [comment]
Thanks for the report. This has already been fixed here df2a780a94201438f0cbc05d2c2588ae5865583b but no new release has been rolled yet.
