### ISSUE TITLE
DOMContentLoaded event don't fire when form is added by JQuery's .html() function

### ISSUE THREAD

**Issue by vanphong1310** [django-ckeditor/django-ckeditor#407]
My form:

```
<form id='create_form' method="post" action="{{ request.path }}"> {% csrf_token %}
        <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
        ...
</form>
```
It is rendered from server and send via a ajax request then I want add it to bootstrap modal by jquery's .html(). When I do that, ckeditor don't work, only normal textarea tag appears.
I discover this code never run:

```
document.addEventListener('DOMContentLoaded', function() {
    initialiseCKEditor();
    initialiseCKEditorInInlinedForms();
});
```

when I change it to:

```
$(function() {
    initialiseCKEditor();
    initialiseCKEditorInInlinedForms();
});
```

it works well!
I use django-ckeditor 5.3.0.
django-ckeditor 5.2.2 works well.

Sorry, I dont know English very well!

**Comment by baxeico** [comment]
I had the same problem. You can trigger the `DOMContentLoaded` event after injecting your form HTML in the DOM, like this:
```
window.document.dispatchEvent(new Event("DOMContentLoaded", {
    bubbles: true,
    cancelable: true
}));
```

**Comment by matthiask** [comment]
Shouldn't `document.readyState` be `complete` or something in this case anyway? It seems to me that the bundled JS should run initialisers even without the synthetic `DOMContentLoaded` event.

**Comment by baxeico** [comment]
My use case is a Django form injected dynamically (using jQuery .html() method) in a Bootstrap modal. Without the synthetic `DOMContentLoaded` event a django-ckeditor `RichTextField` was rendered as a simple TextArea. With the synthetic event fired after the form is injected in the DOM, the form field is rendered correctly with CKEditor.
