### ISSUE TITLE
Uploading image file without extension crashes ckeditor

### ISSUE THREAD

**Issue by swalladge** [django-ckeditor/django-ckeditor#409]
```
  File "venv/lib/python3.6/site-packages/ckeditor_uploader/views.py", line 88, in post              
    if(str(saved_path).split('.')[1].lower() != 'gif'):             
IndexError: list index out of range      
```

This is on the latest master branch, and occurs when attempting to upload an image which doesn't have a file extension (eg. `screenshot`) - this is with CKEDITOR_ALLOW_NON_IMAGE_FILES=False - haven't tested otherwise.

**Comment by riklaunim** [comment]
will fix
