### ISSUE TITLE
Browsing images broken when using custom prefix

### ISSUE THREAD

**Issue by swalladge** [django-ckeditor/django-ckeditor#410]
PR #178 enabled use of a custom user attribute to be used as the upload prefix, but unfortunately this only was added to the upload function. Browsing images still uses the old behaviour (`get_username()`).

This means that browsing images is broken if a custom prefix other than get_username() is used and the user isn't a superuser.

**Comment by matthiask** [comment]
@sbussetti do you want to take a look at this?

**Comment by sbussetti** [comment]
@matthiask yeah you got it and @swalladge let me know if you're preparing a PR for this, otherwise I'll have one shortly in response to this issue.

**Comment by swalladge** [comment]
@sbussetti It's not super high priority for me right now, since I'm simply using `get_username()` for now, so I hadn't started working on a PR. I'm more that happy to work on it and submit a PR sometime next week if no-one else is planning to do it in the meantime (same goes for issue #409 ). 😃

**Comment by swalladge** [comment]
Turns out that using a modified `get_username()` messes up the default admin flow for adding users... Suddenly this is higher priority. Stay tuned for a PR

**Comment by sbussetti** [comment]
@swalladge @matthiask -- sorry about that -- missed that reference in the merge.  thanks for beating me to the solve.
