### ISSUE TITLE
Removes img tags from imported posts

### ISSUE THREAD

**Issue by talaikis** [django-ckeditor/django-ckeditor#416]
I have a imported posts into database and if I load those posts on Django ckeditor textarea, img tags are removed from them. Example of code which is removed:

```text
<a href="http://www.example.com/wp-content/uploads/2015/12/flow-state.jpg"><img class="alignnone size-full wp-image-47" src="http://www.example.com/wp-content/uploads/2015/12/flow-state.jpg" alt="flow-state" width="1000" height="453" /></a>
```

**Comment by matthiask** [comment]
CKEditor cleans the HTML, I'm not sure why it happens in this case. But if a problem exists it will be a CKEditor problem, not a django-ckeditor problem.
