### ISSUE TITLE
Broken path due to unnecessary trailing slash on tableselection.css file

### ISSUE THREAD

**Issue by augustogoulart** [django-ckeditor/django-ckeditor#422]
I'm using AWS S3 to serve my static files and notice a 403 on the tableselection.css file.
I found that's due to this broken path:

![link](https://user-images.githubusercontent.com/13952931/29486580-ed07b23a-84bf-11e7-8b3c-f1a97e276125.png)

Which can be easily noticed here:

![one](https://user-images.githubusercontent.com/13952931/29486594-40b081fa-84c0-11e7-8a33-62a5af1115c5.png)

Am I missing something? Is this really a bug?

**Comment by matthiask** [comment]
This is not a django-ckeditor issue, and already fixed in CKEditor:
https://github.com/ckeditor/ckeditor-dev/commit/49fef384e4d7ac821283b59f5ddbc46b1becd11d
