### ISSUE TITLE
Git tags for every release

### ISSUE THREAD

**Issue by vstoykov** [django-ckeditor/django-ckeditor#423]
Now it's very hard to see what are the differences (commits) between versions which are uploaded to PyPi. If there where tags in GitHub for every version then it will be very helpful.

**Comment by sharifzadesina** [comment]
I think this is so important.

**Comment by ashishnitinpatil** [comment]
Any update on this?

**Comment by matthiask** [comment]
You could help by providing a copy-pastable shell script which creates those tags. Unsigned tags are OK. I'll happily run this, check everything and push the tags into this repo.

**Comment by ashishnitinpatil** [comment]
I'm on it :) I'll

- [ ] 1. check pypi history & note the commit hashes for various versions
- [ ] 2. confirm with `setup.py` & `ckeditor.__init__.py` histories
- [ ] 3. make a script to git tag versions correctly
- [ ] 4. run locally & push tags to my forked repo & verify
- [ ] 5. upload the verified script here

**Comment by ashishnitinpatil** [comment]
[django_ckeditor_version_git_hashes.txt](https://github.com/django-ckeditor/django-ckeditor/files/2798119/django_ckeditor_version_git_hashes.txt)

Got all pypi release info (exact UTC time of release publish) from the [release history page](https://pypi.org/project/django-ckeditor/#history) and then went on to check corresponding commits from [github commit history](https://github.com/django-ckeditor/django-ckeditor/commits/master) on that exact date-time & updated git hashes in this file. Most of it was straightforward, except 3-4 instances where I had to check back with pypi released readme & other details to get exact commit hash.

All of this is correct to the best of my knowledge, please feel free to cross-check & correct if needed. Will try & make a script soon.

**Comment by matthiask** [comment]
Very nice, thanks!

I changed the file to contain one line per record and ran the script generated by the following command and pushed all tags that were created, so I think we can close this issue. Thanks for your help!

`awk '{print "git tag " $1 " " $2 " -m \"django-ckeditor " $1 "\"" }' django_ckeditor_version_git_hashes.txt`

**Comment by ashishnitinpatil** [comment]
Happy to help! I was thinking we could've even [back-dated the tag](https://stackoverflow.com/a/21759466/2689986) / release dates according to my hashes file, but no issues, we've primarily solved the issue :smiley: & the resulting script would've been quite complicated & requires much more efforts too.

**Comment by ashishnitinpatil** [comment]
Okay, I've made a script to fix the dates & it seems to be [working nicely for my forked repo](https://github.com/ashishnitinpatil/django-ckeditor/releases/). PFA.
[django_ckeditor_tag_date_fix.txt](https://github.com/django-ckeditor/django-ckeditor/files/2798814/django_ckeditor_tag_date_fix.txt)

**Comment by matthiask** [comment]
Thank you, I replaced all tags using your script. It did work nicely :)
