### ISSUE TITLE
Installs are breaking (Pillow is required, but should not be)

### ISSUE THREAD

**Issue by LegoStormtroopr** [django-ckeditor/django-ckeditor#426]
Why: you probably forgot to pin your dependencies.

Looks like CKEDITOR now requires (but doesn't install) pillow, so an environment with `pip install ckeditor` isn't working like it used to.

You need to make sure you install `pillow` independently as of 5.3.0

**Comment by matthiask** [comment]
`ckeditor_uploader`  requires Pillow (and probably has for a long time?) but the `ckeditor` app should not (and does not, from my reading of the code, but maybe I missed something?)

Unfortunately there is no way to know in advance whether users want to use the `ckeditor_uploader` app. Not sure how to fix this.

**Comment by riklaunim** [comment]
My idea is to have two pypi packages - ckeditor and uploader with their dependencies (and django-ckeditor as a meta package pulling both) - then people can choose and get correct dependencies... but still Pillow is required only if you use the Pillow backend. In some edge cases (Goggle App Engine, Jython?) Pillow may not be available.

**Comment by matthiask** [comment]
But then this import shouldn't have been added:
https://github.com/django-ckeditor/django-ckeditor/commit/1305510a8a338588e82637510677191afc2b4f9f#diff-082797dc2080cfc476d0807975d1d168R19

**Comment by riklaunim** [comment]
Some refactoring needed.

**Comment by matthiask** [comment]
I think this has been fixed some time ago. An eventual `ImportError` raised by importing Pillow is silently discarded (as it probably should be).
