### ISSUE TITLE
django-ckeditor working on one computer, not working in another

### ISSUE THREAD

**Issue by gusarg81** [django-ckeditor/django-ckeditor#427]
Hi, in relaction of my other post (https://github.com/django-ckeditor/django-ckeditor/issues/425), this is a very weird problem. I have same OS, same version, same django, same django-ckeditor, etc.

Where is not working: on my PC (local development) and on my server (production)
Where is working: on my Notebook (local development).

Here you can see that all JS and CSS from ckeditor is loading (my notebook): http://imgur.com/a/0pAyO
Now, the same in my PC, you can see that is not loading all related stuff to ckeditor: http://imgur.com/a/XScLe

I load ckeditor by doing {{ form.media }} and the widget is being loaded in both cases but not working, like I said, in my PC and Server: http://imgur.com/a/rAHIj

I don't know what else to test, I don't know if in my PC and Server I've missing deps (which seems in my notebook does not)...

OS: Ubuntu 16.04
Django: 1.11.4
Django-ckeditor: 5.3.0

Any one can help me? Thanks in advance...

**Comment by riklaunim** [comment]
Does JS console has any errors? Does the static files load (or maybe they throw 404 or alike)?

**Comment by gusarg81** [comment]
Hi,

No errors on console and static files loads correctly.

**Comment by gusarg81** [comment]
Hi,

For testing, I've installed a fresh install on a VirtualBox, and is not working (as like I said, is not working on my PC and on my Production server).

I don't know if related, but outside ajax call of the form, the widget loads just fine:

Inside Ajax: https://imgur.com/a/eagCq
Outside Ajax: https://imgur.com/a/QiIEQ

Like I said in my other post, the static files are being loaded even in the ajax call, so I don't have a clue.

Now, what I don't understand why in my Notebook is working (inside or outside Ajax call), with same version of everything, which difficults me to find a solution...

**Comment by gusarg81** [comment]
Hi,

Today testing: I've harcoded adding all JS and CSS thats ckeditor loads in the form template and still does not work inside ajax:

{% load static %}

<script type="text/javascript" src='{% static "ckeditor/ckeditor-init.js" %}'></script>
<script type="text/javascript" src='{% static "ckeditor/ckeditor/ckeditor.js" %}'></script>
<script type="text/javascript" src='{% static "ckeditor/ckeditor/config.js" %}?t=H4PG'></script>
<script type="text/javascript" src='{% static "ckeditor/ckeditor/lang/es.js" %}?t=H4PG'></script>
<script type="text/javascript" src='{% static "ckeditor/ckeditor/styles.js" %}?t=H4PG'></script>

<style>.cke{visibility:hidden;}</style>
<link rel="stylesheet" type="text/css" href='{% static "ckeditor/ckeditor/skins/moono-lisa/editor.css" %}?t=H4PG'>
<link rel="stylesheet" type="text/css" href='{% static "ckeditor/ckeditor/plugins/scayt/skins/moono-lisa/scayt.css" %}'>
<link rel="stylesheet" type="text/css" href='{% static "ckeditor/ckeditor/plugins/scayt/dialogs/dialog.css" %}'>
<link rel="stylesheet" type="text/css" href='{% static "ckeditor/ckeditor/plugins/tableselection//styles/tableselection.css" %}'>
<link rel="stylesheet" type="text/css" href='{% static "ckeditor/ckeditor/plugins/wsc/skins/moono-lisa/wsc.css" %}'>
<link rel="stylesheet" type="text/css" href='{% static "ckeditor/ckeditor/plugins/copyformatting/styles/copyformatting.css" %}'>

<form id='services-form' action='' method='post' enctype='multipart/form-data'>
	{% csrf_token %}
	{{ services_form.as_p }}
	{{ services_form.errors.as_p }}
</form>

Does work outside Ajax...

Just to mention, I've tested with django-tinymce and works just fine inside ajax, outside ajax, etc.
