### ISSUE TITLE
django-ckeditor not working with Google Material Design Lite framework

### ISSUE THREAD

**Issue by wardal** [django-ckeditor/django-ckeditor#429]
Hi guys, 

I'm working in a project where I need to use ckeditor not only in django-admin, but also in forms outside django-admin. Based on Django 1.11 and django-ckeditor 5.3.0

forms.py
`from ckeditor_uploader.widgets import CKEditorUploadingWidget`
```
class PaymentForm(forms.Form):
    comments = forms.CharField(widget=CKEditorUploadingWidget())
```
settings.py
```
# Settings for CKEditor
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_RESTRICT_BY_DATE = True
```
in template used form.media to add ckeditor js:
`{{ form.media }}`

Today when I trying to integrate ckeditor to public form, I found that form charfield with ckeditor does not working at all. Something like I can't focus to this field, and when I click to any of ckeditor control elements I got errors (tried in different browsers):

In Firefox:

`TypeError: this.document.getWindow(...).$ is undefined`
```
getNative http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:445:29
	CKEDITOR.dom.selection http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:443:54
	CKEDITOR.editor.prototype.getSelection http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:440:319
	CKEDITOR.plugins.undo.Image http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:1174:458
	save http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:1169:123
	b http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:1164:291
	n http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:10:222
	CKEDITOR.event.prototype</<.fire</< http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:12:42
	CKEDITOR.editor.prototype.fire http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:13:212
	execCommand http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:271:120
	CKEDITOR.ui.button/<.click< http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:654:417
	execute http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:655:478
	render/q< http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:656:324
	addFunction/< http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:31:216
	callFunction http://127.0.0.1:8000/static/ckeditor/ckeditor/ckeditor.js:31:332
	onclick http://127.0.0.1:8000/accounts/trip/2/:1:1
```
In Opera:

`Uncaught TypeError: Cannot read property 'getSelection' of undefined`
 
```
at CKEDITOR.dom.selection.getNative (ckeditor.js:445)
    at CKEDITOR.dom.selection (ckeditor.js:443)
    at a.CKEDITOR.editor.getSelection (ckeditor.js:440)
    at CKEDITOR.plugins.undo.Image (ckeditor.js:1174)
    at CKEDITOR.plugins.undo.UndoManager.save (ckeditor.js:1169)
    at a.b (ckeditor.js:1164)
    at a.n (ckeditor.js:10)
    at a.CKEDITOR.event.CKEDITOR.event.fire (ckeditor.js:12)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)
    at a.execCommand (ckeditor.js:271)
```

ckeditor.js 445 line:
`x?this.document.$.selection:this.document.getWindow().$.getSelection()},getType:x?function(){var a=this._.cache;if(a.type)return a.type;var b=CKEDITOR.SELECTION_NONE;try{var c=this.getNative(),d=c.type;"Text"==d&&(b=CKEDITOR.SELECTION_TEXT);"Control"==d&&(b=CKEDITOR.SELECTION_ELEMENT);c.createRange().parentElement()&&(b=CKEDITOR.SELECTION_TEXT)}catch(e){}return a.type=b}:function(){var a=this._.cache;if(a.type)return a.type;var b=CKEDITOR.SELECTION_TEXT,c=this.getNative();if(!c||!c.rangeCount)b=CKEDITOR.SELECTION_NONE;`

First of all I tried to search info about this errors, but any of founded fixes doesn't worked in my situation.

Then I decide to check all my project scripts, and found conflict with https://getmdl.io/ https://github.com/google/material-design-lite Google material design lite css framework.

If we will not include material.min.js to page scripts, ckeditor working as needed. And if we will include this script - ckeditor does not work. Not minified framework js: https://code.getmdl.io/1.3.0/material.js

PS: this is my first issue ever made, sorry for any inconvenience.

**Comment by wardal** [comment]
Very nice to close the issue, when it wasn't fixed.

**Comment by matthiask** [comment]
Thanks for removing the irritating comment. It was my intention to fix this, but I didn't like the fix after all.
