### ISSUE TITLE
Code Snippet Plugin Disappears Upon Saving Text Content

### ISSUE THREAD

**Issue by artforlife** [django-ckeditor/django-ckeditor#436]
### Summary

I am not sure if this belongs here or is better suited for Aldryn NewsBlog repository. In short, placing a code snippet inside a Text content box does not work. 

I am able to place a Text box inside a `Newsblog_Article_Content` placeholder. Then, I type some text and place a CodeSnippet plugin inside the text content. The source looks like this:

```
<p>Post content here!</p>

<p>Some code here:<cms-plugin alt="Code - &lt;code&gt; " id="46" render-plugin="true" title="Code - &lt;code&gt;"><code>print(&#39;hello&#39;)</code></cms-plugin></p>
<cms-plugin alt="Code - &lt;pre&gt; " id="45" title="Code - &lt;pre&gt;"></cms-plugin>

<p>&nbsp;</p>
```
After I save the changes to the text, the code snippet is not shown. Upon opening the text area in edit mode, I see the following source:

```
<p>Post content here!</p>

<p>Some code here:<cms-plugin alt="Code - &lt;code&gt; " id="46" title="Code - &lt;code&gt;"></cms-plugin></p>

<p>&nbsp;</p>
```

* Python version: 3.5
* Django==1.10.9.dev20170906233227
* django CMS version: django-cms==3.4.5rc1

P.S. I have also experienced the same problem with Django 1.9 and a stack that seems to be deemed as "stable." I am just now reporting this because there were other more pressing issues at the time.

**Comment by matthiask** [comment]
django-ckeditor does not do any processing of HTML itself, which means that this issue should either be reported to the CKEditor developers, or probably better yet to the django CMS developers.

(
Side note 1: My personal opinion is that CKEditor isn't really a good fit if you need a richer document model. For example [ProseMirror](https://prosemirror.net/) would be a better fit for this.

Side note 2: That is the exact reason why [feincms3](https://github.com/matthiask/feincms3) and [django-content-editor](https://github.com/matthiask/django-content-editor) do not use one big rich text editor with custom elements but many small plugins to compose content.
)

**Comment by khanhney** [comment]
- 

- [ ] `1. `sadsad``
