### ISSUE TITLE
GIF thumbnail issue

### ISSUE THREAD

**Issue by tisdall** [django-ckeditor/django-ckeditor#438]
Okay...  this is a little convoluted so I'll start from the beginning...

I was using version 5.2.2 and when a user tried uploading a .gif I got the following exception (I'm just included the parts related to this lib):
```
  File "/data/virtualenv/default/lib/python2.7/site-packages/ckeditor_uploader/views.py", line 66, in post
    self._create_thumbnail_if_needed(backend, saved_path)

  File "/data/virtualenv/default/lib/python2.7/site-packages/ckeditor_uploader/views.py", line 89, in _create_thumbnail_if_needed
    backend.create_thumbnail(saved_path)

  File "/data/virtualenv/default/lib/python2.7/site-packages/ckeditor_uploader/image/pillow_backend.py", line 45, in create_thumbnail
    imagefit.save(thumbnail_io, format=file_format)

  File "/data/virtualenv/default/lib/python2.7/site-packages/PIL/Image.py", line 1826, in save
    save_handler(self, fp, filename)

  File "/data/virtualenv/default/lib/python2.7/site-packages/PIL/GifImagePlugin.py", line 458, in _save
    _write_single_frame(im, fp, palette)

  File "/data/virtualenv/default/lib/python2.7/site-packages/PIL/GifImagePlugin.py", line 378, in _write_single_frame
    _write_local_header(fp, im, (0, 0), flags)

  File "/data/virtualenv/default/lib/python2.7/site-packages/PIL/GifImagePlugin.py", line 483, in _write_local_header
    transparency = int(transparency)

TypeError: int() argument must be a string or a number, not 'tuple'
```

I checked to see if there was a new version so I thought I'd try that to see if the issue was solved.  I installed 5.3.0 and after putting in a hack to get around #411 I found that I no longer got the exception.  However, I also found that I no longer got a thumbnail, either.

It seems that #351 [added the following code](https://github.com/AliYmn/django-ckeditor/blob/master/ckeditor_uploader/views.py#L67) that stops thumbnails for GIFs:
```
        if(str(saved_path).split('.')[1].lower() != 'gif'):
            self._create_thumbnail_if_needed(backend, saved_path)
```

So, the bug wasn't fixed but a new bug stopped the old bug from happening.  Also, [as stated in #351 a different method should be used to determine the file type](https://github.com/django-ckeditor/django-ckeditor/pull/351#issuecomment-277532747).  There doesn't appear to be any explanation in #351 why thumbnails for GIF is disabled, but I suspect they ran into the same issue I did.

**Comment by tisdall** [comment]
I tried uploading a "filename.jpg.gif" file and it gets renamed to "filenamejpg.gif" so it seems using `split` is less of an issue here.  I'm still not sure why gif thumbnails have been disabled, though.

**Comment by tisdall** [comment]
I wrote more info, but apparently I forgot to hit "comment"...  :disappointed: 

I found another library that seemed to have copied the same Django snippet for making a thumbnail and fixed it by changing
```
    if image.mode not in ('L', 'RGB'):
        image = image.convert('RGB')
```
into
```
    if file_format == 'JPEG' and image.mode not in ('L', 'RGB'):
        image = image.convert('RGB')
```

That seemed to work, but it seems like it's just bypassing the issue.  

Here's the issue I found with the same stacktrace:  https://github.com/wagtail/Willow/issues/16  And here's the patch they did:  https://github.com/sehmaschine/django-filebrowser/commit/b5923202758b69a9102b7453788d4362481faf40

**Comment by riklaunim** [comment]
Pillow may be missing a library for handling GIFs. Whatever the reason thumbnailing should be handled correctly. I wonder if TIFF can also get into problems.

**Comment by tisdall** [comment]
Unfortunately that Django snippet is 10 years old and seems to be fixing some issue with an ancient copy of PIL that I suspect is no longer an issue if using a recent Pillow copy (this is why comments are important!).  [Someone mentioned that the only remaining issue is with JPEG in "P" mode](https://github.com/sehmaschine/django-filebrowser/pull/274#commitcomment-14161285).  I tried the image provided on that PR and it thumbnailed fine without converting to RGB.  It seems that the resize is able to work in most cases without converting the colour scheme (provided you're using a recent Pillow version).  If the colour scheme is left, then GIF and PNG with transparencies don't have that transparency turned to black.

The image below caused the exception.  Please test it out on your own system to confirm it's not an issue with only my Pillow install (you'll have to comment out that `if` statement that's preventing GIF thumbnails from being generated, though).  I tried with Pillow 4.1.1 and the latest version (same result) and on different machines.

I'm going to test a little more, but I'm pretty sure the issue is with Pillow and the only change needed here is the removal of that if statement preventing GIF thumbnailing.

![plus](https://user-images.githubusercontent.com/4029388/31665888-5b0a1314-b318-11e7-8e39-f4ea94ff6b11.gif)

**Comment by tisdall** [comment]
Filed the bug with Pillow here:  https://github.com/python-pillow/Pillow/issues/2803

The issue here is really that GIF thumbnailing has been disabled.  (sorry for confusing the issue)
