### ISSUE TITLE
Doubt about Licence

### ISSUE THREAD

**Issue by bauripalash** [django-ckeditor/django-ckeditor#439]
I want to use django-ckeditor in one of my commercial project. But django-ckeditor is BSD-3 Clause Licensed but CKeditor official website says I've to buy a license to use CKeditor in commercial projects.
Now, can anyone help me?

**Comment by riklaunim** [comment]
django-ckeditor isn't ckeditor itself (although the package contains it for convenience). Also CKEditor Premium is bit more than CKEditor itself - are you sure you "need" that option? GPL/LGPL/MPL licenses for CKEditor are quite permissive for commercial projects.

**Comment by matthiask** [comment]
As always you should consult a lawyer, but in this case I can give some advice as well. 

You should be fine under the LGPL as long as you're not modifying the CKEditor source itself. According to my reading of https://en.wikipedia.org/wiki/Mozilla_Public_License the MPL is perfectly fine for commercial projects as well.
