### ISSUE TITLE
Getting a 404 for static files.

### ISSUE THREAD

**Issue by YujinYuz** [django-ckeditor/django-ckeditor#441]
Hi. I'm using S3 and I'm getting this error:

> GET https://jinyuz-blog-static.s3.amazonaws.com/static/ckeditor/ckeditor/plugins/tableselection//styles/tableselection.css net::ERR_ABORTED

It seems that it's appending double slash `//` after tableselection.

In my `admin/base_site.html`

I did:

`<script>window.CKEDITOR_BASEPATH = "{% static 'ckeditor/ckeditor/' %}";</script>`

Because using the hard coded version
`<script>window.CKEDITOR_BASEPATH = "/static/ckeditor/ckedito/r";</script>`

does not seem to work for me.. It's pointing to

`http://jinyuz-blog.herokuapp.com/static/ckeditor/ckeditor/`

**Comment by riklaunim** [comment]
if it's within plugin path of the url it's rather not a part of the ckeditor base path. Maybe "tableselection" has a custom path/url hardcoded that causes such problem?

**Comment by matthiask** [comment]
Thanks. Duplicate of #422.

**Comment by YujinYuz** [comment]
@matthiask I see that it was fixed but I don't see anything that can help me resolve my issue

**Comment by riklaunim** [comment]
I should put out a new version of the package with newer ckeditor.

**Comment by riklaunim** [comment]
and done.

**Comment by YujinYuz** [comment]
@riklaunim so I just have to wait for a new version?

**Comment by riklaunim** [comment]
5.3.1 is already out and it has a newer CKEditor version. Check it out.

**Comment by YujinYuz** [comment]
@riklaunim Thanks! I thought it wasn't released yet because it has `(Upcoming)` in the release notes
