### ISSUE TITLE
RESTRICT_BY_USER is broken in 5.3.0

### ISSUE THREAD

**Issue by crucialfelix** [django-ckeditor/django-ckeditor#443]
TypeError at /ckeditor/upload/
getattr(): attribute name must be string

[site-packages/ckeditor_uploader/views.py in get_upload_filename, line 28
](https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/views.py#L28)--

5.3.0 looks like this:

```
        try:
            user_prop = getattr(user, RESTRICT_BY_USER)
        except AttributeError:
            user_prop = getattr(user, 'get_username')
```

which throws an uncaught TypeError

It looks like it is fixed in master but the released version doesn't include this.

django-ckeditor==5.3.0

**Comment by riklaunim** [comment]
https://pypi.python.org/pypi/django-ckeditor/5.3.1 is available

**Comment by crucialfelix** [comment]
Oh good. Sorry I missed noticing that.
