### ISSUE TITLE
Add default class to Images

### ISSUE THREAD

**Issue by elmcrest** [django-ckeditor/django-ckeditor#446]
Hey everybody,

I try to apply a default class (using Bootstrap 4 btw) to all used/uploaded Images. the classname is `img-fluid`.
Maybe it would make sense to prevent the inline height and width settings for Images too, but that's not really an issue.

What I've tried in `CKEDITOR_CONFIGS` is the following:

```
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            # ...
        ],
        'toolbar': 'YourCustomToolbarConfig',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', 
            # ...
        ]),
        'stylesSet': [
            {
                'name': 'Image-Fluid',
                'element': 'Image',
                'attributes': {'class': 'img-fluid'},
            },
        ],
        'contentsCss': 'p img {width:100%;}',
    }
}
```
 
So neither `stylesSet` nor `contentsCss` has any effect for me.

Thx for any hints and comments :P

**Comment by elmcrest** [comment]
meanwhile I've found this:

https://ckeditor.com/old/forums/Support/Adding-class-attribute-default-images

which proposes to add a callback to the editors JS instance:

``` Javascript
editor.on('insertElement', function(event) {
	var element = event.data;
	if (element.getName() == 'img') {
		element.addClass('contentimage');
	}
});
```

In case that's the only possible way, how would I extend/modify django-ckeditor ideally?

**Comment by Senpos** [comment]
Is there any suggestions on this?
I Google'd and tried this:
```
   'stylesSet': [
            {
                "name": 'Image',
                "element": 'img',
                "attributes": {'class': 'my_custom_class'},
            },
        ],
```

But it doesn't work. 

Is there a proper way of doing this not in JS, but Python?

**Comment by riklaunim** [comment]
In Python you could use for example Beautifulsoup to go through every img and check/add a class.

**Comment by Senpos** [comment]
@riklaunim nah, that's not solution. 

Probably, will play around styling without adding the class, but thats annoying

**Comment by juncheong** [comment]
Has a solution to this issue been found by anyone or implemented by the contributors?

**Comment by MrAlexWinkler** [comment]
Also curious what the final solution was

**Comment by cellmon** [comment]
whery need solution! js or Setting - nobody nowork///

**Comment by juliendland** [comment]
I tried to change styleset, chang ckeditor config.js or ckeditor JS instance and nothing work. Does anyone have a solution to this problem? thx

**Comment by matthiask** [comment]
The solution by riklaunim is the correct one even if some people do not like it. HTML should always be [sanitized](https://pypi.org/project/html-sanitizer/)/processed in the backend anyway. I'd recommend adding a wrapper and styling e.g. `.richtext img` anyway.
