### ISSUE TITLE
How to configure absolute url for uploaded images

### ISSUE THREAD

**Issue by qiyiping** [django-ckeditor/django-ckeditor#448]
Hi,

I uploaded an image and get a relative path like this:
`<img` alt="" src="/media/creatives/2017/11/20/ypovyh.jpeg" style="height:121px; width:121px" `/>`

Is there any way to configure absolute url for uploaded images?

Thanks

**Comment by riklaunim** [comment]
MEDIA_URL is used for this.

**Comment by qiyiping** [comment]
Thanks for the reply. It helps a lot.
