### ISSUE TITLE
Exception Type:	NoReverseMatch

### ISSUE THREAD

**Issue by JiamingWu233** [django-ckeditor/django-ckeditor#456]
Exception Type: | NoReverseMatch
-- | --
Reverse for 'ckeditor_upload' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

how to resolve this problem?

**Comment by riklaunim** [comment]
did you add ckeditor urls.py include to yours urls.py?

**Comment by JiamingWu233** [comment]
@riklaunim sorrry,i no run the collectstatic management command: $ ./manage.py collectstatic
