### ISSUE TITLE
Does Syntax Highlighter plugin really highlights the code ?

### ISSUE THREAD

**Issue by javadmokhtari** [django-ckeditor/django-ckeditor#459]
Hello my friends and thanks a lot for your beautiful editor. I use the configs in the bellow issue:
https://github.com/django-ckeditor/django-ckeditor/issues/220

it works fine and I have code snippet in my editor. but when I insert a code and select the language it really does not colorize the code. it just shows the code as it is. is it OK ? or something went wrong ? what should I do to have my codes colorized ? 
------EDIT------
Of course it highlights my code truly in editor, but when I show it in a template using django, it only shows the pure code not colorized.
thank you.

**Comment by matthiask** [comment]
Use something else for highlighting code in the frontend, for example PrismJS (I'm not affiliated): http://prismjs.com/

Also, this is really a CKEditor question, not a django-ckeditor question.
