### ISSUE TITLE
upload image problem

### ISSUE THREAD

**Issue by Kaming** [django-ckeditor/django-ckeditor#461]
After I upload the image, preview out the image 404;
![image](https://user-images.githubusercontent.com/9999264/34599035-640ba1b0-f22b-11e7-8855-2d15b8fbc16d.png)
![image](https://user-images.githubusercontent.com/9999264/34599057-7391aef4-f22b-11e7-9992-e7db7443b37b.png)
![image](https://user-images.githubusercontent.com/9999264/34599023-58e264a4-f22b-11e7-9070-d288774efc2a.png)
setting.py:
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CKEDITOR_UPLOAD_PATH = "uploads/"
How can I solve?

**Comment by riklaunim** [comment]
are you media files handled correctly in urls.py?
