### ISSUE TITLE
a.ui.space is null due to eagerly initialising of CKEditor (reopen #345)

### ISSUE THREAD

**Issue by n3storm** [django-ckeditor/django-ckeditor#466]
We experienced failures with CKEditor if the page takes longer to load.
The error reads a.ui.space being null.

A workaround was to initialise CKEditor on $(window).on('load', initialiseCKEditor). Especially the replace call happened too early. But proper implementation is not clear.

Started at #345 

(Note: sorry if this is not the proper way to reopen an eagerly closed issue)
(Note 2: sorry for the pun)

**Comment by matthiask** [comment]
Maybe we'd have more luck with https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_editor.html#instanceReady or https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_editor.html#loaded
