### ISSUE TITLE
Can you fix this bug? Bad url for filebrowser browse.html

### ISSUE THREAD

**Issue by xros** [django-ckeditor/django-ckeditor#467]
Tested 
Django 1.11
django-ckeditor 5.4.0

Use his [solution](https://github.com/darklow/django-suit-ckeditor/issues/11) to download the browse.html template to make it work. it has been out for years.. 
Thanks

**Comment by riklaunim** [comment]
The template should be in the package.

**Comment by msaizar** [comment]
The template is in the ckeditor_uploader application. Make sure you include it in your INSTALLED_APPS.
