### ISSUE TITLE
Misleading error: ImproperlyConfigured: django-ckeditor requires CKEDITOR_MEDIA_PREFIX setting

### ISSUE THREAD

**Issue by crucialfelix** [django-ckeditor/django-ckeditor#468]
In widgets.py there is a try block where any AttributeError that happens inside of that results in this error:

https://github.com/django-ckeditor/django-ckeditor/blob/17d89a2ef7efdf91fb266ed84031f6cf2693b07e/ckeditor/widgets.py#L61-L78

CKEDITOR_BASEPATH is what is being checked, but with a getattr and a default. CKEDITOR_MEDIA_PREFIX is not being checked at all.

In my case CKEDITOR_MEDIA_PREFIX and CKEDITOR_BASEPATH are set and I still have no idea what is wrong.

It must be something inside js_assets.

I don't think you need that try block at all. The setting that is being checked already has a default. The error message is probably left over from a previous implementation.

**Comment by matthiask** [comment]
Do you have additional details about the `AttributeError` you're getting?

And yes, the error message is completely out of date, I missed that when changing the block above .-(

**Comment by crucialfelix** [comment]
It had something to do with a different setting related to staticfiles. So the original error should have been allowed to propagate. Then I could have solved it faster.

Personally I think python programmers misuse attribute error most of the time. We all do it. Better to check with hasatttr in the object you are using.

Thanks for fixing this !
