### ISSUE TITLE
How to store uploaded images outside the default Media URL

### ISSUE THREAD

**Issue by pckapps** [django-ckeditor/django-ckeditor#471]
I'm using S3 to save my media files and it is currently set up for private access. When rendering the template I generate a signed url that's valid for 1 hour.

This approach doesn't work when uploading images through the editor since the url must be static.

Is it possible to upload images to something other than the default media path? Ideally I would like to setup a different bucket to store the images.

**Comment by riklaunim** [comment]
there is a pull request for setting up different django file storage for files uploaded via the ckeditor file uploader. That should help.

**Comment by riklaunim** [comment]
Feature merged and released.
