### ISSUE TITLE
Can't make work ckeditor widgets plugins

### ISSUE THREAD

**Issue by antoinefavre** [django-ckeditor/django-ckeditor#475]
Hello, 

I'm having an issue with this package : I'm trying to create a ckeditor widget to add to the toolbars, I followed [this official tutorial] (https://docs.ckeditor.com/ckeditor4/latest/guide/widget_sdk_tutorial_1.html ) and it does not seem to work, even if I take the exact same code for the widget as in the tutorial. No new icon is getting added on the toolbar.
Here is the way I added the widget, in the "plugins" folder : 
![capture d ecran 2018-03-14 a 11 16 39](https://user-images.githubusercontent.com/14332344/37396465-3fdcb9ae-2779-11e8-8f49-c5949370abfd.png)
Here is my django config : 
![capture d ecran 2018-03-14 a 11 11 46](https://user-images.githubusercontent.com/14332344/37396222-8fc2f114-2778-11e8-8581-ec29ec58b13c.png)
As you can see, I loaded the "widget" plugin as it is specified as a requirement, and then I loaded my custom plugin "simplebar", which is present in my first toolbar.

It's probably only a configuration issue that I forgot/did wrong, or It might be a bug, I really don't know, anyway, I would really appreciate getting some help to try resolve it ! Thanks guys !

**Comment by rustedwolf** [comment]
I have the same issue. Some feedback or at least workaround would be nice.

**Comment by rustedwolf** [comment]
I found the cause of the problem. It's caused by custom toolbar definition:
https://dev.ckeditor.com/ticket/12576
In order to use a widget in the custom toolbar, you need to enter title-cased plugin name, like so:
`'toolbar': [[... 'Simplebox']],`
