### ISSUE TITLE
How to start uploader?

### ISSUE THREAD

**Issue by xiaohuanlin** [django-ckeditor/django-ckeditor#477]
I follwed the steps as document, but I even can't see an "upload" button. How should I do next?
![image](https://user-images.githubusercontent.com/33860497/37561919-58f97448-2a96-11e8-87ad-1ee556c11c8d.png)

**Comment by xiaohuanlin** [comment]
I know why I can't see it, because I used RichTextField instand of the RichTextUploadField.
But I have another question when I post an image, just like this.
![image](https://user-images.githubusercontent.com/33860497/37564166-4952c5f0-2acb-11e8-901b-3e33af7dce4e.png)
please tell me how to fix it.

**Comment by matthiask** [comment]
You should probably remove `CKEDITOR_FILENAME_GENERATOR` from your settings.

**Comment by xiaohuanlin** [comment]
Thank you, but I still have this problem even remove `CKEDITOR_FILENAME_GENERATOR`.
Finally, I choose to remove the statement in `ckeditor_uploader`-`views`-`get_upload_filename`, just like the last block that I marked.
![image](https://user-images.githubusercontent.com/33860497/37637870-041ecd28-2c45-11e8-96da-650ae26aeaca.png)
Now, It works perfectly. However, I still want to know how should I do if I want to use the function of Filename generator?
