### ISSUE TITLE
ckeditor_uploader/browse.html not found

### ISSUE THREAD

**Issue by Rekoc** [django-ckeditor/django-ckeditor#480]
The issue come from: 
_def browse(request)_ in _ckeditor_uploader/views.py_ 
When I tried to use ckeditor_uploader, the view isn't able to find the file _browse.html_ when I was trying to upload an image on my server. To fix it, I modified the render, like so: 
before --> return render(request, 'ckeditor_uploader/browse.html', context)
my fix --> return render(request, 'ckeditor/browse.html', context)

In fact, in _ckeditor/templates/_ & _ckeditor_uploader/templates/_ both have subdirectory called _ckeditor_ and we tried to call _'ckeditor_uploader/browse.html'_ instead of _'ckeditor/browse.html'_.

Maybe this is due to an incorrect configuration on my project ? Because, I'm not the first guys who tried to use the uploader, isn't it ? I found this topic, it seems to be the same issue than #467 

Thanks anyway for this great framework you have made :) !

**Comment by matthiask** [comment]
From https://github.com/django-ckeditor/django-ckeditor/issues/467#issuecomment-369119554:

> The template is in the ckeditor_uploader application. Make sure you include it in your INSTALLED_APPS.

Did you do this?

**Comment by Rekoc** [comment]
Yes I did.

> INSTALLED_APPS = [
>     'django.contrib.admin',
>     'django.contrib.auth',
>     'django.contrib.contenttypes',
>     'django.contrib.sessions',
>     'django.contrib.messages',
>     'django.contrib.staticfiles',
>     'blog',
>     'ckeditor',
>     'ckeditor_uploader',
> ]

**Comment by riklaunim** [comment]
Is it still a problem?
