### ISSUE TITLE
Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by DevQiao** [django-ckeditor/django-ckeditor#484]
when run the demo app, I got an error that " Uncaught TypeError: Cannot read property 'left' of undefined, ckeditor.js:944"

**Comment by bing13** [comment]
i had the same error.  after running collectstatic with the "-c" option the error resolved. i believe i had some files from a previous version laying about, but i didn't try to run it to ground. 

https://docs.djangoproject.com/en/2.0/ref/contrib/staticfiles/#cmdoption-collectstatic-clear
