### ISSUE TITLE
ACF not removing script tag

### ISSUE THREAD

**Issue by lijoev** [django-ckeditor/django-ckeditor#487]
I am using django-ckeditor 5.4.0 in my application. i enabled content filter for removing script tag in my config.js file. Below is my config.js file content

`/**
 * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	// config.language = 'fr';
	// config.uiColor = '#AADC6E';
	config.disallowedContent = 'script';
};
`
the problem is that if i add the script tag at the bottom of the html field it will filter out the script tag and is working fine but if add script tag at the top it is not removing. Please help me to fix this issue

**Comment by matthiask** [comment]
Hi,

That's really a CKEditor-specific question so you should better ask it ina CKEditor forum, not in a django-ckeditor forum. Thanks.

(Also, you should filter HTML in the backend too and never only rely on JS filtering.)
