### ISSUE TITLE
reverse match not found !

### ISSUE THREAD

**Issue by 3ripleM** [django-ckeditor/django-ckeditor#492]
Hi 
I did configs on settings.py and add 

```
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow" 
```
And Add install Apps too 

At models.py i imported `from ckeditor_uploader.fields import RichTextUploadingField`
and then in admin page when I want to add content I get an error 

Reverse for 'ckeditor_upload' not found. 'ckeditor_upload' is not a valid view function or pattern name.

when i am using RichTextFiels method there isnt error but in uploading there is a problem 

where i am doing wrong?

**Comment by riklaunim** [comment]
Did you added needed apps to INSTALLED_APPS as well as urls in urls.py?

**Comment by 3ripleM** [comment]
Yes i did both

**Comment by riklaunim** [comment]
The error looks like ckeditor_uploader is not in installed apps or views not connected to routing.

**Comment by 3ripleM** [comment]
its ok now it seems it wasn't in view thanks

**Comment by DanielNgumo** [comment]
Thank you for the answer, I appreaciate
