### ISSUE TITLE
No ckeditor_uploader browse view results when using google cloud storage

### ISSUE THREAD

**Issue by db654** [django-ckeditor/django-ckeditor#493]
Not sure if this should be possible or not but using google cloud storage, uploading works perfectly but the browse view returns nothing. Briefly experimented with bucket permissions to no avail. Any idea if this should be expected to work or is GCS simply incompatible with that feature? Since S3 is mentioned explicitly in the docs, is this known to work with that?

**Comment by riklaunim** [comment]
Everything is done via django storage system. Are URLs generated correctly? try opening one directly - is it a 404 or something else?

**Comment by db654** [comment]
Thanks for the
