### ISSUE TITLE
How to do configuration

### ISSUE THREAD

**Issue by caliph007** [django-ckeditor/django-ckeditor#494]
I find it very hard to understand the unique way of configuring ckeditor with the provided example.

i.e. I use the out-of box configuration. i.e. no CKEDITOR_CONFIGS in settings.py

a) How can I modify this default config?

Maybe a simpel example: I need to add BulletedList to the toolbar.

How can I use CKEDITOR_CONFIGS to add this to the default config?

Any help is appreciated.
Stefan

**Comment by riklaunim** [comment]
The configuration in django settings file is then used to generate ckeditor configration.

**Comment by riklaunim** [comment]
You can also check https://github.com/django-ckeditor/django-ckeditor#example-ckeditor-configuration and if you are using something custom then it's up to to to make it working.
