### ISSUE TITLE
ModuleNotFoundError: No module named 'ckeditor_uploaderusers'

### ISSUE THREAD

**Issue by EruDev** [django-ckeditor/django-ckeditor#495]
`INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'ckeditor', 
    'ckeditor_uploader' 
]`
urls
`urlpatterns = [
    url(r'', include('users.urls')),
    url(r'', include('verifications.urls')),
    url(r'', include('areas.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]`

**Comment by riklaunim** [comment]
looks like you are missing a coma on one of lists, likely in the installed apps list

**Comment by EruDev** [comment]
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'ckeditor', # 富文本编辑器
    # 'ckeditor_uploader' # 富文本编辑器上传图片模块
    # 'django-crontab', # 定时任务
    'users.apps.UsersConfig',
    'verifications.apps.VerificationsConfig',
    'oauth.apps.OauthConfig',
    'areas.apps.AreasConfig',
    'goods.apps.GoodsConfig',
    'contents.apps.ContentsConfig'
]
I configured it under win10，is it the operating system?

**Comment by merwok** [comment]
This line is missing a comma at the end:
```
    'ckeditor_uploader' 
```
