### ISSUE TITLE
Ck editor text area not allowing contents after & sign 

### ISSUE THREAD

**Issue by lijoev** [django-ckeditor/django-ckeditor#496]
I have integrated Django-ckeditor in my application and when i enter the text which contains & sign, all the text and sentences after & sign is removed when saving the content. Please see the image below

![ckeditor](https://user-images.githubusercontent.com/19813885/42074304-189010c6-7b89-11e8-9199-cf272d460e3b.png)

Please note that the content after & sign got removed when saved. please see the image below

![save](https://user-images.githubusercontent.com/19813885/42074353-72b5a9ee-7b89-11e8-8405-8087d8abe627.png)

I haven't done any server side script to remove that sign. still it got removed. 
Please help me to fix this issue. 
I am using django-ckeditor==5.4.0

**Comment by matthiask** [comment]
Maybe you found a real issue, but if that's the case then this is a bug in CKEditor proper, not in django-ckeditor. You should report this in their issue tracker. Thanks!
