### ISSUE TITLE
State the Django minimum supported version in the Readme

### ISSUE THREAD

**Issue by boulayb** [django-ckeditor/django-ckeditor#501]
It took me quite some times to understand why it wasn't working on my project running Django 1.8 only to later find on pypi.org that the minimum supported version since 5.6.0 is Django 1.11 LTS, it would be nice to have it in the Readme so that it is easily found.

Nevertheless, awesome package, thank you!

**Comment by riklaunim** [comment]
Yep, I've dropped it in the changelog but not in other places.

**Comment by arielpontes** [comment]
Where in the Changelog? I only see Django being mentioned when support is added for a new version. It is nowhere clear what the MINIMUM supported version of Django is for any given version of `django-ckeditor`. I am trying to upgrade from Django 1.9 and it seems there is no version of ckeditor which is compatible both with Django 1.9 and 1.10, for example.

**Comment by matthiask** [comment]
I think that we can close this issue for now.

Here's the current changelog btw. https://github.com/django-ckeditor/django-ckeditor/blob/master/CHANGELOG.rst
