### ISSUE TITLE
Setting the width of the widget using relative widths does not work.

### ISSUE THREAD

**Issue by brechtdonckels** [django-ckeditor/django-ckeditor#504]
After setting the width to '100%' (or any relative width) in CKEDITOR_CONFIGS, the widget does not look as expected. It does seem to work with absolute widths (e.g., '500px'), but not for relative widths. 

Temporarily solved this by defining the width of the django-ckeditor-widget class in my css stylesheet, but I assume there must be a better way. 

`.django-ckeditor-widget {
    width: 100%;
}`

**Comment by vzagorovskiy** [comment]
please read PR #502
