### ISSUE TITLE
Image Source Url is missing

### ISSUE THREAD

**Issue by uditvashisht** [django-ckeditor/django-ckeditor#505]
I am trying to upload an image in Ckeditor_demo app through admin. And I am getting this error. 

![screenshot 2018-08-17 at 6 17 50 pm](https://user-images.githubusercontent.com/34136134/44291082-25c8db00-a24a-11e8-90c1-e5057720e6b1.png)

**Comment by pupattan** [comment]
i am also seeing the same issue

**Comment by basamrajesh** [comment]
I'm also facing the same issue

**Comment by dengwen168** [comment]
I'm also facing the same issue

How to solve it?

**Comment by nottherealironman** [comment]
Apparently, you need to click **Send it to the server** button just below it before clicking OK according to this [Stackoverflow](https://stackoverflow.com/questions/57032762/how-to-fix-image-source-url-is-missing-issue-when-using-django-ckeditor) thread

**Comment by tkwebdesigner** [comment]
I am facing also this issue in ckeditor

![Image](https://github.com/user-attachments/assets/9d41401b-aa99-4f25-ac63-64a0e1645942)
