### ISSUE TITLE
Plans about CKEDITOR5

### ISSUE THREAD

**Issue by benzkji** [django-ckeditor/django-ckeditor#508]
I really dig the new ckeditor, as seen here: https://ckeditor.com/ckeditor-5/#classic

But this is a completely new library to include, and will probably break all current configurations and also all custom plugins. Anyway, the question: Are there any plans implementing it, maybe even deprecating ck4 some day?

**Comment by matthiask** [comment]
Has already been asked once, and I'm afraid the answer / state of things didn't change: https://github.com/django-ckeditor/django-ckeditor/issues/482
