### ISSUE TITLE
CKEditor allows script tags (code injection)

### ISSUE THREAD

**Issue by cheryllium** [django-ckeditor/django-ckeditor#510]
I am using a fresh install of CKEditor on Django 2.1 and python 3. I'm using it with django-machina, but I don't think that should matter.

To clarify here is exactly what I did:
- pip install'd django-ckeditor
- followed the instructions on this page exactly to edit settings.py: https://django-machina.readthedocs.io/en/stable/customization/recipes/using_another_markup_language.html 

When I tested it out, it allowed me to write Javascript in a forum post by switching to "Source" mode and submitting. The Javascript runs in the post.

I tried to change this by adding the following to `settings.py`: 

```
CKEDITOR_CONFIGS = {
    'default': {
        "removePlugins": "stylesheetparser",
        "allowedContent": False,
    }
};
```

The javascript still ran in the post. I don't know how to disable this. (Is there a way?)

From issue #245 I infer that this is not intended behavior (That issue makes it sound like CKEditor has HTML cleaning by default and thus shouldn't be allowing script tags on a fresh install) If this has actually been changed intentionally, I'd like to argue that this is a security risk and should be changed back to filter it by default. 

Thank you and please let me know if you need more information.

**Comment by matthiask** [comment]
Well you should sanitize HTML anyway on the server side. People will submit what they want (maybe by deactivating the rich text editor themselves and submitting raw HTML) and if you show it back to people unsanitized you have a wide open door for XSS attacks.

I've heard good things about https://github.com/mozilla/bleach , but if you prefer something a bit more opinionated have a look at my sanitizer here: https://github.com/matthiask/html-sanitizer

**Comment by jitendraSumanDeloitte** [comment]
sdada@21313123dsdssdsddsfs
