### ISSUE TITLE
ckeditor_upload error

### ISSUE THREAD

**Issue by HDilshodbek** [django-ckeditor/django-ckeditor#511]
Reverse for 'ckeditor_upload' not found. 'ckeditor_upload' is not a valid view function or pattern name.
I had an error like this can anybody help me with this error

**Comment by forgive38** [comment]
ckeditor_uploader in place of ckeditor_upload ?

**Comment by hakanergul** [comment]
Your urls.py file must be properly configured. login_required decorator #ghj#

**Comment by hakanergul** [comment]
please share your `urls.py` file. For example I customize my `urls.py` for `login_required` decorator.

**Comment by kasaiee** [comment]
I found the problem. **I SHOULD INCLUDE URLS IN MAIN urls.py IN THE PROJECT NOT IN ANOTHER URLS EXISTS IN INCLUDED APPS**

**Comment by pranjal0819** [comment]
I found the same problem. and it is solved by using re_path in url.py 
django==2.1.4

url.py
```python
from django.urls import path, include, re_path
urlpatterns = [
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
```

**Comment by pranjal0819** [comment]
I found the same problem. and it is solved by using re_path in main urls.py 
django==2.1.4

urls.py
```python
from django.urls import path, include, re_path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
```

**Comment by EliasOPrado** [comment]
Thank you @pranjal0819 it solved my problem.

**Comment by RafaFurla** [comment]
Follow the same logic as @pranjal0819, the other solution is just include:
`path('ckeditor/', include('ckeditor_uploader.urls')),` 
inside the urlpatters[], instead adding the re_path method.
