### ISSUE TITLE
Ошибка при подключении в ckeditor.js

### ISSUE THREAD

**Issue by coolfire79** [django-ckeditor/django-ckeditor#512]
При вычислении пути
                -1 == b.indexOf(":/") && "//" != b.slice(0, 2) && (b = 0 === b.indexOf("/") ? location.href.match(/^.*?:\/\/[^\/]*/)[0] + b + '/' : location.href.match(/^[^\?]*\/(?:)/)[0] + b + '/');

пришлось добавить + '/'.

**Comment by matthiask** [comment]
Maybe that's also been fixed by https://github.com/django-ckeditor/django-ckeditor/commit/a07db2a97d12cb038d6b80d59fb987171f58aa90
