### ISSUE TITLE
Django Ckeditor form not showing saved content

### ISSUE THREAD

**Issue by lijoev** [django-ckeditor/django-ckeditor#514]
Hi i am using django ckeditor in my application i have a form to edit the saved content. but not showing the content inside the box when i try to edit the content. please see the image below.
![ckeditor](https://user-images.githubusercontent.com/19813885/46244314-a60e5e80-c3fa-11e8-98f5-19cdc0b3d852.png)
i use below  tags to show the ckeditor. it shows the editor without saved data.
{{ form.media }}
{{ form.description }}
data instance is passed from view. all other fields are working fine but ckeditor fields not working. 
`spattern_instance = Spattern.objects.get(id=kwargs['pk'])
spattern_form = SpatternForm(request.POST or None, instance=spattern_instance)`

please help me to figure out this issue

**Comment by luis92arma** [comment]
I think you need init your form
```python
init_update = {'name_field_form': field_model}
form = SpatternForm(instance=spattern_instance, initial=init_update)
```
