### ISSUE TITLE
Change bodyClass

### ISSUE THREAD

**Issue by bkawakami** [django-ckeditor/django-ckeditor#517]
How can I change the bodyClass to `document-editor`?

![editor2](https://user-images.githubusercontent.com/1881935/47334326-e0b39180-d65c-11e8-9320-dacb03ea12e4.png)

**Comment by matthiask** [comment]
Try adding something like
```
CKEDITOR_CONFIGS = {
"default": {
...
"bodyClass": "document-editor",
},
}
```

More: https://github.com/django-ckeditor/django-ckeditor/blob/master/README.rst#optional-customizing-ckeditor-editor
