### ISSUE TITLE
truncateword templatetag and html tag

### ISSUE THREAD

**Issue by pgdju** [django-ckeditor/django-ckeditor#520]
Hi, 
I'am using django-ckeditor to write html formated  richtext.
The problem is if I use the truncateword django templatetag associated with safe templatetag in my template,  the <s> html tag could be opened but not closed. So in consequence the rest of the text after is with a strikethrough although.
Any idea?
Thank's

**Comment by matthiask** [comment]
Use `|truncatewords_html` instead.
