### ISSUE TITLE
script tag with django-js-assets causing problems

### ISSUE THREAD

**Issue by TZanke** [django-ckeditor/django-ckeditor#521]
Hello,

we upgraded django-ckeditor to a newer version. This version uses django-js-assets, causing problems in js/css path handling.

https://github.com/matthiask/django-js-asset/blob/master/js_asset/js.py#L60

this replaces the url with a kind of html

`static/js/some.js`
is converted to
`static/js/some.js" id="abv" data-example="something`
watch out for the quoting marks

Our problem: absolute_path() normally returns a url, so we can append a timestamp `?v=123456798` for cache optimization. Now we add the timestamp incorrectly to the end of `data-example`.

I dont know the reason for using django-js-assets / adding things to script tag, but in my oppinion, this is not a very good solution at the moment

**Comment by matthiask** [comment]
What solution do you use for appending the timestamp? Is there a reason you're not using Django's ManifestStaticFilesStorage for this?

**Comment by TZanke** [comment]
We implemented our own solution years ago for Django 1.2 our something like that. But you are right, Django 1.7 [1] adds the ManifestStaticFilesStorage. A year ago i started a test, migrating to ManifestStaticFilesStorage, but we had a lot of problems with urls not being detected and now missing a md5sum. I had to derive the ManifestStaticFilesStorage class to fix the detection engine. Cause of this trouble we decided to not deploy a ManifestStaticFilesStorage solution to production systems.

Maybe we should give it a try with a newer Django versions sometime. At the moment i changed our timestamp engine to deal with the html returned in url.

Besides migration to ManifestStaticFilesStorage, it feels wrong implementing parts of html in absolute_path(). 

Maybe it would be a better solution adding the html later, like ManifestStaticFilesStorage replaces strings in rendered html, not manipulating absolute_path() methods

Or maybe the additional html attributes are only needed if unsing multiple instances of ckeditor in one single page? We do not need that, the django-js-assets could be turned off in this case.

[1] https://docs.djangoproject.com/en/2.1/releases/1.7/

**Comment by matthiask** [comment]
Oh, I agree completely that django-js-asset is an ugly hack. But it's also an ugly hack with [reasons](https://406.ch/writing/django-admin-apps-and-content-security-policy-compliance/), a relatively wide deployment these days and with only one bug report in 18 months.

I'm certainly open to different ways of providing the CKEditor basepath to the JavaScript env if it means less maintenance and less hackiness down the road. (It does not have anything to do with providing more than one CKEditor instance per page -- that's a different concern.)

**Comment by matthiask** [comment]
One more thing that comes to mind: django-js-asset uses Django's `static()` function to determine the location of assets. This function in turn uses the static files storage -- so if you'd append the timestamp (`?v=...`) inside the storage class itself everything should just work and you'd be using the "official" way to determine and manipulate the locations of static assets.

**Comment by TZanke** [comment]
In the last weeks i finally recreated our static file handling with a working custom Django ManifestStaticFilesStorage. It went live in production yesterday. Right now no problems, and it fixed a lot more then we expected in comparison to our own solution.

So thanks for your help and pointing us to ManifestStaticFilesStorage.
