### ISSUE TITLE
LookupError: unknown encoding: 874

### ISSUE THREAD

**Issue by yanadhorn** [django-ckeditor/django-ckeditor#522]
pip install django-ckeditor
Collecting django-ckeditor
  Downloading https://files.pythonhosted.org/packages/a5/a7/9a6f039f950cb148bb60d9223bcafe31329b3c85dc9a3d9b74182649c343/django-ckeditor-5.6.1.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 4.2MB/s
    Complete output from command python setup.py egg_info:
    Fatal Python error: init_sys_streams: can't initialize sys standard streams
    LookupError: unknown encoding: 874

    Current thread 0x000049b0 (most recent call first):

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 3221226505 in

**Comment by matthiask** [comment]
Search for the error on the web and you'll find it's a Python bug, and not related to django-ckeditor specifically.

Good luck!
