### ISSUE TITLE
admin inline 'add another' disappears

### ISSUE THREAD

**Issue by ImplicitCoder** [django-ckeditor/django-ckeditor#525]
HI all,

If I add ckeditor to a tabular inline in the django admin, the 'add another' link at the bottom of the inline disappears. Is there any fix available?

EDIT: using a ckeditor anywhere on the admin change page removes the 'add another' link of all inlines on the change page. I guess it is some sort of javascript conflict but I'm not sure how to solve this (properly).

EDIT 2: In chromium console I get following error:
```
inlines.js:20 Uncaught TypeError: Cannot read property 'fn' of undefined
    at inlines.js:20
    at inlines.js:298
```

EDIT 3: It is due to jquery that is not yet loaded when the inlines.js script is run. I found a [hacky fix on stackoverflow](https://stackoverflow.com/questions/50707750/django-admin-stackedinline-not-loading-add-another-model-uncaught-typeerror-ca) (wait 300ms to call inlines.js basically). However, there must be a better solution.

ckeditor version 5.6.1
django version 2.1

Thanks!

**Comment by matthiask** [comment]
This is probably fixed now that `ckeditor-init.js` doesn't depend on jQuery anymore.
