### ISSUE TITLE
Images uploaded to AWS s3 via ckeditor expire after one hour

### ISSUE THREAD

**Issue by peter-doherty** [django-ckeditor/django-ckeditor#526]
I'm uploading images in ckeditor to an AWS S3 bucket. I'm using Django. The images disappears from the blog post after 60 mins. However, I have uploaded the blog cover photo and this image does not expire. So, I think there is a setting or configuration that I'm missing. 

Where could I find this?
Thanks

**Comment by riklaunim** [comment]
Check django filestorage configuration for that S3 backend.
