### ISSUE TITLE
upload an image outside admin

### ISSUE THREAD

**Issue by iliya-hajjar** [django-ckeditor/django-ckeditor#529]
Hi, 
how can I upload images outside admin, I mean when I want to upload an image, it redirects me to a log in page and says I have to log in as an admin . I went through all issues and document to find anything related to my problem but I could not find anything . Is there any solution ?

PS: to accentuate a little, I don't use admin and it forces me to use admin when I want to upload imges.

**Comment by matthiask** [comment]
https://github.com/django-ckeditor/django-ckeditor#restricting-file-upload

Short version: Use your own `urls.py` to refer to the views. The staff member restriction is only a default, not a must have.
