### ISSUE TITLE
'User' object has no attribute 'is_superuser'

### ISSUE THREAD

**Issue by logicappsource** [django-ckeditor/django-ckeditor#532]
I get an Attribute error in production which is freaking annoying, tried to look into urls.py in CKEDITOR

and removed the memberstaff required... Still not working , very frustating! 

Request Method: | GET
-- | --
https://mynordicroom.herokuapp.com/ckeditor/browse/?CKEditor=id_body&CKEditorFuncNum=1&langCode=en
2.0
AttributeError
'User' object has no attribute 'is_superuser'
/app/.heroku/python/lib/python3.7/site-packages/django/utils/functional.py in inner, line 216
/app/.heroku/python/bin/python
3.7.0
['/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python37.zip',  '/app/.heroku/python/lib/python3.7',  '/app/.heroku/python/lib/python3.7/lib-dynload',  '/app/.heroku/python/lib/python3.7/site-packages',  '/app/.heroku/src/django-import-export']
Sat, 5 Jan 2019 22:26:15 +0000

**Comment by logicappsource** [comment]
This is the trace back : 


    if user and not user.is_superuser: ...
        user_path = _get_user_path(user)
    else:
        user_path = ''
    browse_path = os.path.join(settings.CKEDITOR_UPLOAD_PATH, user_path, path)
▼ Local vars

**Comment by logicappsource** [comment]
Hello Matthiask , Thank you very much for your respond I really appricate it and try it :)

**Comment by johntovor** [comment]
I had the same problem but I have solved it. I don't recommend setting is_superuser=True on a normal user model.
You have to edit the views.py in ckeditor_uploader manually and everything will work correctly.

If you are running a virtual environment then navigate to the virtual environment folder in your project folder and follow the instructions to fix the error.

**env/lib/python3.8/site-packages/ckeditor_uploader/views.py**

**NB: the "env" is the name of the virtual environment so replace the "env" with the name of your virtual environment"**

Once you have opened the "views.py" locate `def get_image_files(user=None, path=""):` and change 
`if user and not user.is_superuser:
        user_path = _get_user_path(user)
    else:
        user_path = ""`

to 

` if user:
        user_path = _get_user_path(user)` .

This is how to remove the superuser requirement and any ordinary user can upload files without giving the is_superuser privileges.
