### ISSUE TITLE
How to downgrade CKEditor js library to 4.6.2 version

### ISSUE THREAD

**Issue by gameot** [django-ckeditor/django-ckeditor#533]
I need the old style Paste dialog. How can I use CKEditor library 4.6.2? 
I am using Django 2.1.
When I install django_ckeditor 5.2.2 I get error `ModuleNotFoundError: No module named 'django.core.urlresolvers'`

**Comment by riklaunim** [comment]
Old package isn't compatible with new Django. To get old ckeditor put it sources in yor project static folder and mimic the folder structure used by django-ckeditor to override it.
