### ISSUE TITLE
How to wrap whole content in a div in Django CKeditor and save in database?

### ISSUE THREAD

**Issue by dipbazz** [django-ckeditor/django-ckeditor#534]
I am using _Django CKeditor 5.6.1_ and _Django 2.0.9_ and trying to save content that I have edited on CKeditor to a database with wrapping its content inside a `div` tag. So, how can I do that?

For eg: I have a CKeditor content as below:![ckeditor content][1]
And when I save this to a database it would be saved as:

     <h2><strong>My Heading</strong></h2>
     <p>This is my paragraph</p>

But what I want to save is, wrap this content inside a `div` tag and add a class to that `div` like below:

    <div class="ckeditor-content">
       <h2><strong>My Heading</strong></h2>
       <p>This is my paragraph</p>
    </div>

 [1]: https://i.stack.imgur.com/bYdat.png

**Comment by riklaunim** [comment]
Use signals or form validation to alter the content if needed. Also rethink if such wrapping div should be a part of your content instead being a part of a template. What if you change the editor or stop using a wysiwyg?
