### ISSUE TITLE
Google Drive support ? not Cloud Storage!

### ISSUE THREAD

**Issue by bboyadao** [django-ckeditor/django-ckeditor#535]
Hi, im looking for something like https://github.com/torre76/django-googledrive-storage  for the ckeditor_uploader. if it not yet support. let me know some how i can intergrate them.

**Comment by riklaunim** [comment]
the code uses Django storage API and does not require any additional integration. If you have google cloud storage working for media files is should just work.

**Comment by NiharKashyap** [comment]
@bboyadao I am using the same thing for a django project. It works for images uploaded through `ImageField` but not Ckeditor `RichTextUploadingField` . Could you make it work?
