### ISSUE TITLE
Serving media files with GCS backend

### ISSUE THREAD

**Issue by MikeBlomm** [django-ckeditor/django-ckeditor#539]
I'm currently using a GCS bucket as a static and media backend. Both are in a shared bucket, and I wrote a small backend class to separate static files from media files in their own subdirectories.

Static files work perfectly fine and end up in the right place (e.g. <assets-bucket/static>). I'm using the RichTextUploadingField() to allow users to upload images to the bucket and use them. Uploading works fine using the google storage api, (files end up in <assets-bucket/media/upload/../..>) but it generates a URL to the media file which includes a expire-token.

Serving the media file is fine, as long as the token isn't expired. After a while the image isn't being served anymore, because the auto-generated URL has become invalid.

I set up a Cloud CDN, which has its dedicated URL and loadbalancer for serving the media files from the assets bucket. However, I can't seem to make it work that the ckeditor uses this URL, instead of the auto-generated one when an image is embedded.

1. Is there a way that the ckeditor doesn't generate a url with an expire-token?
2. Can I somehow configure the ckeditor to upload through the storage api, and serve/embed through the dedicated Cloud CDN url/loadbalancer?

**Comment by JackMorganNZ** [comment]
@MikeBlomm Did you ever solve this? I've just encountered this exact issue.

**Comment by MikeBlomm** [comment]
Sorry for the late response, but I did not solve it unfortunately.. The images are still being served through the google storage api.

**Comment by Rigno** [comment]
@MikeBlomm @JackMorganNZ I think i resolved it. So in order to upload images without an expiring url you have to enable uniform pubblic access in the bucket and the put `GS_QUERYSTRING_AUTH = False` in settings.py which will create non signed URLs for all images in the bucket that don't expire.
