### ISSUE TITLE
Update to 4.11

### ISSUE THREAD

**Issue by pacahon** [django-ckeditor/django-ckeditor#540]
Hello! 
First of all thanks for the app. 
I want to update CKEditor to the 4.11 version since I've noticed some css issues in current version which already fixed in `4.11`. 
What steps should I reproduce to do this? I've thought it's enough to replace `ckeditor/static/ckeditor/ckeditor` with a new build downloaded by the link from the previous update http://ckeditor.com/builder/d92ab52ffca329d7b5e1b78ef77a81f9 but it doesn't include all extra plugins (online builder has changed it the last year? Who knows.) I can check all plugins manually but maybe I missing something else?

**Comment by skabbit** [comment]
Interested in the same goal to update to 4.13
Did you succeed in this?

**Comment by matthiask** [comment]
The bundled CKEditor has been updated.
