### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by hsmett** [django-ckeditor/django-ckeditor#541]
Hello @matthiask :)
Could you make a release and upload it on pypi please ?
Thank you !

**Comment by matthiask** [comment]
I unfortunately do not have access to PyPI. @riklaunim would be great if you find the time to upload a new release. Thanks in advance!

**Comment by riklaunim** [comment]
can be done.

**Comment by hsmett** [comment]
Let me know if I can help :) Have a good week !

**Comment by riklaunim** [comment]
New version released.

@matthiask I can add you as a maintainer on pypi.

**Comment by hsmett** [comment]
Thank you !

**Comment by matthiask** [comment]
@riklaunim Yes, that would be great.

**Comment by riklaunim** [comment]
@matthiask what's your username there?

**Comment by matthiask** [comment]
@riklaunim Same as here, https://pypi.org/user/matthiask/
