### ISSUE TITLE
How can I add watermark on pic?

### ISSUE THREAD

**Issue by Abeautifulsnow** [django-ckeditor/django-ckeditor#547]

**Comment by hsmett** [comment]
Hello @Abeautifulsnow 
With the latest release, you could define your own file handler backend class:
https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/backends/pillow_backend.py#L16
register it,
https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/backends/__init__.py#L26
and use it, defining the `CKEDITOR_IMAGE_BACKEND` setting.

**Comment by alstr** [comment]
I have been looking at overriding the `PillowBackend` `create_thumbnail` function to make it crop thumbnails square (I'm sure it used to do this - now it keeps the original image aspect ratio...). What would be the best way to register the custom image backend? I'm not sure where I should do this.
