### ISSUE TITLE
some plugins can not using.like 'codesnippet'.

### ISSUE THREAD

**Issue by SiewiChan** [django-ckeditor/django-ckeditor#548]
According to you 'config example', I found 'codesnippet' can not using.the 'extraplug' didn't show when I config 'toolbar_Custom'.When I set toolbar is 'full',the 'codesnippet' is show in page.I don't understand the reason?
Virtualenv:
Django:2.1.7
python：：3.6.7

**Comment by NitaiFraire** [comment]
i have the same problem.
But i can not see the codesnippet icon even if i set the toolbar to full
