### ISSUE TITLE
[XXS - CVSS Score 6.5] Update ckeditor to 4.11.4

### ISSUE THREAD

**Issue by ronnievdc** [django-ckeditor/django-ckeditor#549]
> CKEditor 4.11 fixes an XSS vulnerability in the HTML parser reported by maxarr. The vulnerability stemmed from the fact that it was possible to execute XSS inside the CKEditor source area after persuading the victim to: (i) switch CKEditor to source mode, then (ii) paste a specially crafted HTML code, prepared by the attacker, into the opened CKEditor source area, and (iii) switch back to WYSIWYG mode. Although this is an unlikely scenario, we recommend to upgrade to the latest editor version.
https://ckeditor.com/blog/CKEditor-4.11-with-emoji-dropdown-and-auto-link-on-typing-released/

### How to find vulnerabilities
https://retirejs.github.io/retire.js/

### More information on Snyk 
https://snyk.io/vuln/SNYK-JS-CKEDITOR-72618

### Also solves
https://github.com/django-ckeditor/django-ckeditor/issues/540

**Comment by matthiask** [comment]
Fixed in 3d8879d4d6d7b42048eedda8aaf8b
