### ISSUE TITLE
HTML Tags are being removed on saving

### ISSUE THREAD

**Issue by SilverFoxA** [django-ckeditor/django-ckeditor#552]
It's a really decent library. Thank you. I implemented the same in one of my django projects, where I'm trying to get the product details. We wanted the feasibility that the product details can be HTML codebase.

When saving the HTML codebase added to this, it stores as below:

Here's my implementation

`from ckeditor.fields import RichTextField`

```
<p>Shape&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Maxi&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Neck&nbsp;<strong> &nbsp;</strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;V-Neck</p>

<p>Length<strong>&nbsp; &nbsp; </strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Maxi&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Print or Pattern Type&nbsp; &nbsp; &nbsp; &nbsp;Geometric</p>
```

Where as the above should be 

<table>
<tr>
<td>
Neck    
</td>
<td>V-Neck</td>
</tr>
</table>

I'm confused, why the table tags are being removed on saving even divs gets removed.

**Comment by alpinista82** [comment]
It's not a bug, it's a feature! If you want to disable content filtering completely, put this in your config:
`'allowedContent': True,
        'extraAllowedContent': '*(*)',`

**Comment by alpinista82** [comment]
Issue can be closed.

**Comment by ArtemBernatskyy** [comment]
Maybe we should put this in docs or in README.
It caused some confusion for sure.

**Comment by matthiask** [comment]
I'd merge a doc update for sure. This isn't specific to django-ckeditor though, that really is a CKEditor feature. So maybe we should just point people to the CKEditor docs instead :-)
