### ISSUE TITLE
'external_plugin_resources' is not being honored

### ISSUE THREAD

**Issue by alpinista82** [django-ckeditor/django-ckeditor#553]
specifying the 'external_plugin_resources' attribute for the widget doesn't lead to the plugins being loaded from a different location. wanted to load the codemirror plugin, but unfortunately django-ckeditor makes ckeditor look for the plugin in ckeditor/ckeditor/plugins directory. Please fix.

**Comment by matthiask** [comment]
Please test the current master branch if possible. Does it fix the issue?

**Comment by alpinista82** [comment]
> Please test the current master branch if possible. Does it fix the issue?

Hello Matthias,

just tried the master branch....exactly the same behaviour as the version installed via pip. For now my workaround is to simply put my extra plugins into 'ckeditor/ckeditor/plugins' directory. I just hope that I remember that when I upgrade the package.

Thanks and best regards

Paul

**Comment by matthiask** [comment]
Can you please post your code? This might be helpful.

**Comment by alpinista82** [comment]
Right now I am at work, but it must have been something like this:
In myapp/admin.py:
`class `MyModelForm(ModelForm):`
    `class` `Meta:`
          `...`
          widgets = { 'myModelContent': CKEditorUploadingWidget(config_name = 'myconfig'),\ extra_plugins='someplugin', external_plugin_resources=[['pluginname', '/path/to/plugin/dir', 'plugin.js']]}`

**Comment by matthiask** [comment]
Looks good, I have no idea why this wouldn't work.

That being said, it's now possible to specify `external_plugin_resources` and `extra_plugins` using `CKEDITOR_CONFIGS` (since 5.7.1) so maybe you want to try this instead?

**Comment by alpinista82** [comment]
Hey Matthias! Thanks a lot! Just tried it out: this now works flawlessly! Maybe you want to clarify this in the documentation. I will close this issue now. Have a nice weekend!
