### ISSUE TITLE
Why do we need migration when changing TextField -> RichTextField ?

### ISSUE THREAD

**Issue by ArtemBernatskyy** [django-ckeditor/django-ckeditor#557]
When I change from `TextField` -> `RichTextField` (without changing any `blank`, `null` etc)
it generates this migration 

    import ckeditor.fields
    from django.db import migrations

    class Migration(migrations.Migration):

        dependencies = [
            ('mail', '0006_some_previous_migration'),
        ]

        operations = [
            migrations.AlterField(
                model_name='message',
                name='body_html',
                field=ckeditor.fields.RichTextField(blank=True, null=True),
            ),
        ]

Which doesn't change db (PostgreSQL) structure at ALL

Why do we need it ? Thx !

**Comment by matthiask** [comment]
This could be avoided in principle but isn't right now.

Django also generates migrations if you change `blank` or `verbose_name` and those also do not have an effect on the underlying DB, so this issue isn't exactly specific to django-ckeditor.

**Comment by matthiask** [comment]
Here's an example: https://github.com/matthiask/django-cabinet/blob/fde37f493f70e48f6c3438ca01157b947a806273/cabinet/fields.py#L73-L75

**Comment by ArtemBernatskyy** [comment]
Yeah, I see your point now. It makes sense.
Thx for explanations.
