### ISSUE TITLE
Readonly Rendering in Admin

### ISSUE THREAD

**Issue by dwasyl** [django-ckeditor/django-ckeditor#560]
This is more of a Django issue than a specific ckeditor issue, but I'm wondering if anyone has sorted out how to `mark_safe()` a CKEditor field in `readonly_fields` mode in the Djano admin? Whether it's just the field marked as `readonly_fields`, or the user only has `view` permission (Django 2.x), the field is rendered directly.

The display of the field can't be overwritten (without renaming the field), and based on the `widgets.py` when no `renderer` is specified the script users `get_default_renderer()`.

Has anyone else found a way around this yet?

Edit:
The only solution that I've come up with is to default render `CKEditorWidget` as `mark_safe()`, but I'm sure that wouldn't be the desirable function for everyone.

**Comment by thunderamur** [comment]
Confirm this issue.

**Comment by thunderamur** [comment]
I added this to the model:
`    def text_html(self):
        return mark_safe(self.text)

    text_html.short_description = 'Text'
`
And used next for readonly_fields - 'text_html'.

**Comment by GunnerGorilla** [comment]
![1](https://user-images.githubusercontent.com/52919668/62414682-70e72400-b63c-11e9-9192-4bb2ac80753e.png

**Comment by GunnerGorilla** [comment]
unable to upload images plz guys fix this soon i am in big trouble,plz fix it asap

**Comment by riklaunim** [comment]
@GunnerGorilla did you checked what the exception was? Image uploading should work so spending 5 minutes to see what's going wrong could solve your problem immediately.

**Comment by some1ataplace** [comment]
Code that uses mark_safe() to display a CKEditor field in readonly_fields mode in the Django admin:

```
from django.contrib import admin
from django.utils.safestring import mark_safe
from ckeditor.widgets import CKEditorWidget
from .models import MyModel

class MyModelAdmin(admin.ModelAdmin):
    readonly_fields = ('content_display',)

    def content_display(self, obj):
        return mark_safe(obj.content)

    content_display.short_description = 'Content'

    formfield_overrides = {
        models.TextField: {'widget': CKEditorWidget},
    }

admin.site.register(MyModel, MyModelAdmin)
```


This code defines a MyModelAdmin class that inherits from admin.ModelAdmin. It sets the readonly_fields attribute to include a content_display field, which is a read-only version of the content field that uses mark_safe() to display the CKEditor content as HTML. 

The content_display method is defined to return the content field as HTML using mark_safe(). The short_description attribute is set to 'Content' to display a more user-friendly label for the field.

The formfield_overrides attribute is also set to use the CKEditorWidget for all TextField form fields.

Finally, the MyModel model is registered with the MyModelAdmin class in the Django admin using admin.site.register()

**Comment by mardukbp** [comment]
Here is a generic reusable solution using a mixin.

```python
from django.db import models
from django.utils.safestring import mark_safe

from ckeditor.widgets import CKEditorWidget


class RichTextField:
    formfield_overrides = {
        models.TextField: {
            'widget': CKEditorWidget
        }
    }

    def get_fields(self, request, obj=None):
        if self.show_readonly(request, obj):
            return self.fields + (self.readonly_field,)

        return self.fields + (self.field,)
        
    def get_readonly_fields(self, request, obj=None):
        def readonly_field(obj):
            return mark_safe(getattr(obj, self.field))

        readonly_field.short_description = self.field.capitalize()

        if self.show_readonly(request, obj):
            setattr(self, self.readonly_field, readonly_field)

            return tuple([
                readonly_field if readonly_field != self.field else self.readonly_field
                for readonly_field in self.readonly_fields
            ])

        return self.readonly_fields

    @property
    def readonly_field(self):
        return 'readonly_' + self.field

    def show_readonly(self, request, obj):
        return (
            self.field in self.readonly_fields or 
            not self.has_change_permission(request, obj)
        )


class DocumentationField(RichTextField):
    field = 'documentation'


class MyModelAdmin(DocumentationField, admin.ModelAdmin):
    fields = ('name',)
    readonly_fields = ('documentation',)
```
