### ISSUE TITLE
TypeError unhashable type: 'JS'

### ISSUE THREAD

**Issue by jumasheff** [django-ckeditor/django-ckeditor#568]
Hey, thanks for wonderful package!

I don't know why, but in `django/forms/widgets.py` `JS(ckeditor/ckeditor-init.js, {})` part gets included to a list of static assets :( See screenshots below.
```python
[JS(ckeditor/ckeditor-init.js, {"data-ckeditor-basepath": "/media/static/ckeditor/ckeditor/", "id": "ckeditor-init-script"}, static=True), 'ckeditor/ckeditor/ckeditor.js']
```

Versions:
django `2.2.3`
django-ckeditor `5.6.1`

Sentry error screenshots:

<img width="829" alt="Screen Shot 2019-09-06 at 1 30 58 AM" src="https://user-images.githubusercontent.com/3319967/64374718-365f1580-d046-11e9-87d7-270366c521c3.png">
<img width="797" alt="Screen Shot 2019-09-06 at 1 32 02 AM" src="https://user-images.githubusercontent.com/3319967/64374717-365f1580-d046-11e9-9765-09d750a6a25c.png">

**Comment by matthiask** [comment]
You should try updating to django-js-asset 1.2.2: https://github.com/matthiask/django-js-asset/commits/master

**Comment by jumasheff** [comment]
Woohoo! Thank you so much, @matthiask ! The issue was resloved right after updating the dependency you pointed to.
