### ISSUE TITLE
modify config with widget args?

### ISSUE THREAD

**Issue by tisdall** [django-ckeditor/django-ckeditor#569]
I know I can select a configuration defined in settings with `config_name='my_config'`.  But is there a way to modify the configuration with other args to the init?  For example, let's say I wanted to use a configuration in settings, but only modify the `'format_tags'` in that one case.  Is it possible to pass some argument that would modify that one configuration?  (I looked through the source and couldn't see any way)

It'd be convenient to do the following:
```python
CKEditorUploadingWidget(config_name='my_config', config={'format_tags', 'p;h1;h2'})
```

**Comment by matthiask** [comment]
I would like this too. It isn't possible currently.
