### ISSUE TITLE
about upload tag button?

### ISSUE THREAD

**Issue by yslhzj** [django-ckeditor/django-ckeditor#572]
Hello, I am using the demo, of django-ckeditor to run the django program, only to find that there is no upload tag button, how can I solve it?

![image](https://user-images.githubusercontent.com/29890756/66554585-d8ab7500-eb7f-11e9-96fa-3d5f1b0e2a55.png)

**Comment by wodn5515** [comment]
If you haven't solved it yet, you should use RichTextUploadingField instead of RichTextField.
