### ISSUE TITLE
i can't change all static files path 

### ISSUE THREAD

**Issue by AlexTolmy** [django-ckeditor/django-ckeditor#573]
https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor/widgets.py#L76
this file 'ckeditor/ckeditor-init.js' and 
this file https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor/widgets.py#L84
why ? 
i want use my path for all ckeditor static files

**Comment by xch91** [comment]
I'm bumping into the same issue as well T____________T

**Comment by matthiask** [comment]
I have no idea what you're trying to do and what does not work. Can you elaborate?

**Comment by xch91** [comment]
Essentially what I'm trying to achieve is hosting ckeditor assets separately from my other assets. For example hosting most of the web assets in a more dynamic CDN and ckeditor (since it's only used in Django admin) in a more static and dedicated place with another domain.

**Comment by matthiask** [comment]
@xch91 You'd have to write your own Django staticfiles storage backend for this. It's certainly doable.

**Comment by xch91** [comment]
Yea, eventually resolved to serving those static files with Django instead of CDN
