### ISSUE TITLE
django-ckeditor don't load any JS instance

### ISSUE THREAD

**Issue by darkvodka** [django-ckeditor/django-ckeditor#578]
Hi,

I try to change the readonly attribut with jquery.

I found in ckeditor documentation, this way :
CKEDITOR.instances.id_area.config.readOnly = false;

But It doesn't work with django-ckeditor because, there are not "instances" loaded.
If I try to execute : 
var allInstances=CKEDITOR.instances;
for ( var i in allInstances ){
    alert(allInstances[i].name);
}

Nothing appear.

**Comment by matthiask** [comment]
Maybe your JS is running too early. Maybe only run the JS when ckeditor instances have been fully initialized?
