### ISSUE TITLE
Text with the '<' character is not displayed correctly when using CKEditorWidget

### ISSUE THREAD

**Issue by danielrc14** [django-ckeditor/django-ckeditor#593]
So, I have an update view in django with a form that has a field with CKEditorWidget. 

When going into the view, if the field text has the character '<', the initial value of the input just strips everything from the character until the next html tag or the end of the text.

How can I override this behaviour to allow '<' in the text?

**Comment by matthiask** [comment]
Hi,

That's really a CKEditor-specific question so you should better ask it in a CKEditor forum, not in a django-ckeditor forum. Thanks.
