### ISSUE TITLE
generating new ckeditor by jquery clone

### ISSUE THREAD

**Issue by iliya-hajjar** [django-ckeditor/django-ckeditor#595]
generating new ckeditor by jquery clone will end up disabling textbox and doing anything else with tools will appear only on the first textarea. I changed all the ids but this didn't work. I want to let users add new ckeditors by clicking on a button.

**Comment by matthiask** [comment]
1. Add a new textarea to the HTML using JS
2. Attach a new CKEditor instance

Maybe this code could serve as an inspiration:
https://github.com/django-ckeditor/django-ckeditor/blob/ee3e30ea19a5e01e7722bd2bf43394dda870437d/ckeditor/static/ckeditor/ckeditor-init.js#L40-L44
