### ISSUE TITLE
Get absolute path of files when using with django-rest-framework

### ISSUE THREAD

**Issue by corand** [django-ckeditor/django-ckeditor#600]
Hi everyone,

I'm experimenting an issue when accessing to the files uploaded from ckeditor on server side, and using those files on client side. I would like to show the full file paths considering that the client can be in another domain.

That is how I am getting now this field from django rest framework:
```
{
    body: "<p><a href=\"/media/ckeditor/myfile.pdf\">download my file</a></p>"
}
```
And that is how I would like to see it:
```
{
    body: "<p><a href="http://mydomain.com/media/ckeditor/myfile.pdf\">download my file</a></p>"
}
```

Is that possible or I need to make some hack?

**Comment by riklaunim** [comment]
Django media file handling is used so it's up to django settings to return paths as you want them to be.

**Comment by corand** [comment]
Only happening with media files uploaded by djago-ckeditor. The rest of media files are served as absolute urls on the rest framework.

**Comment by TheGhostDevlopper** [comment]
any solution for this problem ?

**Comment by matthiask** [comment]
You have to process the HTML blob and modify URLs, e.g. with beautifulsoup.

Or maybe there's a way to configure CKEditor to always insert absolute URLs, however that's a CKEditor question not a django-ckeditor question.
