### ISSUE TITLE
img-fluid

### ISSUE THREAD

**Issue by iashutosh9119** [django-ckeditor/django-ckeditor#604]
**Please add or give a setting option to add img-fluid class in img tag when using image2 plugin. images uploaded by ckeditor is not responsive.**

**Comment by rupertbaker** [comment]
Hi Ash, 

I was having similar issues with images in ckeditor fields. Wrote a little template tag which I call when loading ckeditor content in certain pages. Something like this might help..... 


```

from bs4 import BeautifulSoup
from django import template
from django.utils.safestring import mark_safe

register = template.Library()


@register.filter
def format_user_html(value):
    doc = BeautifulSoup(value, "html.parser")
    for tag in doc.find_all("img"):
        # add responsive bootstrap class to images
        tag["class"] = "w-100"
    return mark_safe(str(doc))
```

**Comment by matthiask** [comment]
Yes, you should probably post-process the HTML on the server.

**Comment by iashutosh9119** [comment]
@rupertbaker Thanks for your response. 
I also adopted a similar method when didn't get an answer. 
used jquery for changing the class of <img> tags to <img class="img-fluid"> after loading the HTML part completely.

**Comment by iamMHZ** [comment]
You can also add a class to  image tags using javascript 

```
var images = document.getElementsByTagName("img");
var i;

for(i = 0; i < images.length; i++) {
    images[i].className += " imagedropshadow";
}
```

checkout this [stackoverlfow](https://stackoverflow.com/questions/6304233/adding-a-class-to-img-tags-using-javascript)
