### ISSUE TITLE
uploaded image path issue with external media storage

### ISSUE THREAD

**Issue by sandeepbalagopal09** [django-ckeditor/django-ckeditor#605]
When using external Media storages like amazon s3, the images are embedded to the content like 
bucketname.s3.amazonaws.com/media/uploads/test.jpg

This causes trouble because if we transfer the images to a bucket with different name, the embedded image path will not work. Shouldn't the embedded content be just uploads/test.jpg ?

**Comment by matthiask** [comment]
No, because then you'd always have to post-process the HTML.
