### ISSUE TITLE
The editor does not show styles of ul element

### ISSUE THREAD

**Issue by rmuktader** [django-ckeditor/django-ckeditor#610]
I selected  "Square" under bulleted list properties. How do I get that to show up in the editor? Please see screenshot https://ibb.co/qJcvQw9

Also, I added  ` 'contentsCss': 'ul {color: red;}'` in the config assuming this will turn the ul content red in the editor that is not working either.

**Comment by matthiask** [comment]
`contentsCss` should be the URL for an external CSS file if I remember correctly. I don't think inline CSS works there.

**Comment by rmuktader** [comment]
Doing this in the admin class is the only that worked for me. I hope this helps someone else.
```
    class Media:
        css = {
                'all': ('/static/css/rich-text-editor.css',)
            }
```
