### ISSUE TITLE
HTML parsing

### ISSUE THREAD

**Issue by monikatrivedi** [django-ckeditor/django-ckeditor#612]
Hi, I want to display both data:
1. `<strong>Kite</strong>`
2. **Kite**
But it is parsing the content `<strong>Kite</strong>` and displaying as '**Kite**'. I am not able to display any HTML tag.
Is there any way I can handle both the content.
Please help me out.
Thanks in advance

**Comment by matthiask** [comment]
The HTML / source code toggle button may be useful to you:
![image](https://user-images.githubusercontent.com/2627/92325129-733e5d80-f048-11ea-8629-20e5e5e2b91f.png)

Anyway, I think that's really more a CKEditor than a django-ckeditor question. Maybe you get better and quicker help in a CKEditor forum?
