### ISSUE TITLE
Materializecss issue with dialog

### ISSUE THREAD

**Issue by adigunsherif** [django-ckeditor/django-ckeditor#613]
If using materializecss and say image upload widget, materializecss affects the dialog inputs making it impossible to use radio buttons and checkboxes. Do you have a suggestions on how to solve this?
![image](https://user-images.githubusercontent.com/30326604/86243410-3ebcaa00-bb9e-11ea-97b7-385868944546.png)

**Comment by matthiask** [comment]
Hi,

That's really a CKEditor-specific question so you should better ask it ina CKEditor forum, not in a django-ckeditor forum. Thanks.
