### ISSUE TITLE
CKEditor WordCount plugin refuses to work with django-ckeditor

### ISSUE THREAD

**Issue by mayukhnair** [django-ckeditor/django-ckeditor#614]
As defined [here in the docs](https://django-ckeditor.readthedocs.io/en/latest/#optional-customizing-ckeditor-editor), I have been trying to install the [official CKEditor Word Count plugin](https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html). I have done these steps:

- added `wordcount.js` and `utils.js` from the [plugin GitHub](https://github.com/ckeditor/ckeditor5/tree/master/packages/ckeditor5-word-count) to `static/ckeditor/ckeditor/plugins/wordcount/`
- defined a `RichTextField` in my model like this:
`snippet = RichTextField(
        config_name='default',
        extra_plugins=['WordCount'],
        external_plugin_resources=[(
            'WordCount',
            'plugins/wordcount/',
            'wordcount.js'
        )],
    )`
- defined my `default` config in `settings.py` as follows:
    CKEDITOR_CONFIGS = {
        'default': {
            'toolbar': 'Custom',
            'toolbar_Custom':  [["Format", "Bold", "Italic", "Underline", "Strike", "SpellChecker"],
                    ['NumberedList', 'BulletedList', "Indent", "Outdent", 'JustifyLeft', 'JustifyCenter',
                     'JustifyRight', 'JustifyBlock'],
                    ["Table", "Link", "Unlink", "Anchor", "SectionLink", "Subscript", "Superscript"], ['Undo', 'Redo'], ["Source"],
                    ["Maximize"]],
        },
    }

(pardon the formatting, markdown isn't behaving nicely for me)

In my browser console, I end up getting `Error: [CKEDITOR.resourceManager.load] Resource name "WordCount" was not found at "http://localhost:8000/static/ckeditor/ckeditor/plugins/wordcount/wordcount.js?t=I3I8".`

Any ideas how to sort this, or is there a less painful way to use plugins like these?

django-ckeditor version 5.6.1
django version 2.1.5

**Comment by jsolly** [comment]
I know this is a super old issue, but maybe I can help someone. 
Word count is working for me. Maybe try my CKEDITOR config. I notice that my workcount plugin is in all lowercase whereas yours is using camel case.

```py
CKEDITOR_CONFIGS = {
    "default": {
        "removePlugins": "exportpdf",
        # name - Toolbar name
        # items - The buttons enabled in the toolbar
        "toolbar_DefaultToolbarConfig": [
            {
                "name": "basicstyles",
                "items": [
                    "Bold",
                    "Italic",
                    "Underline",
                    "Strike",
                    "Subscript",
                    "Superscript",
                    "RemoveFormat",
                ],
            },
            {
                "name": "clipboard",
                "items": [
                    "Undo",
                    "Redo",
                ],
            },
            {
                "name": "paragraph",
                "items": [
                    "NumberedList",
                    "BulletedList",
                    "Outdent",
                    "Indent",
                    "HorizontalRule",
                    "JustifyLeft",
                    "JustifyCenter",
                    "JustifyRight",
                    "JustifyBlock",
                ],
            },
            {
                "name": "links",
                "items": [
                    "Link",
                    "Unlink",
                ],
            },
            {
                "name": "extra",
                "items": [
                    "Blockquote",
                    "Image",
                    "Table",
                    "CodeSnippet",
                ],
            },
            {
                "name": "source",
                "items": [
                    "Maximize",
                    "Source",
                ],
            },
            {
                "name": "styles",
                "items": ["Styles", "Format", "Font", "FontSize"],
            },
            {"name": "colors", "items": ["TextColor", "BGColor"]},
        ],
        # This hides the default title provided by CKEditor
        "title": False,
        # Use this toolbar
        "toolbar": "DefaultToolbarConfig",
        # Which tags to allow in format tab
        "format_tags": "p;h1;h2;h3;h4;h5;h6",
        # Remove these dialog tabs (semicolon separated dialog:tab)
        "removeDialogTabs": ";".join(
            [
                "image:advanced",
                "image:Link",
                "table:advanced",
                "tableProperties:advanced",
            ]
        ),
        "linkShowTargetTab": True,
        "linkShowAdvancedTab": False,
        "allowedContent": True,
        # CKEditor height and width settings
        "height": "400px",
        "width": "auto",
        "forcePasteAsPlainText ": True,
        # Tab = 4 spaces inside the editor
        "tabSpaces": 4,
        # Extra plugins to be used in the editor
        "extraPlugins": ",".join(["codesnippet", "wordcount", "notification", "prism"]),
        # Character count
        "wordcount": {
            "showWordCount": False,
            "showCharCount": True,
            "showParagraphs": False,
            "countSpacesAsChars": True,
            "countHTML": True,
            "countLineBreaks": True,
        },
    }
}
```

**Comment by vncntk** [comment]
hello @jsolly, I'm struggling to make this work also. What is the step by step process for this to work?

**Comment by jsolly** [comment]
Woops. I am completely in the wrong repo. I got this working using the [django-ckeditor-5 library](https://github.com/hvlads/django-ckeditor-5).
