### ISSUE TITLE
embed element get replace with text inside the embed in ckeditor-django !!

### ISSUE THREAD

**Issue by sudhanshu456** [django-ckeditor/django-ckeditor#616]
I was trying to embed google forms in CKEditor. If I'm creating a new object in Django or we can say a new post 
then it works fine to embed the element but  when I want to edit that post again or open that in Django admin  and try to edit that embed I see the only text "Loading....."  that means the embed script and embed element is now converted inside a <p></p> tags 

that's happening to every embed item inside a CKEditor widget.
- in the first Picture, I embed an element in the source of editor 
- in the second switch to the normal view of the creditor 
- in the third when I switch back to source mode.

After embedding an element I can't access the toolbar too if want to edit the content inside of it again. (4th Picture ).

![image](https://user-images.githubusercontent.com/44128982/87846072-b7d03700-c8ea-11ea-921e-87d3c7b06e7d.png)
![image](https://user-images.githubusercontent.com/44128982/87846080-c61e5300-c8ea-11ea-85aa-447d027f6cca.png)
![image](https://user-images.githubusercontent.com/44128982/87846093-d0405180-c8ea-11ea-9281-09b5b24a79dc.png)
![image](https://user-images.githubusercontent.com/44128982/87846164-56f52e80-c8eb-11ea-8873-30f7b9d7c57a.png)

**Comment by mikeromanov** [comment]
Do you use iframe plugin? If no, switch it on. I had similar problem with emedded youtube videos (they were just disappear) until I switch on iframe plugin.

**Comment by sudhanshu456** [comment]
But why plugin? it should still work fine right , without that?

**Comment by mikeromanov** [comment]
Sorry, friend, I've forgotten. That was iframe button, not plugin. Namely, it helped when I inserted to my CKEDITOR_CONFIGS in settings.py the following row:

 {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', **'Iframe'**]},

Hopefully, it can help you, either.
