### ISSUE TITLE
django.conf.urls.url() is deprecated in favor of django.urls.re_path()

### ISSUE THREAD

**Issue by vint66** [django-ckeditor/django-ckeditor#617]
Hello,
There is depreciation error due to using legacy syntax:

/usr/local/lib/python3.8/dist-packages/ckeditor_uploader/urls.py:10: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().

Change from:
from django.conf.urls import url
url(r'^upload/', staff_member_required(views.upload), name='ckeditor_upload'),

To:
from django.urls import re_path
re_path(r'^upload/', staff_member_required(views.upload), name='ckeditor_upload'),

**Comment by matthiask** [comment]
Yes. Please submit a pull request!

**Comment by diegofsousa** [comment]
Hello guys, how are you?
I'm taking care of that refact and I'm going to launch a PR on, okay?
