### ISSUE TITLE
iframes disappear when saving again or switching between views

### ISSUE THREAD

**Issue by lguariento** [django-ckeditor/django-ckeditor#620]
**How to reproduce the issue:**

in source view, add an iframe code; for instance:

`<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/322724603&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/matthew-whiteside" title="mwhiteside" target="_blank" style="color: #cccccc; text-decoration: none;">mwhiteside</a> · <a href="https://soundcloud.com/matthew-whiteside/repercussive-2017-matthew-whiteside" title="Repercussive (2017) - Matthew Whiteside" target="_blank" style="color: #cccccc; text-decoration: none;">Repercussive (2017) - Matthew Whiteside</a></div>`

Switching to normal edit view and then saving nullifies the iframe already. Saving while still in source view retains the iframe. After saving in source view (therefore having the iframe working on the front end) and entering in edit mode again and then saving the form (whether in source view or normal view) makes the iframe disappear. I suppose because the editor enters in normal view by default and not in source view. The iframe only works if we remain in source view all the time.

See also #223 , which is closed although it doesn't seem to have been solved.

**Comment by lguariento** [comment]
Adding

`'extraAllowedContent': 'iframe[*]', 'div[*]'`

to my configuration did the trick.

**Comment by podplatnikm** [comment]
Hello @lguariento,
I'm facing the same issue but your answer `'extraAllowedContent': 'iframe[*]', 'div[*]'` is not a valid python code. How did you add support for the above-mentioned iframe ?

Thank you in advance

**Comment by lguariento** [comment]
That code goes in the Django settings file:

```
CKEDITOR_CONFIGS = {
    'default': {
        [...]
        'extraAllowedContent': 'iframe[*]; div[*]; hr[*]; iframe; div; hr',
```

**Comment by podplatnikm** [comment]
Thank you, this fixed it for me too. Did not know if it was a string or a list.

Cheers!
