### ISSUE TITLE
App-specific upload paths for images

### ISSUE THREAD

**Issue by mikeromanov** [django-ckeditor/django-ckeditor#630]
Now the upload path consists from three parts: CKEDITOR_UPLOAD_PATH, optional date path <year>/<month>/<day>, optional user path (id or other field).

What I need is more flexibility in paths:

1. Some optional path suffix to set the application-specific paths, like uploads/news/, uploads/events/, uploads/gallery/, etc.

2. More flexible path ending, to set paths like <year>/<slug>/ or <year>/<month>/<slug>/.

Is it possible to do it via some settings, or, if not, could you implements these options in the new package versions?

**Comment by matthiask** [comment]
Maybe you can use the `CKEDITOR_FILENAME_GENERATOR` setting for this. If not you could write and contribute a solution yourself?

**Comment by mikeromanov** [comment]
Thank you very much for the idea. If it is possible to generate file names together with path, it is just what I need! I will try it and write here.
