### ISSUE TITLE
"Incorrect server response" in Django application

### ISSUE THREAD

**Issue by mikeromanov** [django-ckeditor/django-ckeditor#633]
Everything look great while one is logged in as a superuser. This error appears if I try to edit a page as a common user. It disappears if I assign the user a "staff status" (which means access to the admin panel). I suspect, there should be settings that can resolve it.
UPD: It seems like the ckeditor_uploader uses admin panel while browsing or uploading files. When I try to browse server, I got an error "You are authenticated as XXXXXXX, but are not authorized to access this page."

**Comment by mikeromanov** [comment]
Solution was found [here](https://stackoverflow.com/questions/58904408/django-ckeditor-upload-permission-for-all-users-add-scroll-bar-automatically) (see answer 1). I've just update it according to the new version of Django (3.1):

1. Add following imports in the project urls.py:
`from django.contrib.auth.decorators import login_required`
`from django.views.decorators.cache import never_cache`
`from ckeditor_uploader import views as ckeditor_views`

2. Replace the following row in the urls.py:
`path('ckeditor/', include('ckeditor_uploader.urls')),`
with
`path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),`
`path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),`

Now it's working! Hope it will help to someone else.

**Comment by sarangkkl** [comment]
Brother it is not working for it is coming with error 404 image not found

**Comment by Vijay1157** [comment]
Thank you for your help

**Comment by success-99** [comment]
thanks
