### ISSUE TITLE
Limit character length and display character count on rich text field

### ISSUE THREAD

**Issue by amartya-dev** [django-ckeditor/django-ckeditor#636]
I could not find a way to do this in the existing documentation, is there a possibility to include this in the model configuration or a widget configuration somehow?

**Comment by some1ataplace** [comment]
To limit the character length and display the character count on a rich text field in Django-CKEditor, you can use the maxlength attribute and a JavaScript function to update the character count. Here's an example:

Add the maxlength attribute to your CKEditor widget in your Django form:

```
from django import forms
from ckeditor.widgets import CKEditorWidget

class MyForm(forms.Form):
    my_field = forms.CharField(widget=CKEditorWidget(attrs={'maxlength': '500'}))

```

Then, add a JavaScript function to your template to update the character count:

```
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div id="char-count"></div>
    <button type="submit">Submit</button>
  </form>

  <script>
    const field = document.querySelector('#id_my_field');
    const charCount = document.querySelector('#char-count');

    field.addEventListener('input', () => {
      const maxLength = parseInt(field.getAttribute('maxlength'));
      const currentLength = field.value.length;
      charCount.textContent = `${currentLength}/${maxLength} characters`;
    });
  </script>
{% endblock %}
```


This code adds an event listener to the CKEditor widget that updates the #char-count element with the current character count and the maximum character limit. You can modify the maxlength value and the JavaScript function to suit your specific needs.
