### ISSUE TITLE
Not able to add multiple CKEditors on same page

### ISSUE THREAD

**Issue by aryan29** [django-ckeditor/django-ckeditor#637]
Not able to add multiple CKEditors on same page
Is there a way to do it because when trying to render same form multiple times in template I am getting a JS error
![Screenshot from 2020-10-16 12-12-25](https://user-images.githubusercontent.com/43298145/96221971-161fbb00-0fa9-11eb-9a89-bbcfd337755e.png)
Error is maybe due to same name for 2 text editors but how can I resolve it

**Comment by matthiask** [comment]
Yes it's possible. You have to use different IDs for the two elements.

**Comment by aryan29** [comment]
Thanks for replying 
but Id is added by default on my form when creating it by using RichTextField in models.py
Where I should change it

**Comment by matthiask** [comment]
You could use forms with differing prefixes https://docs.djangoproject.com/en/3.1/ref/forms/api/#prefixes-for-forms

**Comment by aryan29** [comment]
I'm closing this issue as its due to django form giving a default id to each form 
Not related to django-ckeditor
And it can be solved by using your own forms using HTML and making a custom adaptor

**Comment by ylaguardia** [comment]
Here is a quick fix to help people who face this problem in the future and stumble upon this issue while searching for a solution:

```python
# Contents of admin.py
from django.contrib import admin
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Article

class ArticleAdminForm(forms.ModelForm):
    """A form to allow different ids for the CKEditorWidgets

    By default, ckeditor.fields.RichTextField seems to assign the same id to 2 different
    ckeditor fields in the same form. See this issue:

    https://github.com/django-ckeditor/django-ckeditor/issues/637

    To circumvent this, we can assign different ids to the CKEditorWidgets.
    """

    content_en = forms.CharField(widget=CKEditorWidget(attrs={"id": "content_en"}))
    content_fr = forms.CharField(widget=CKEditorWidget(attrs={"id": "content_fr"}))

    class Meta:
        model = Article
        fields = "__all__"


@admin.register(Article)
class ArticleAdmin(admin.ModelAdmin):
    form = ArticleAdminForm
```

**Comment by matthiask** [comment]
This is confusing. It works perfectly even without specifying the form field name twice, as follows:

```python
    content_en = forms.CharField(widget=CKEditorWidget())
    content_fr = forms.CharField(widget=CKEditorWidget())
```

I'm not sure what's going on in your projects. But the ID which Django's forms automatically generate are already unique *except if you're rendering the exact same form twice* which cannot work anyway.
