### ISSUE TITLE
White spaces around <a> tag when it inside <p> tag disappeared with the new version of django-ckeditor

### ISSUE THREAD

**Issue by ollko** [django-ckeditor/django-ckeditor#638]
I am upgrading Django1.7 project to Django2.2, so I upgrate django-ckeditor from 4 to 6.0 version (I tried and 5 version)
Now I got the display of my text field, where a tags are inserted without spaces. I couldn't find any settings that would help fix this. I will be very grateful for your help

**Comment by matthiask** [comment]
This sounds like a behavior change of CKEditor itself.
