### ISSUE TITLE
Using django-ckeditor with dynamically added forms (from formset)

### ISSUE THREAD

**Issue by SnakeWhisperer** [django-ckeditor/django-ckeditor#639]
I'm using django-ckeditor with a model formset and I'd like to add and remove forms dynamically, not only after the last form, but also in between pre-existing forms. I had done this before using django-ckeditor, but I can't make it work with it. I can't clone or insert the contents of the `<iframe>`, which is the HTML document with the editable field. I'm doing this outside of the admin page.

Is this possible?

**Comment by matthiask** [comment]
Yes, this is possible. django-ckeditor can be used in Django's admin inlines too, see here: https://github.com/django-ckeditor/django-ckeditor/blob/3951b726013f5c4ae465e907fba575f9b418bb95/ckeditor/static/ckeditor/ckeditor-init.js#L40-L44

The code ensures that CKEditor isn't activated on the template used for new fields (IDs having `__prefix__` somewhere) and that you only activate the CKEditor after reinserting the textarea element *with a new ID*. Django's inlines.js does this automatically. If you want the same outside the administration panel you'll have to reimplement parts of it. Here's some old code which may work (but it's not maintained well anymore) https://github.com/matthiask/towel/blob/master/towel/static/towel/towel.js

**Comment by SnakeWhisperer** [comment]
@matthiask Thank you very much for your reply and the code you shared.

I see that the code is for inserting new forms dynamically. In my case, it took more work and code because I need to add the forms in between others while keeping their form indexes in order. This was especially necessary because I am also deleting forms, which need to be hidden while maintaining their form indexes and their ids in order to have them deleted in the database when I submit. Every time I submitted the html form with these indexes and ids and their orders altered, I had validation errors. Of course, I also alter the `TOTAL-FORMS` so django can save those instances in the database. I was able to fix that before using CKEditor (the `ckeditor.fields.RichTextField`) and it works great without it, but now I can't make the django-ckeditor widget be applied to the newly added forms, just as it is for the originally rendered ones.

Excuse me if my questions are a bit basic; I'm still dipping my toes in this.

From this, 

> The code ensures that CKEditor isn't activated on the template used for new fields (IDs having __prefix__ somewhere) and that you only activate the CKEditor after reinserting the textarea element with a new ID.

I understand that any new form added will not have a CKEditor isntance, instead I'd need to re-render my html with a new context that contains that form, which is what I'm seeing right now. Am I correct? However, I don't understand the `__prefix__` part. Doesn't this apply only when I'm using `empty_form`? Should I mix the django template language in JavaScript code to use it?

I would appreciate it if you can elaborate a bit more.

**Comment by bb4L** [comment]
@SnakeWhisperer 

i'm facing the same problem:
>I can't make the django-ckeditor widget be applied to the newly added forms, just as it is for the originally rendered ones

did you find a working solution?

**Comment by matthiask** [comment]
What I'm doing in https://github.com/matthiask/django-content-editor is that I reorder inlines using Flexbox ordering. This allows me to append a new form at the end (in the HTML) but still move it somewhere in-between other forms.

**Comment by bb4L** [comment]
I am able to dynamically add forms to the formset that's not the issue, the only thing is that the new forms don't have the ckeditor widget

**Comment by matthiask** [comment]
Well yes, you'll have to call `initialiseCKEditor` somehow yourself, if your code doesn't run in the admin panel where a `formset:added` event handler does this for you.

**Comment by SnakeWhisperer** [comment]
@bb4L 

Hi. I hadn't had the chance to update here. But yes, exactly as @matthiask  says, you only need to call `initialiseCKEditor`, which is in `ckeditor-init.js`.

I really didn't have to call the actual `initialiseCKEditor`, and you don't have to either, actually. Only try to understand how it works and see what `CKEDITOR.plugins.addExternal()` and `CKEDITOR.replace()` do in the documentation. Then you only have to call them on your newly added textareas. Or, if you don't want to do this, just copy the contents of `initialiseCKEditor` and paste it in your own script under another function name. You'll have unnecessary iterations over the already processed textareas, but it'll initialize the editor correctly for your newly added ones.

Just make sure these dynamically added forms have the correct structure. Create the `div.django-ckeditor-widget` with the textarea inside.

**Comment by SnakeWhisperer** [comment]
The last comment answers the original question.

**Comment by bb4L** [comment]
@SnakeWhisperer 

sorry for not reporting back

indeed the `initialiseCKEditor` did solve the problem

thank you for the help

**Comment by IamMiracleAlex** [comment]
@bb4L @SnakeWhisperer @matthiask 
I am facing this same issue, please how exactly did you solve yours?
Adding this:
`function initialiseCKEditorInInlinedForms() { 
   if (typeof django === 'object' && django.jQuery) { 
     django.jQuery(document).on('formset:added', initialiseCKEditor); 
   } 
 } `

to my code didn’t solve it..
Please if you can see this, I need some assistance
