### ISSUE TITLE
How can I limit the color choices for TextColor and BGColor?

### ISSUE THREAD

**Issue by SnakeWhisperer** [django-ckeditor/django-ckeditor#640]
When using TextColor and BGColor in the toolbar, there are a number of choices and even a button to select more. I'd like to limit those choices to a specific set of colors and remove the button to select more colors. Can this be done? If so, how?

**Comment by matthiask** [comment]
I don't know but this is a question which isn't specific to django-ckeditor. You may have better luck getting an answer either in the CKEditor 4 documentation or in CKEditor-oriented forum / mailing list.

**Comment by SnakeWhisperer** [comment]
I found that the config option to limit the colors is `colorButton_colors`, which receives a string with the desired color options. To disable the `Automatic` button, `colorButton_enableAutomatic`, and, to disable the `More` button, `colorButton_enableMore`; both receive `True` or `False`.
