### ISSUE TITLE
Delete uploaded file from server

### ISSUE THREAD

**Issue by Marchamp** [django-ckeditor/django-ckeditor#643]
I was wondering if it is possible to delete images from storage when they are removed within the ckeditor widget.
Whenever an image is dragged into the widget, it would automatically be uploaded even before 'save'.

I tried using django-cleanup but it only works on FileField and ImageField.

Is 'delete from storage' feature built into django-ckeditor?
If so, how may I proceed?

I guess workaround solution would be to upload images as ImageField and use the image in the widget as img src url after upload.
Thanks.

**Comment by some1ataplace** [comment]
https://stackoverflow.com/questions/26201258/how-to-remove-images-uploaded-with-django-ckeditor

**Comment by some1ataplace** [comment]
1. Install django-cleanup using pip:
`pip install django-cleanup`


2. Add django_cleanup to your INSTALLED_APPS in your Django project's settings.py file:

```
INSTALLED_APPS = [
    'django_cleanup',
]
```


3. In your CKEditor configuration, add the filebrowserUploadUrl and filebrowserUploadMethod options to specify the URL and method for uploading images:

```
CKEDITOR.replace('editor', {
    filebrowserUploadUrl: '/ckeditor/upload/',
    filebrowserUploadMethod: 'form'
});
```


4. Create a Django view to handle the image upload. In this view, you can use Django's FileField to save the uploaded file to your desired storage location. The django-cleanup package will automatically delete the file when the associated model instance is deleted or updated:

```
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.files.storage import FileSystemStorage
from myapp.models import MyModel

@csrf_exempt
def upload_image(request):
    if request.method == 'POST' and request.FILES['upload']:
        myfile = request.FILES['upload']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        mymodel = MyModel(image=filename)
        mymodel.save()
        return JsonResponse({'url': fs.url})
```


4. To delete the image file when it is removed within the CKEditor widget, you can override the delete method of your Django model:

```
from django.db import models
from django.core.files.storage import default_storage
from django.conf import settings

class MyModel(models.Model):
    image = models.FileField(upload_to='images/')

    def delete(self, *args, **kwargs):
        # Delete the file from storage
        if self.image:
            default_storage.delete(self.image.name)
        # Call the parent method to delete the model instance
        super(MyModel, self).delete(*args, **kwargs)
```


5. In your CKEditor configuration, add the filebrowserDeleteUrl option to specify the URL for deleting images:
```

CKEDITOR.replace('editor', {
    filebrowserUploadUrl: '/ckeditor/upload/',
    filebrowserUploadMethod: 'form',
    filebrowserDeleteUrl: '/ckeditor/delete/'
});
```


6. Create a Django view to handle the image deletion. In this view, you can use Django's FileField to delete the image file from your storage location:

```
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from myapp.models import MyModel

@csrf_exempt
def delete_image(request):
    if request.method == 'POST' and request.POST.get('filename'):
        filename = request.POST.get('filename')
        mymodel = MyModel.objects.filter(image=filename).first()
        if mymodel:
            mymodel.delete()
            return JsonResponse({'success': True})
    return JsonResponse({'success': False})
```

***

Management command that deletes orphaned images that were uploaded and then deleted from CKEditor in Django:

```
from django.core.management.base import BaseCommand
from django.core.files.storage import default_storage
from django.conf import settings
from myapp.models import MyModel

class Command(BaseCommand):
    help = 'Deletes orphaned images that were uploaded and then deleted from CKEditor'

    def handle(self, *args, **options):
        # Get a list of all uploaded images
        uploaded_images = MyModel.objects.values_list('image', flat=True)
        # Get a list of all images in the storage directory
        storage_images = default_storage.listdir(settings.MEDIA_ROOT + '/images/')[1]
        # Get a list of orphaned images
        orphaned_images = set(storage_images) - set(uploaded_images)
        # Delete the orphaned images
        for image in orphaned_images:
            default_storage.delete('images/' + image)
        self.stdout.write(self.style.SUCCESS('Successfully deleted {} orphaned images.'.format(len(orphaned_images))))
```


This command gets a list of all uploaded images from the MyModel model, a list of all images in the storage directory, and then finds the orphaned images by comparing the two lists. It then deletes the orphaned images using Django's default_storage object. Finally, it outputs a success message to the console. You can run this command using python manage.py delete_orphaned_images.

***

On commit handler code that handles deleting images when they are deleted directly from CKEditor in Django:

```
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.core.files.storage import default_storage
from myapp.models import MyModel

@receiver(pre_delete, sender=MyModel)
def delete_image_on_commit(sender, instance, **kwargs):
    # Check if the instance has an image field
    if hasattr(instance, 'image'):
        # Delete the image file from storage
        if instance.image:
            default_storage.delete(instance.image.name)
```


This code defines an on commit handler function called delete_image_on_commit that is triggered when a MyModel instance is deleted. The function checks if the instance has an image field, and if so, deletes the image file from storage using Django's default_storage object. The @receiver decorator connects the function to the pre_delete signal for the MyModel model. This ensures that the image file is deleted after the model instance is deleted from the database.
