### ISSUE TITLE
Changes to 'contents.css' not taking effect. Need to change styles in editor widget.

### ISSUE THREAD

**Issue by SnakeWhisperer** [django-ckeditor/django-ckeditor#646]
I want to set for my ckeditor widgets, among other things, a default text color (other than black), a default background color (other than white), a background color for the editor, and change the line spacing, the font, and the padding. I found a recommendation in several places to change the `contents.css` file. However, this is not working for me.

For example, I found this ruleset in `contents.css`.

```
.cke_editable {
    font-size: 13px;
    line-height: 1.6;
    word-wrap: break-word;
}
```

If I change something here, say, `line-height: 1.1;` and reload the page, I see the new line spacing for a couple seconds, but then it goes back to `1.6`, and it's actually what I see in the inspector.

How can I make these changes take effect? If this is not the correct way to do it, then which would it be?

**Comment by some1ataplace** [comment]
Clear your browser cache and reload the page. This will force your browser to download the latest version of the CSS file.

Check if there are any other CSS files that are overriding the styles in contents.css. Use your browser's inspector tool to see which styles are being applied to the element in question and where they are coming from.
