### ISSUE TITLE
Getting two <br> with one ENTER press with `enterMode: 2` and two <p> with `enterMode: 1`.

### ISSUE THREAD

**Issue by SnakeWhisperer** [django-ckeditor/django-ckeditor#647]
This is my config in `settings.py`:

```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'colorButton_colors': '000000,0000FF,FFFF00,FF0000,FF00FF,00FFFF,008000,FFFFFF', 
        'colorButton_enableAutomatic': False,
        'colorButton_enableMore': False, 
        'extraPlugins': 'sharedspace',
        'toolbar_Custom': [
            ['Italic', 'Underline'],
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
        ],
        'sharedSpaces': {
            'top': 'top',
            'bottom': 'bottom',
        },
        'removePlugins': ['elementspath', 'resize', 'magicline'],
        'enterMode': 2,
        'height': 150,
        'width': 300,
    },
}
```

If I have an editor with the following contents: `This is a sample text.`, and I press ENTER right before the 's' in 'sample', it becomes this: `This is a <br><br><div>sample text</div>`, when—I think—it should be this: `This is a <br>sample text.` Not only I'm getting an extra `<br>`, but also that weird `<div>`.

Seen in the inspector:

![image](https://user-images.githubusercontent.com/60672110/105931023-dd1fc980-6020-11eb-98c3-ee39dac70bd3.png)

The documentation says nothing about this double `<br>` or the weird `<div>`, or at least I can't find anything.

I tried changing `enterMode` to `1`, but this is what happens:

![image](https://user-images.githubusercontent.com/60672110/105931811-405e2b80-6022-11eb-9830-cf644551787f.png)

Both are wrong.

I actually need to have `<br>` elements instead of new `<p>` elements, but I think what solves the problem with one will solve it with the other.

In case it is relevant, I am almost always pre-populating the editor with text from the database.

**Comment by matthiask** [comment]
Thanks for the report! This sounds like a behavior from CKEditor 4, and isn't specific to django-ckeditor. Maybe you have more luck here https://support.ckeditor.com/hc/en-us

**Comment by SnakeWhisperer** [comment]
@matthiask Sorry, but I think it doesn't sound like a behavior from CKEditor 4. If you go [here](https://ckeditor.com/docs/ckeditor4/latest/examples/enterkey.htmll) and choose 'Break the line with a `<br>`' and inspect the element, you'll see that it works as expected. It really looks like something happening in `django-ckeditor` and I need help finding a solution. Is it possible to reopen the issue?

**Comment by matthiask** [comment]
Oh of course, I'm sorry for closing this too quickly. But, django-ckeditor ships CKEditor 4.11.1 as-is and only adds this script https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor/static/ckeditor/ckeditor-init.js so I doubt that this behavior has anything to do (can have anything to do) with django-ckeditor.

**Comment by SnakeWhisperer** [comment]
Don't worry. Thank you very much. I also think I might have missed a configuration setting or something like that, but since I can't find it, I'm trying to make sure it's not an actual issue.
