### ISSUE TITLE
CK - Editor in django is not working in production

### ISSUE THREAD

**Issue by Nitesh-Singh-5** [django-ckeditor/django-ckeditor#648]
I am using ckeditor in my django project. It is working fine in local machine. But after deploying to web server it is not working. I can see the textarea without ckeditor tools.

**Comment by matthiask** [comment]
Please check your browser console. Do you get an error?

**Comment by Nitesh-Singh-5** [comment]
ckeditor-init.js:1  Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Nitesh-Singh-5** [comment]
ckeditor.js:1   Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by matthiask** [comment]
Did you run `collectstatic`?

**Comment by Nitesh-Singh-5** [comment]
yes I tried

**Comment by sirthom9123** [comment]
Had the same issue on apache, just make sure your ckeditor folder is in your static folder after collectstatic.

**Comment by PyOfile** [comment]
I had the same issue. I needed to do as sirthom9123 said. but I also needed to move the staticfiles.json into the static file.
