### ISSUE TITLE
Missing skin.js in skins/moono and skins/moono-lisa

### ISSUE THREAD

**Issue by ndunn219** [django-ckeditor/django-ckeditor#649]
In the documentation for django-ckeditor/ckeditor/static/ckeditor/ckeditor/skins/moono/ and django-ckeditor/ckeditor/static/ckeditor/ckeditor/skins/moono-lisa/, under **Directory Structure > Other Parts** it says that a **skins.js** file is included, but the file is missing, as are the the directories **icons** and **dev**.

This results in a 404 error when the editor is loaded:

```
ckeditor.js:105 GET https://127.0.0.1/static/ckeditor/ckeditor/skins/moono/skin.js?t=K5H9 net::ERR_ABORTED 404 (Not Found)
```

**Comment by shivan2418** [comment]
I have the same error.

**Comment by shivan2418** [comment]
Just in case this might help anyone. 
A workaround is to go to [Custom CKeditor builder](https://ckeditor.com/cke4/builder) and dowload a just the standard package. In that package under skins/moono (or whatever theme you use) you will find a `skins.js` file. 
Put that in your project on `<yourapp>/static/ckeditor/ckeditor/skins/moono/skins.js`

I removed the warning for me.

**Comment by sonny-zhang** [comment]
我也出现了这个问题，我特地记录了下这个问题的解决步骤
https://www.cnblogs.com/1fengchen1/p/15405326.html
