### ISSUE TITLE
generateckeditorthumbnails mangement command sends wrong args to create_thmbnail

### ISSUE THREAD

**Issue by fgpietersz** [django-ckeditor/django-ckeditor#650]
I get output like this:

`Creating thumbnail for editor/2021/01/17/1029920.jpg
Couldn't create thumbnail for editor/2021/01/17/1029920.jpg: create_thumbnail() missing 2 required positional arguments: 'file_object' and 'file_path'
Creating thumbnail for editor/2020/12/02/p1000041.jpg
Couldn't create thumbnail for editor/2020/12/02/p1000041.jpg: create_thumbnail() missing 2 required positional arguments: 'file_object' and 'file_path'`

The problem seems to be here:

https://github.com/django-ckeditor/django-ckeditor/blob/3951b726013f5c4ae465e907fba575f9b418bb95/ckeditor_uploader/management/commands/generateckeditorthumbnails.py#L26

Where the call is 

`backend.create_thumbnail(image)`

whereas it should be:

`backend.create_thumbnail(backend, fileobject, image)`

I am not entirely clear why we need backend as the first parameter there, but a bit of experimentation showed it does.

**Comment by stevelarocque** [comment]
I ran into this as well.  Not certain best workaround.  Using pillow.

**Comment by ppfeufer** [comment]
Same here

Any solution?

**Comment by matthiask** [comment]
If you have a workaround or a fix for the management command, submit a pull request please! (I don't use the uploader (at all) so I do not have a fix for this.)
