### ISSUE TITLE
ckeditor works in local environment, but not in production

### ISSUE THREAD

**Issue by Nitesh-Singh-5** [django-ckeditor/django-ckeditor#652]
Django-ckeditor works fine on local server but does not works in production.
I tried `python manage.py collectstatic` also

**Comment by ShyamSundhar1411** [comment]
Same here Sir, ckeditor_uploader gives http 500 error when images are uploaded and sent to server

**Comment by eggsmayhem** [comment]
What do you mean by "does not work in production" ? Do you mean that it is not visible?

It might have something to do with your static file paths, as django handles them internally in development, but you need your staticfiles to be properly configured in production.

I assume from your wording that your other static files (such as css) are working properly. 

What is your production environment? If it is heroku, it should collectstatic automatically during a build, but this is worth checking.

Some more likely things to check: 

1.Is your STATIC_URL set to '/static/'
2.The CKEDITOR_BASEPATH, unlike other static paths, needs to be manually set or it can cause errors.

If you are using Django, for instance: on the page where the CKEDITOR should be (i.e. whichever template.html page), before using {% load static %}, manually set the CKEDITOR_BASEPATH like so: 

<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>

I find that the above issue (including adding or omitting a '/' somewhere when concatenating the paths, has caused people an issue where their CKeditor was not loading when Debug=False.
