### ISSUE TITLE
Which plugins are not enabled by default?

### ISSUE THREAD

**Issue by OmidShojaee** [django-ckeditor/django-ckeditor#657]
The documentation says some plugins are not enabled by default. How we are going to find out which one is enabled and which one isn't??

**Comment by matthiask** [comment]
We are using the "full" preset of CKEditor 4. The information you seek is available on the official CKEditor website (NOT django-ckeditor)

**Comment by OmidShojaee** [comment]
Then please update your documents accordingly.

**Comment by matthiask** [comment]
Thanks for the suggestion. A pull request would be even better.

**Comment by OmidShojaee** [comment]
I'm sorry but I'm still confused. Yes you use full preset, but again how do I know which plugins are "enabled" (not just "included")?

**Comment by matthiask** [comment]
Oh, right. I'm sorry I cannot help you there. Here's the default configuration:  https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor/configs.py
And here's the comparison: https://ckeditor.com/cke4/presets

If that still doesn't answer your question (I think it does not, unfortunately) you may want to check out the issue tracker or the FAQ for CKEditor 4 https://support.ckeditor.com/hc/en-us
