### ISSUE TITLE
Update the package with my own custom package

### ISSUE THREAD

**Issue by omidshojaee** [django-ckeditor/django-ckeditor#659]
Hello,

What happens if I build my own custom package (on CKEditor website) and overwrite the files inside virtual environment with that?

**Comment by matthiask** [comment]
You should probably put it into a folder in `STATICFILES_DIRS` https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-STATICFILES_DIRS instead of modifying files inside your virtualenv.

You're welcome.

**Comment by OmidShojaee** [comment]
Thanks. 

And then how to use that instead of what is stored in site-packages?

**Comment by matthiask** [comment]
If you're using Django's staticfiles app to serve assets in development resp. to collect assets for production files are automatically picked up from the first (last?) location where they can be found. It basically works the same way as overriding templates. I hope this helps.
