### ISSUE TITLE
Widget config copy vs deepcopy

### ISSUE THREAD

**Issue by bernhardmiller** [django-ckeditor/django-ckeditor#660]
I ran into a problem with dynamically changing the configuration for one of many ckeditor widgets in my site. One of the widgets should also contain an additional print button. I decided to modify the config of this particular widget on the fly:
`self.fields["my_input"].widget.config["toolbar"].append({"name": "print", "items": ["Print"]})`
However, this leads to one more print button for every time the widget is rendered.

https://github.com/django-ckeditor/django-ckeditor/blob/edff11fc84fc8f25cf0d29ae23e2f00c4d309c02/ckeditor/widgets.py#L60
Shouldn't this be a deep copy, instead of a shallow one? I'm happy to provide a patch for this; but I'm not sure yet if I should be doing it, or if modifying widget configs dynamically is an absolute no-go for some reason.

Looking forward to your input!

**Comment by matthiask** [comment]
I'd recommend copying the configuration into your project's settings file and modifying the configuration there, see https://github.com/django-ckeditor/django-ckeditor#optional-customizing-ckeditor-editor

**Comment by bernhardmiller** [comment]
Ok, then I'll just close this as a non-recommended usage.
Thank you!
