### ISSUE TITLE
How to allow html block-level tags to be wrapped in an anchor tag in CKEDITOR_CONFIGS

### ISSUE THREAD

**Issue by ashrafemad** [django-ckeditor/django-ckeditor#663]
I'm trying to allow adding divs inside <a> tag but it always get converted into wrapping the <a> inside the div
i found a solution in native CKEditor:

```
CKEDITOR.dtd.a.div = 1;
CKEDITOR.dtd.a.p = 1;
```

but don't know how to add these settings in CKEDITOR_CONFIGS dict

any ideas?

**Comment by ashrafemad** [comment]
i made a workaround by adding config.js file to my static directory and moved my app above ckeditor in INSTALLED_APPS
don't know if this will make any troubles

**Comment by matthiask** [comment]
That sounds like a good way. Just make a note to yourself to re-check the contents of `config.js` when upgrading :)
