### ISSUE TITLE
Manual YouTube iframe embed gets deleted when switching views

### ISSUE THREAD

**Issue by Kaszanas** [django-ckeditor/django-ckeditor#664]
When attempting to include YouTube embed ```<iframe>``` by hand in the "Source" part of the django-ckeditor:

![image](https://user-images.githubusercontent.com/34846245/114216109-c2de6200-9966-11eb-8ded-d4eacaf6487b.png)

After switching out of the source view the embed is deleted.
Looking back into the source shows the following:

```
<p>&nbsp;</p>
```

I understand that there are plugins that are meant to allow for YouTube embedding but it seems unnecessary as one could simply paste ```<iframe>``` tag with the required embeding code.

**Comment by podplatnikm** [comment]
Hello,

I have the same issue. Any updates on how you solved this @Kaszanas  ?

Cheers

**Comment by Kaszanas** [comment]
@podplatnikm 

The solution was simple.
I have stopped using ckeditor and went towards pure text input. Now I generate HTML from markdown and just paste it into the text input. I might at some point go in and verify if my system is able to render Markdown.

**Comment by Revocsid** [comment]
Hello, 

The issue seems to be fixed if you add the following in the `CKEEDITOR_CONFIGS`

```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'MyToolbarConfig',
        'toolbar_MyToolbarConfig': [
           ... other lines
            {'name': 'insert',
             'items': ['Iframe', ... other components]},
        ],
        'extraPlugins': ','.join([
            'iframe'
        ]),
    }
}
```

After that, when you will switch to editor mode, you will see
<img width="838" alt="Screenshot 2021-09-24 at 13 47 23" src="https://user-images.githubusercontent.com/6648115/134669418-ebd6381a-b808-4396-a292-d68a3269a402.png">
