### ISSUE TITLE
upload image with wrong url

### ISSUE THREAD

**Issue by sgnes** [django-ckeditor/django-ckeditor#668]
when I upload image using ckeditor, issue is the generated url is not correct on windows platform.
**#settting.py**
```
CKEDITOR_MEDIA_PREFIX="/site_media/media/ckeditor/"
CKEDITOR_UPLOAD_PATH = os.path.join(BASE_DIR,"site_media" , "media/uploads").replace("\\",'/')
CKEDITOR_UPLOAD_PREFIX=os.path.join(BASE_DIR,"/site_media/media/uploads").replace("/","\\")
```

**uploading:**
![image](https://user-images.githubusercontent.com/8180266/119261095-5c588f00-bc08-11eb-8b09-5d89e27d0b77.png)
the url
![image](https://user-images.githubusercontent.com/8180266/119261112-6c706e80-bc08-11eb-9a65-afbf359c9e19.png)

![image](https://user-images.githubusercontent.com/8180266/119261142-9d50a380-bc08-11eb-8d0e-1b55df2ed546.png)
`
C%3A/Users/sunguo2/Code/Django/InnovationJourney/site_media/media/uploads/2021/05/23/11111_flFlEOr.png`
should be "C:/Users/sunguo2/Code/Django/InnovationJourney/site_media/media/uploads/2021/05/23/11111_flFlEOr.png"

**the python versions:**
![image](https://user-images.githubusercontent.com/8180266/119261289-4f886b00-bc09-11eb-87e4-6d9fc9c6b052.png)

**Comment by pujanrajrai** [comment]
have anyone found the solution?
