### ISSUE TITLE
Display issues with Django admin's Dark theme

### ISSUE THREAD

**Issue by subodhk01** [django-ckeditor/django-ckeditor#670]
As part of the Django 3.2 release, the django admin panel has a dark mode by default. The CSS for the admin dark mode affects how the ckeditor instance components are displayed on the admin panel.

Below are the screenshots of some ckeditor components.

![image](https://user-images.githubusercontent.com/19875783/119770488-e0956580-bed9-11eb-944e-3e8ae5a4a152.png)

![image](https://user-images.githubusercontent.com/19875783/119770526-ee4aeb00-bed9-11eb-8e37-84b4f071f328.png)

![image](https://user-images.githubusercontent.com/19875783/119770555-f99e1680-bed9-11eb-8a2d-cc52039c75ad.png)

**Comment by Laikos38** [comment]
Hi! Did you find a solution?

**Comment by subodhk01** [comment]
@Laikos38 No nothing yet

**Comment by Laikos38** [comment]
A "fix" is just force the light theme of Django admin. Override admin/base.html template (https://docs.djangoproject.com/en/3.2/howto/overriding-templates/), extend from original but replacing de dark theme CSS variables for the light ones. 
```html
{% extends "admin/base.html" %}
{% load static %}

{% block extrastyle %}
    {{ block.super }}
    <style>
/**
 * These rules are shamelessly lifted from  django/contrib/admin/static/admin/css/base.css
 * for "@media (prefers-color-scheme: dark)".
 * "html" added to ":root" for added CSS specificity.
 */
@media (prefers-color-scheme: dark) {
  :root {
    --primary: #79aec8;
    --secondary: #417690;
    --accent: #f5dd5d;
    --primary-fg: #fff;

    --body-fg: #333;
    --body-bg: #fff;
    --body-quiet-color: #666;
    --body-loud-color: #000;

    --header-color: #ffc;
    --header-branding-color: var(--accent);
    --header-bg: var(--secondary);
    --header-link-color: var(--primary-fg);

    --breadcrumbs-fg: #c4dce8;
    --breadcrumbs-link-fg: var(--body-bg);
    --breadcrumbs-bg: var(--primary);

    --link-fg: #447e9b;
    --link-hover-color: #036;
    --link-selected-fg: #5b80b2;

    --hairline-color: #e8e8e8;
    --border-color: #ccc;

    --error-fg: #ba2121;

    --message-success-bg: #dfd;
    --message-warning-bg: #ffc;
    --message-error-bg: #ffefef;

    --darkened-bg: #f8f8f8; /* A bit darker than --body-bg */
    --selected-bg: #e4e4e4; /* E.g. selected table cells */
    --selected-row: #ffc;

    --button-fg: #fff;
    --button-bg: var(--primary);
    --button-hover-bg: #609ab6;
    --default-button-bg: var(--secondary);
    --default-button-hover-bg: #205067;
    --close-button-bg: #888; /* Previously #bbb, contrast 1.92 */
    --close-button-hover-bg: #747474;
    --delete-button-bg: #ba2121;
    --delete-button-hover-bg: #a41515;

    --object-tools-fg: var(--button-fg);
    --object-tools-bg: var(--close-button-bg);
    --object-tools-hover-bg: var(--close-button-hover-bg);
  }
}
    </style>
{% endblock extrastyle %}
```

**Comment by subodhk01** [comment]
Yeah that is for sure a temporary fix, but I was thinking maybe the ckeditor devs can add something native for that

**Comment by matthiask** [comment]
It seems CKEditor 4 itself doesn't really support dark mode without switching to a different skin. I would think that a fix for this issue is out of scope for django-ckeditor but since the editor is basically rendered unusable maybe someone wants to contribute a CSS file which fixes the worst problems using an override? The CKEditor code itself cannot be changed because this makes it hard to upgrade the bundled CKEditor in the future.

**Comment by alperencapar** [comment]
Still there is no long term solution for this issue. 

(tempporary fix)
Changing skin will fix problem without manually changing  `background-color: black` and `color: white`

```
CKEDITOR_CONFIGS = {
    "default": {
        'skin': 'moono-dark',
    }
}
```

**Comment by plumber-craic** [comment]
I wanted to keep my dark admin theme, but get the Image form to be light, so I changed the selector to:
```
@media (prefers-color-scheme: dark) {
  :root .cke_dialog_body {
...
}
```

**Comment by Wecros** [comment]
I fixed this issue temporarily by downloading the source of `moono-dark` and changing color settings on those elements that required it.

**Comment by matthiask** [comment]
I think it would probably be a good idea to ship a few CSS overrides and include them by default. A good start may be these CSS rules:

https://github.com/matthiask/feincms3/blob/26cf2c9aab2317a1accc3ae61b47c6671a3d33fc/feincms3/static/feincms3/inline-ckeditor.css#L93-L102

**Comment by hashlash** [comment]
> I think it would probably be a good idea to ship a few CSS overrides and include them by default. A good start may be these CSS rules:
> 
> https://github.com/matthiask/feincms3/blob/26cf2c9aab2317a1accc3ae61b47c6671a3d33fc/feincms3/static/feincms3/inline-ckeditor.css#L93-L102

I've tried the CSS rules and it (at least) does make the link and image popup readable. However, the source mode is still unreadable.

**Comment by matthiask** [comment]
I'm sure it's not sufficient but it's a start. It would be great if you did find the necessary CSS rules for this. And even better if you or someone would submit a pull request :)

**Comment by hashlash** [comment]
I'll check more on this and hopefully could create a PR in a week or two

**Comment by hashlash** [comment]
Created the PR, could you please kindly check? @matthiask
