### ISSUE TITLE
Django's ManifestStaticFilesStorage can't handle some static files

### ISSUE THREAD

**Issue by TZanke** [django-ckeditor/django-ckeditor#675]
### 1. Wrong relative paths, not resolvable outside a JS engine
CKEditor uses a lot of assets not relative to the ckeditor.js, but relative to `this.path` or stuff like this:
`addContentsCss(this.path+"styles/tableselection.css")`

 To fix most of this kind of issues, i created a custom `ManifestStaticFilesStorage`:

```
class CustomManifestStaticFilesStorage(ManifestStaticFilesStorage):
    patterns = (
        ("*.css", (  # extension to search in
            (r"""(url\(\s*([^'"]*?)\))""", """url(%s)"""),
            (r"""(url\('\s*(.*?)'\))""", """url('%s')"""),
            (r"""(url\("\s*(.*?)"\))""", """url("%s")"""),
        )),
        ("*.js", (  # extension to search in
            (r"""(getUrl\('([^'"]*?)'\))""", """getUrl('%s')"""),
            (r"""(getUrl\("([^'"]*?)"\))""", """getUrl("%s")"""),
            (r"""(getUrl\(this\s?\.\s?path\s?\+\s?'([^'"]*?)'\))""", """getUrl(this.path+'%s')"""),
            (r"""(getUrl\(this\s?\.\s?path\s?\+\s?"([^'"]*?)"\))""", """getUrl(this.path+"%s")"""),

            # https://code.djangoproject.com/ticket/32849
            (r"""(appendStyleSheet\(this\s?\.\s?path\s?\+\s?"([^'"]*?)"\))""", """appendStyleSheet(this.path+"%s")"""),
            (r"""(addContentsCss\(this\s?\.\s?path\s?\+\s?"([^'"]*?)"\))""", """addContentsCss(this.path+"%s")"""),
        )),
    )


    def _url(self, hashed_name_func, name, force=False, hashed_files=None):
        # fix ckeditor's not path relative includes, ckeditor includes it by module path which we dont know here.
        name = name.replace('ckeditor/ckeditor/plugins/uicolor/dialogs/plugins/uicolor/yui/', 'ckeditor/ckeditor/plugins/uicolor/yui/')
        name = name.replace('ckeditor/ckeditor/plugins/uicolor/plugins/uicolor/', 'ckeditor/ckeditor/plugins/uicolor/')

        # fix ckeditor imports plugins relative to a variable (not known to replace regex)
        name = name.replace('ckeditor/ckeditor/dialogs/dialog.css', 'ckeditor/ckeditor/plugins/scayt/dialogs/dialog.css')
        name = name.replace('ckeditor/ckeditor/dialogs/options.js', 'ckeditor/ckeditor/plugins/scayt/dialogs/options.js')
        name = name.replace('ckeditor/ckeditor/dialogs/paste.js', 'ckeditor/ckeditor/plugins/clipboard/dialogs/paste.js')
        name = name.replace('ckeditor/ckeditor/dialogs/templates.js', 'ckeditor/ckeditor/plugins/templates/dialogs/templates.js')
        name = name.replace('ckeditor/ckeditor/images/hiddenfield.gif', 'ckeditor/ckeditor/plugins/forms/images/hiddenfield.gif')
        name = name.replace('ckeditor/ckeditor/images/pagebreak.gif', 'ckeditor/ckeditor/plugins/pagebreak/images/pagebreak.gif')
        name = name.replace('ckeditor/ckeditor/images/placeholder.png', 'ckeditor/ckeditor/plugins/flash/images/placeholder.png')
        name = name.replace('ckeditor/ckeditor/styles/copyformatting.css', 'ckeditor/ckeditor/plugins/copyformatting/styles/copyformatting.css')
        name = name.replace('ckeditor/ckeditor/styles/dialog.css', 'ckeditor/ckeditor/plugins/dialog/styles/dialog.css')
        name = name.replace('ckeditor/ckeditor/styles/tableselection.css', 'ckeditor/ckeditor/plugins/tableselection/styles/tableselection.css')

        return super(CustomManifestStaticFilesStorage, self)._url(hashed_name_func, name, force, hashed_files)
```

### 2. Dynamic paths

But some paths are even more challenging, cause outside a JS engine i don't know the `skin.name`:

`CKEDITOR.document.appendStyleSheet(this.path + "skins/" + CKEDITOR.skin.name + "/wsc.css")`

### 3. Even Worse

`plugin.js` and some other files are loaded completely out of nowhere aka dynamic path generation.

### Question

How to solve 2 & 3? Right now i really have no clue how to fix the detection. This is not a show-stopper, cause the files will be delivered to the browser/user as a none-cached version, but it produces load and even worse, maybe a slight delay loading the files every time.

But also, i have to mention, i think this is a basic problem of how the ckeditor itself works. But to find a solution, i will start right here at django-ckeditor. :)

Best regards

**Comment by matthiask** [comment]
I'm not sure whether it's necessary to post-process CKEditor's files? CKEditor already appends a version-specific query parameter to all assets it requests, at least I think it does.

See e.g. here: https://cdn.ckeditor.com/4.16.1/full/ckeditor.js
![image](https://user-images.githubusercontent.com/2627/123600485-02df1380-d7f7-11eb-8f61-bfc80636043b.png)

All asset URLs look like this with 4.16.1: https://cdn.ckeditor.com/4.16.1/full/config.js?t=L4KA

**Comment by TZanke** [comment]
The version-specific query parameter was broken for plugins, but it is resolved now.
https://github.com/ckeditor/ckeditor4/issues/4761

Update is included in #705

Maybe `ManifestStaticFilesStorage` should skip ckeditor files at all, because it is handling its own cache parameters now. I will come back and investigate further if there is time to do so.

**Comment by matthiask** [comment]
I'm going to close this, hoping that everything works as it's supposed to.

**Comment by daandeheij** [comment]
My apologies for commenting on a closed issue; as I have not seen the solution to this issue anywhere online, I thought I would post the solution here in case that may help someone.

The problem indeed lies with CKEditor not being able to (lazily) load resource files. With `Manifest(Compressed)StaticFilesStorage`, loading `ckeditor<hash>.js` works just fine, but it doesn't load the other resources causing it to crash. This behavior is [mentioned](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_basepath.html) in the CKEditor 4 docs. 

One solution, as mentioned here, could be to exclude CKEditor from the manifest, but there is no straightforward way to do so in Django. Another approach is to use `django-compressor`, which will yield similar results but which does make it easy to include/exclude certain static files.

The true solution, as [mentioned](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_basepath.html#solution-ckeditor_basepath) on the same CKEditor 4 docs page, is to specify `CKEDITOR_BASEPATH` in the template in which you are trying to use CKEditor. Note that this `var` needs to be set **before** you load CKEditor JS files. For example:

```html
<head>
..
--various stuff--
..
<script>
    var CKEDITOR_BASEPATH = "{% static '/ckeditor/ckeditor/' %}";
</script>
</head>
<body>
....
  <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
</body>
```

**Comment by matthiask** [comment]
Yes, thanks. That's the reason why `ckeditor-init.js` does set the variable here:
https://github.com/django-ckeditor/django-ckeditor/blob/7a9716fae92121ad1c614778b1ab52e8f2a0d0e9/ckeditor/static/ckeditor/ckeditor-init.js#L4-L6
