### ISSUE TITLE
CKEditor giving http 500 in production in heroku

### ISSUE THREAD

**Issue by ShyamSundhar1411** [django-ckeditor/django-ckeditor#678]
I had deployed a website yesterday using ckeditor but when I try to upload any image from the computer using ckeditor and send it to server it gives HTTP 500 and in console some ckeditor internal server error with 500. My static folders are aligned properly. But nothing seems to work

**Comment by Inayat-Ullah-Khan** [comment]
I have the same issue, need help!

![ckeditor-500](https://user-images.githubusercontent.com/47157614/141247203-d38472f9-47c7-4e48-91ec-f58753379bd5.png)

**Comment by some1ataplace** [comment]
Please share your code/config files. 

1. Make sure you have properly configured your Heroku environment variables to allow file uploads. You may need to set the "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", and "AWS_STORAGE_BUCKET_NAME" environment variables to enable file uploads to an S3 bucket.

2. Verify that your S3 bucket is properly configured to allow file uploads from your Heroku app. You may need to set up a CORS configuration to allow cross-origin requests from your Heroku app.

3. Check that your Django settings file is properly configured to use the S3 storage backend for file uploads. You can use the "storages" package to configure your Django app to use S3 storage.

4. Ensure that your CKEditor configuration is set up to use the correct upload URL for image uploads. You can check the "filebrowserUploadUrl" setting in your CKEditor configuration to see if it is pointing to the correct URL.
