### ISSUE TITLE
CKEditor image upload doesn't work, server responses: Forbidden (CSRF token missing or incorrect.)

### ISSUE THREAD

**Issue by jdbit** [django-ckeditor/django-ckeditor#680]
Hi,
I can't make image uploading work, no matter I'm trying to drag&drop an image or use the image upload button from the toolbar, I get a 403 error:
```
Forbidden (CSRF token missing or incorrect.): /ckeditor/upload/&responseType=json
[23/Aug/2021 15:42:57] "POST /ckeditor/upload/&responseType=json HTTP/1.1" 403 8900
```
Not sure what's wrong with the CSRF token. Any ideas on how to troubleshoot the issue? Thanks!

**Comment by hadpro24** [comment]
Hi guys are finde solution for this ?

**Comment by hadpro24** [comment]
I think : CSRF TOKEN NAME is incorrect named : I found this : `ckCsrfToken`

**Comment by matthiask** [comment]
The default CSRF upload URL is exempted from CSRF protection it seems:
https://github.com/django-ckeditor/django-ckeditor/blob/50cd4aba9533c541e7d1ef5a4e67aed8c827f10c/ckeditor_uploader/views.py#L136

There's something else amiss.

**Comment by Nwafor6** [comment]
for someone from the future with this same problem, see my solution at stackoverflow [https://stackoverflow.com/a/79495571/17830037](https://stackoverflow.com/a/79495571/17830037)
