### ISSUE TITLE
How to set creating thumbnail of uploaded images by default

### ISSUE THREAD

**Issue by ptbang** [django-ckeditor/django-ckeditor#682]
In settings.py I have CKEDITOR_IMAGE_BACKEND = 'pillow' but a thumbnail have not been created automatically.
In docs v.6.1.0:

> Set CKEDITOR_IMAGE_BACKEND to one of the supported backends to enable thumbnails in ckeditor gallery. By default no thumbnails are created and full size images are used as preview. Supported backends:
pillow: Uses Pillow

How should I do it?
Thanks!

**Comment by some1ataplace** [comment]
If you have set "CKEDITOR_IMAGE_BACKEND" to "pillow" in your Django settings file, but thumbnails are not being created automatically in CKEditor gallery, there are a few things you can check:

1. Make sure that you have the "Pillow" package installed in your Django environment. You can install it using pip: "pip install Pillow".

2. Verify that your CKEditor configuration is set up to use the "Image" plugin and that the "image_previewText" setting is set to "true". This will enable image previews in the CKEditor gallery.

3. Check that your CKEditor configuration is set up to use the correct URL for thumbnail generation. You can check the "filebrowserImageThumbWidth" and "filebrowserImageThumbHeight" settings in your CKEditor configuration to see if they are set to the correct values.

4. Ensure that your CKEditor configuration is set up to use the correct image upload URL. You can check the "filebrowserUploadUrl" setting in your CKEditor configuration to see if it is pointing to the correct URL.

```
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = 'pillow'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['Image', 'Link', 'Unlink'],
            ['NumberedList', 'BulletedList', 'Blockquote'],
            ['RemoveFormat', 'Source']
        ],
        'extraPlugins': 'image2',
        'image_previewText': True,
        'filebrowserImageThumbWidth': 300,
        'filebrowserImageThumbHeight': 300,
        'filebrowserUploadUrl': '/ckeditor/upload/',
    }
}
```

# urls.py

```
from django.conf.urls import url
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    # ...
    url(r'^ckeditor/upload/', ckeditor_views.upload, name='ckeditor_upload'),
    url(r'^ckeditor/browse/', ckeditor_views.browse, name='ckeditor_browse'),
    # ...
]
```

This configuration sets the "CKEDITOR_IMAGE_BACKEND" to "pillow" to enable thumbnail generation. It also includes settings for the CKEditor toolbar, image preview, thumbnail size, and upload URL.
