### ISSUE TITLE
CKEditor integration with Cloudinary Storage, browse server not working (No images found)

### ISSUE THREAD

**Issue by elbination** [django-ckeditor/django-ckeditor#683]
I've setup these configs for ckeditor_uploader:
```
MEDIA_URL = '/fintech/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
CKEDITOR_UPLOAD_PATH = 'media/'
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_RESTRICT_BY_USER = False
CKEDITOR_BROWSE_SHOW_DIRS = True
```

Images upload worked well, but Browse Server always shows **No images found. Upload images using the 'Image Button' dialog's 'Upload' tab.**
It's seem CKEDITOR is not pointing to cloudinary storage?
What should I do?

**Comment by elbination** [comment]
Anyone can help after 1 year 🍡

**Comment by sabbir2609** [comment]
same problem
