### ISSUE TITLE
Return 403 forbidden for config.js on digitalocean space

### ISSUE THREAD

**Issue by arycloud** [django-ckeditor/django-ckeditor#684]
I have deployed my Django project using Docker-compose, nginx and DigitalOcean space.

Here's my `settings.py`:
```
INSTALLED_APPS = [
    'storages',
    'ckeditor',
    'ckeditor_uploader',
]

CKEDITOR_BASEPATH = f"{STATIC_URL}/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = 'blog_images/'
CKEDITOR_IMAGE_BACKEND = "pillow"
AWS_QUERYSTRING_AUTH = False
CKEDITOR_JQUERY_URL = 'http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
        'extraPlugins': ','.join(['codesnippet']),
        "removePlugins": "stylesheetparser",
    }
}
```

All of the static files are loading correctly except the following three files (These files return 403 forbidden):

- `/ckeditor/ckeditor/lang/en.js`
- `ckeditor/ckeditor/skins/moono-lisa/editor.css`
- `ckeditor/ckeditor/config.js`

At the end of File PATH for each of these files, there's a parameter as: `?t=L4KA` attached.

What might be wrong?

**Comment by matthiask** [comment]
You should ensure that CKEditor's files are not protected respectively that serving them does not require any form of authentication. They do not contain any secrets anyway.
