### ISSUE TITLE
HTTP error occurred during file upload (404: File not found). when i applied in your solution i got a  new error

### ISSUE THREAD

**Issue by sarangkkl** [django-ckeditor/django-ckeditor#685]
![image](https://user-images.githubusercontent.com/72507795/134104112-2e47fdbd-9b44-4e13-b533-5144fe8d7a39.png)

when  i made the changes as it was suggested in project urls remove something and add something i ran out some new error

**Comment by matthiask** [comment]
Thanks for the report. That's not very specific. You should probably check the devtools' network panel, maybe you find the reason there.
