### ISSUE TITLE
Wrong direction

### ISSUE THREAD

**Issue by nimaes80** [django-ckeditor/django-ckeditor#688]
When Change language to none LTR languages,  `code` , `pre` & `embeb` directions change to RTL  and we cant change it!
We dont need change code block directions just `p` tags and `div` tags and `input` tag dirctions should be change nor whole input 

Its better to set directions to auto in `html` tag wich `code` and other elements are inside it so we change direction by our self.

**Comment by matthiask** [comment]
Are you sure that this is specific to django-ckeditor? This sounds like an issue for CKEditor itself.

**Comment by nimaes80** [comment]
Honestly, I do not know if the problem is exactly with ckeditor or django-ckeditor, but it will not be corrected in any way. Even if we give an important style, it will not be registered with the style!
