### ISSUE TITLE
Cross origin request blocked for http://svc.webspellchecker.net/spellcheck31/script/ssrv.cgi not working with Firefox 93.0

### ISSUE THREAD

**Issue by devanghingu** [django-ckeditor/django-ckeditor#689]
some days ago, i integrated this plugin with my Django admin panel. everything works fine but **scayt spelling** checker is not working in my firefox.
![image](https://user-images.githubusercontent.com/43535635/140718900-09852d79-d002-4e8d-9d7b-4cef13297a4c.png)
 
Therefore i investigated and found that i have to configure  [django-cors-headers](https://github.com/adamchainz/django-cors-headers) with my application. **I did. still it's not working for my web application**

And below are my configuration to allow cross origin request from django application.
```
INSTALLED_APPS = [
    ' . . .'
    'ckeditor',
    'corsheaders'
    ' . . .'
]
MIDDLEWARE = [
    ". . .",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    " . . .",
]
CORS_ALLOW_ALL_ORIGINS = True
```

**Comment by matthiask** [comment]
CORS headers seem to be missing on the webspellchecker host, not on your end.

**Comment by devanghingu** [comment]
Thanks for an update!
