### ISSUE TITLE
Adding languages to codesnippet

### ISSUE THREAD

**Issue by uprightcarrion** [django-ckeditor/django-ckeditor#693]
I'm trying to add a language to the code_snippet.   I'm using highlight.js so I'm trying to add it to the dropdown so it will populate the class appropriately.

According to the ckedior docs they show this
![image](https://user-images.githubusercontent.com/7152455/145632773-d153e89b-af80-4bf7-bf53-08a02796bc90.png)

I've tried this and a few other permutations
![image](https://user-images.githubusercontent.com/7152455/145632996-8d22c577-f788-4d35-8f8c-061e30d0998e.png)

The result is always a list of the characters I enter.

 Any pointers would be appreciated.

**Comment by some1ataplace** [comment]
```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'codeSnippet_languages': {
            'html': 'HTML',
            'css': 'CSS',
            'javascript': 'JavaScript',
            'python': 'Python',
            'php': 'PHP'
        },
        # other config options...
    }
}
```
