### ISSUE TITLE
As a user I want to customize the ckeditor wdiget template by pointing a template_name name attribute to a  custom template

### ISSUE THREAD

**Issue by elmq0022** [django-ckeditor/django-ckeditor#697]
As shown below the ckeditor/widget template is **hard-coded** in the render method.  
 
```python
def render(self, name, value, attrs=None, renderer=None):
    ...
      return mark_safe(
          renderer.render(
              "ckeditor/widget.html",
              {
                  "final_attrs": flatatt(final_attrs),
                  "value": conditional_escape(force_str(value)),
                  "id": final_attrs["id"],
                  "config": json_encode(self.config),
                  "external_plugin_resources": json_encode(external_plugin_resources),
              },
          )
      )
```

I believe this should really be a set on a template_name attribute for the class.  This would provide a much easier method to override the widget's template for custom layouts.  

I understand django provides a way to override the widget template for all instance, but this does not help for one off items.  

Here's an example of what I would like to be able to do:

```python
class CustomCKEditorWidget(CKEditorWidget):
    template_name = "templates/my_custom_template.html"
```

There shouldn't be much work for this change.  If you're open to this, let me know and I can raise a PR.

**Comment by matthiask** [comment]
Sure, makes sense. You should even be able to reuse the `def render` method of `Textarea` resp. of the `Widget` base class.
