### ISSUE TITLE
Wrong URL on browse image with defaultStorage

### ISSUE THREAD

**Issue by Mte90** [django-ckeditor/django-ckeditor#703]
![immagine](https://user-images.githubusercontent.com/403283/159981205-98902f3b-13b0-46dc-b890-8be7854a34ef.png)

As you can see is not generating the right URL...

```
MEDIA_URL = "/uploads/"
MEDIA_ROOT = BASE_DIR / "uploads"
CKEDITOR_UPLOAD_PATH = BASE_DIR / "uploads"
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_IMAGE_BACKEND = 'pillow'
```

My tests say that the issue is there https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/utils.py#L84

**Comment by matthiask** [comment]
I have never used the uploader but have you tried NOT prepending `BASE_DIR` to the upload path, like here? https://github.com/django-ckeditor/django-ckeditor/blob/50cd4aba9533c541e7d1ef5a4e67aed8c827f10c/ckeditor_demo/settings.py#L120

**Comment by Mte90** [comment]
Thanks for the hint!

Changed to:
```
CKEDITOR_UPLOAD_PATH = "./"
```

I am not sure if it is mentioned in the readme!

**Comment by matthiask** [comment]
I'm not sure either :-)

Good to hear it worked!

**Comment by PrantaChakraborty** [comment]
@matthiask  @Mte90 thanks both of you. I also faced same issue on production. Now it works perfecly.

**Comment by matthiask** [comment]
Great! Let's close this issue then.
