### ISSUE TITLE
Adopt CKEditor 4.18.0

### ISSUE THREAD

**Issue by TZanke** [django-ckeditor/django-ckeditor#704]
I reported an issue to CKEditor which is fixed in [4.17.2](https://ckeditor.com/cke4/release/CKEditor-4.17.2).

After reading the rest of the CKEditor Changelog [4.18.0](https://ckeditor.com/cke4/release/CKEditor-4.18.0) brings two fixes for vulnerabilities.

I would like two fix them all upgrading django-ckeditor. ;)

**Comment by matthiask** [comment]
Sure! Do you want to submit a pull request? You should download the full CKEditor preset, unzip it in the appropriate folder and commit everything (probably remove the samples folder first)
