### ISSUE TITLE
RichTextUploadingField is not showing up

### ISSUE THREAD

**Issue by omidshojaee** [django-ckeditor/django-ckeditor#716]
After the recent update (around 4 days ago), the RichTextUploadingField is not showing up.

The ```RichTextField``` works just fine, but with the exact same settings, just changing the model's field to ```RichTextUploadingField```, it doesn't show up. **Instead, Django's standard TextField appears.**

I've tested this on both Linux and Windows.

I see no error in browser's developer console.

**Comment by matthiask** [comment]
Does it work with `django-ckeditor==6.4.0`?

**Comment by omidshojaee** [comment]
Good point. Thanks  Will update this shortly.

**Comment by kravciuk** [comment]
Same issue.   RichTextField work fine, but RichTextUploadingField show only basic textarea.   In browser debug console - no errors. 

django-ckeditor==6.3.2
Django==4.0.4

**Comment by omidshojaee** [comment]
It works fine with 6.4.0. Have you updated the package?

**Comment by kravciuk** [comment]
Yep, work fine after update to latest 6.4.0

**Comment by matthiask** [comment]
Great, thanks.
