### ISSUE TITLE
pip install django-ckeditor==6.4.0 not working

### ISSUE THREAD

**Issue by AliyAcho** [django-ckeditor/django-ckeditor#718]
pip install django-ckeditor (latest version of django-ckeditor for pip=6.3.2) doesn't work for RichTextUploadingField. I installed another version (6.0.0) and everything worked. Please add pip version of django-ckeditor 6.4.0 if possible to avoid such errors in the future
![Снимок экрана от 2022-05-02 11-32-00](https://user-images.githubusercontent.com/73710087/166206916-9b58ecc5-fd46-4448-884e-370bba0ead79.png)
.

**Comment by matthiask** [comment]
django-ckeditor 6.4 is definitely available on PyPI https://pypi.org/project/django-ckeditor/#history

You're probably using an unsupported version of Python. django-ckeditor 6.4 requires Python 3.8 or better. https://github.com/django-ckeditor/django-ckeditor/blob/master/CHANGELOG.rst#640
