### ISSUE TITLE
Error fetching command 'generateckeditorthumbnails' with django 4.0.x

### ISSUE THREAD

**Issue by GitRon** [django-ckeditor/django-ckeditor#721]
Hi there!

I just realised I get this error with django 4.0.x:

> Error fetching command 'generateckeditorthumbnails': cannot import name 'registry' from 'ckeditor_uploader.backends' (C:\Users\ronny\.virtualenvs\backend-6qNpIncx\lib\site-packages\ckeditor_uploader\backends\__init__.py)
Command 'generateckeditorthumbnails' skipped

Do you already know about this problem?

Best  
Ronny

**Comment by matthiask** [comment]
Hi @GitRon 

Thanks for the report. That's a new one. It would probably be sufficient to replace the `registry` import with importing `get_backend`, and replacing `backend = registry.get_backend()` with `backend = get_backend()` inside the `handle` function.

Do you want to check if this works and submit a pull request if it does?

**Comment by GitRon** [comment]
Hi @matthiask - unfortunately I am not really using this package. I just supported another team and stumbled over this error. 😔

**Comment by matthiask** [comment]
@GitRon Alright, thanks!

**Comment by GitRon** [comment]
@matthiask Awesome! You are the best! Just post here, when the new version is out so others know when they can do the update ❤️

**Comment by matthiask** [comment]
Voilà https://pypi.org/project/django-ckeditor/#history :)
