### ISSUE TITLE
Automatic enclosing of all written content within <p></p>

### ISSUE THREAD

**Issue by ghost** [django-ckeditor/django-ckeditor#722]
Is there a possibility to turn off the automatic enclosing of all written content within <p></p> in ckeditor as I added the span tag but when I write something its wrapped with p tag
```
<p><span>Op zoek naar manieren om je bedrijfsprocessen te</span></p>

```
But I just wants to add span tag

**Comment by ash-0001** [comment]
You need to do that separately as there is no other way till now. As by viewing things in source file mode.

**Comment by some1ataplace** [comment]
Yes, it is possible to turn off the automatic enclosing of all written content within a specific tag in django-ckeditor. To do this, you need to modify the config.js file in your CKEditor installation. 

1. First, locate the config.js file in your CKEditor installation directory.

2. Open the file and add the following line of code:

`config.allowedContent = 'span';`


3. This will allow only the `<span>` tag to be used in the editor without being automatically enclosed in a <p> tag.

4. Save the file and restart your server to apply the changes.

5. Now, when you use the CKEditor in your Django project, you can use the `<span>` tag directly without being automatically enclosed in a `<p>` tag.

**Comment by matthiask** [comment]
This is handled / caused by CKEditor, not django-ckeditor. If this behavior seems incorrect you have to request a change to CKEditor itself. Thanks!
