### ISSUE TITLE
data-external-plugin-resources parse error on 6.4.x

### ISSUE THREAD

**Issue by peterjochum** [django-ckeditor/django-ckeditor#725]
After upgrading to 6.4.2 the editor does not show in Django the django admin site - the reason is a JSON parse error on the empty attribute data-external-plugin-resources.

The textarea tag is output like this:
```html
<textarea data-config="" data-external-plugin-resources="" data-id="" data-processed="1" data-type="ckeditortype"></textarea>
```

ckeditor-init.js:36

```javascript
var ext = JSON.parse(t.getAttribute("data-external-plugin-resources"))
```
causes: Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
data-external-plugin-resources should be an empty list "[]" and not "".

- Error persists on removing CKEDITOR_CONFIGS from my configuration.
- Reverting back to 6.3.2 solves the issue.

**Comment by matthiask** [comment]
Something is really wrong here. According to my reading of the code `widget.external_plugin_resources` should always fall back to the empty list (in `ckeditor/widgets.py`). `data-config` being empty looks really wrong as well. It seems as if the widget didn't actually get a chance of filling in the widget template context?

**Comment by peterjochum** [comment]
I would suggest waiting for confirmation by another person. Maybe it is a just a configuration error on my end. 

Two other things to note
- Django version is at 3.2.15
- The error also occurred in a different browser (wanted to rule out any extension interfering with markup)

**Comment by some1ataplace** [comment]
Modify the CKEditor widget template to ensure that the data-external-plugin-resources attribute is always set to an empty list. You can achieve this by modifying the widget/ckeditor_widget.html template as follows:

Replace this line:

`<textarea id="{{ id }}" name="{{ name }}"{% include "widget/input_attrs.html" %}>{% if value %}{{ value|safe }}{% endif %}</textarea>`


With this:

```
{% include "ckeditor/ckeditor_config.html" %}
<textarea data-external-plugin-resources="[]" id="{{ id }}" name="{{ name }}"{% include "ckeditor/ckeditor_attrs.html" %}>{{ value|safe }}</textarea>
{{ media }}
```


This modification to the template will ensure that the data-external-plugin-resources attribute is always present, even if it's empty, which should resolve the JSON parse error in ckeditor-init.js

**Comment by peterjochum** [comment]
Thanks so much - through your comment I discovered the template `ckeditor/widget.html` was already overridden in an application and out of date (2020). The problem in the template was the location of context data which seems to have changed after 6.3.2:

**Old**: `data-external-plugin-resources="{{ external_plugin_resources }}"`
**New**:  `data-external-plugin-resources="{{ widget.external_plugin_resources }}"`

Removing/upgrading the custom template fixed my problem.
