### ISSUE TITLE
Ckeditor script fails to render after updating to Django 4.1

### ISSUE THREAD

**Issue by aminvsf** [django-ckeditor/django-ckeditor#727]
Hi, i'm Amin.

I ran into a problem and I was wondering if anyone can help me with it.
After updating my django from 4.0.6 to 4.1, Ckeditor script tag fails to be rendered and displays a bunch of text on the django admin page, as illustrated below.

![Screenshot 2022-08-14 195508](https://user-images.githubusercontent.com/75808738/184543913-a7642219-0c21-42da-a0fc-23507aef6bb3.png)

![Screenshot 2022-08-14 195551](https://user-images.githubusercontent.com/75808738/184543914-69f6f6e4-da88-4ea1-89ec-1ff4d2db4363.png)

Is there a problem with my Ckeditor's configuration or is it related to the package itself.

Thanks in advance.

**Comment by matthiask** [comment]
You should update your version of django-js-asset to 2.0 (or better) using `pip install -U django-js-asset`. It's a dependency of django-ckeditor and it seems that your relatively old version doesn't support Django 4.1 yet.
