### ISSUE TITLE
Need plugin for the citation

### ISSUE THREAD

**Issue by mszahan** [django-ckeditor/django-ckeditor#729]
Need a reference plugin tool that will add the numbered citations. Currently found no plugin for adding a reference in the text. Please add any referencing tool that will allow citing journals, books, and website links.

**Comment by some1ataplace** [comment]
1. In your Django project's models.py file, import the CKEditorPluginBase and CKEditorUploadModel classes from ckeditor_uploader.fields:

`from ckeditor_uploader.fields import CKEditorPluginBase, CKEditorUploadModel`


2.  Create a new model that inherits from CKEditorUploadModel and add a field that uses the CKEditorPluginBase class:

```
class MyModel(CKEditorUploadModel):
    content = RichTextUploadingField(config_name='citation')

    class Meta:
        verbose_name = 'My Model'
        verbose_name_plural = 'My Models'
```


3. In your Django project's settings.py file, add the following CKEditor configuration:

```
CKEDITOR_CONFIGS = {
    'citation': {
        'extraPlugins': 'citation',
        'toolbar': 'Citation',
        'citation_style': 'apa',
        'citation_show_url': True,
    }
}

```

4. In your Django project's admin.py file, import the CKEditorWidget and use it in your form:

```
from ckeditor.widgets import CKEditorWidget
from .models import MyModel

class MyModelAdminForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget(config_name='citation'))

    class Meta:
        model = MyModel
        fields = '__all__'

class MyModelAdmin(admin.ModelAdmin):
    form = MyModelAdminForm

admin.site.register(MyModel, MyModelAdmin)
```

**Comment by matthiask** [comment]
We're bundling the CKEditor 4 full preset. If this preset doesn't include the plugin you want you have to add it yourself.
