### ISSUE TITLE
Override CKEditorWidget template_name

### ISSUE THREAD

**Issue by bbonfoey** [django-ckeditor/django-ckeditor#730]
I would like to override the template_name in the CKEditorWidget.  If you place the template_name in the __init__ function and leave the "ckeditor/widget.html" as the default we would be able to override the template.  

The reason I would like to be able to override is the style is set to remove the style="display: inline-block;" and customize it

**Comment by matthiask** [comment]
Sure, please submit a pull request!

**Comment by matthiask** [comment]
Fixed by #731
