### ISSUE TITLE
ReadTheDocs is lagging behind compared with PyPI

### ISSUE THREAD

**Issue by NFSpeedy** [django-ckeditor/django-ckeditor#733]
Guys, your RTD is way back compared with PyPI. Maybe the CI is failing?

**Comment by matthiask** [comment]
Thanks, seems like it. I don't have the necessary permissions to configure the webhook. 

@riklaunim Maybe you have access to the repository settings or organization settings?

**Comment by riklaunim** [comment]
@matthiask what's needed?

**Comment by matthiask** [comment]
@riklaunim GitHub should send a webhook to the URL mentioned here: https://readthedocs.org/dashboard/django-ckeditor/integrations/218339/ when pushes etc. happen.

This can be configured in the repository settings, but I do not have access.

**Comment by matthiask** [comment]
Ah wait, the webhook URL is https://readthedocs.org/api/v2/webhook/django-ckeditor/218339/

I'm not sure if you even have access to the django-ckeditor RTD project.

**Comment by riklaunim** [comment]
@matthiask you should have access now. I've added the hook at https://github.com/django-ckeditor/django-ckeditor/settings/hooks

**Comment by matthiask** [comment]
Thank you!
