### ISSUE TITLE
Youtube plugin not working

### ISSUE THREAD

**Issue by BhuwanPandey** [django-ckeditor/django-ckeditor#736]
I had install youtube plugin by unziping inside ckeditor plugin directory. I am able to import youtube video on ckeditor successfully but after saving that objects, video wasnot display on ckeditor.

**Comment by some1ataplace** [comment]
1. Install the django-ckeditor package and its dependencies, including the ckeditor package.

2. Add ckeditor to your INSTALLED_APPS setting in your Django project's settings.py file.

3. In your Django project's urls.py file, add the following URL pattern:

`url(r'^ckeditor/', include('ckeditor.urls'))`


4. In your Django project's models.py file, import the CKEditorPluginBase and CKEditorUploadModel classes from ckeditor_uploader.fields:
`
from ckeditor_uploader.fields import CKEditorPluginBase, CKEditorUploadModel`


5. Create a new model that inherits from CKEditorUploadModel and add a field that uses the CKEditorPluginBase class:

```
class MyModel(CKEditorUploadModel):
    content = RichTextUploadingField(config_name='youtube')

    class Meta:
        verbose_name = 'My Model'
        verbose_name_plural = 'My Models'

```

6. In your Django project's settings.py file, add the following CKEditor configuration:

```
CKEDITOR_CONFIGS = {
    'youtube': {
        'extraPlugins': 'youtube',
        'toolbar': 'Youtube',
        'youtube_responsive': True,
        'youtube_controls': True,
        'youtube_privacy': True,
    }
}
```
OR

```
   CKEDITOR_CONFIGS = {
       'default': {
           'toolbar': 'full',
           'height': 300,
           'width': 800,
           'extraPlugins': ','.join([
               'youtube', # Add the youtube plugin
           ]),
       },
   }
```

7. In your Django project's admin.py file, import the CKEditorWidget and use it in your form:

```
from ckeditor.widgets import CKEditorWidget
from .models import MyModel

class MyModelAdminForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget(config_name='youtube'))

    class Meta:
        model = MyModel
        fields = '__all__'

class MyModelAdmin(admin.ModelAdmin):
    form = MyModelAdminForm

admin.site.register(MyModel, MyModelAdmin)
```


```
{% load static %}
{{ form.media }}
{{ form.textfield|ckeditor:"toolbar_Full,['Youtube']"|safe }}
```

This code will add the CKEditor widget to your template, with the 'Youtube' button enabled in the toolbar. Note that we are using the ckeditor filter to render the CKEditor widget, and we have passed the 'Youtube' button to the toolbar_Full configuration in the second argument of the filter.
