### ISSUE TITLE
How to make CKEditor to show tag br as <br>, not <br />?

### ISSUE THREAD

**Issue by Deimos715** [django-ckeditor/django-ckeditor#737]
Hello, can somebody tell me how to make CKEditor to show tag br as `<br>,` not `<br />?` Accordingly CKEditor 4 version documentation (https://ckeditor.com/docs/ckeditor4/latest/guide/dev_howtos_output.html) you need to add this preference to config.js:

`CKEDITOR.on( 'instanceReady', function( ev ) {
    ev.editor.dataProcessor.writer.selfClosingEnd = '>';
});`

But this tag becomes closed by `/>` anyway, this is not a bug. I use Django CKEditor 6.3.0.

Current setting
`CKEDITOR.on( 'instanceReady', function( ev ) {
    ev.editor.dataProcessor.writer.selfClosingEnd = '>';
});`
doesn't execute, I have to remove slashes every time when editing data model.

**Comment by some1ataplace** [comment]
1. Locate the config.js file in the CKEditor installation directory
2. Add the following line at the end of the file:

`CKEDITOR.dtd.$removeEmpty['br'] = false;`

OR
```

// Get the CKEditor configuration object
var config = CKEDITOR.config;

// Check if the $removeEmpty property exists in the DTD (Document Type Definition)
if (config.dtd.$removeEmpty) {
  // Set the $removeEmpty property for the <br> tag to false
  config.dtd.$removeEmpty['br'] = false;
}
```

This code retrieves the CKEditor config object and checks if the $removeEmpty property exists in the Document Type Definition (DTD). If it exists, the code sets the $removeEmpty property for the <br> tag to false, effectively disabling the self-closing tag behavior. Note that this code assumes that the CKEditor library has already been loaded on the page.

**Comment by matthiask** [comment]
If the exact HTML you get is important for you you should probably post-process it, using something like beautifulsoup4, lxml or html-sanitizer. Clients will do what they want.
