### ISSUE TITLE
Adapt to use with dark Django theme

### ISSUE THREAD

**Issue by AntonDatsik** [django-ckeditor/django-ckeditor#738]
I'm using dark theme in my Django admin and can't see black text on some elements...
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/11877527/214054142-86222c38-f087-425a-a54c-1c37b18af8e3.png">

**Comment by matthiask** [comment]
The basic problem is that the bundled CKEditor 4 full preset doesn't support dark mode.

We could add some hacks in a CSS file of our own which would be added to the browser. I'd happily merge a pull request and roll a new release containing these changes.

**Comment by some1ataplace** [comment]
Duplicate of https://github.com/django-ckeditor/django-ckeditor/issues/670

**Comment by matthiask** [comment]
Duplicate of #670
