### ISSUE TITLE
Mobile text selection is difficult

### ISSUE THREAD

**Issue by zhenda-hub** [django-ckeditor/django-ckeditor#750]
I want to select the text in the mobile editor, edit it, and find that it is almost impossible to select the text I want, because it will automatically pop up a drop-down box, but I have not selected the text I want. How do I prevent this editor from automatically popping up a drop-down box on the mobile terminal

**Comment by matthiask** [comment]
That's probably a CKEditor 4 problem. Maybe you have more luck with CKEditor 5 (see https://github.com/django-ckeditor/django-ckeditor/issues/482 for the discussion around it)
