### ISSUE TITLE
URLS of images uploaded via `RichTextUploadingField` before migration to S3 not updated after migration

### ISSUE THREAD

**Issue by 2qxtx** [django-ckeditor/django-ckeditor#753]
I recently migrated my media assets to AWS S3 and later discovered that the URLS of inline images uploaded via Django CKEditor's `RichTextUploadingField` appear to be hardcoded. After the migration, I can upload and view images without a problem. However, all images uploaded prior to the migration return a 404 not found error.

When I query the value of a problematic `RichTextUploadingField` field in the database, I get something like this (note that the first image was uploaded before the migration, and the second image was uploaded after the migration):

`<p><img alt="Image uploaded before migration" src="/media/uploads/image.jpg" /><img alt="Image uploaded after migration" src="https://my-bucket.s3.amazonaws.com/media/public/uploads/image.jpg" /></p>`

Is this normal behavior? One solution I can think of is to loop over the values of all `RichTextUploadingField` fields and manually update the URLS, but I'm wondering if there's a built-in solution for this that I might have overlooked.

I'm using Django CKEditor 6.7.0, Django 4.2.6, and Django Storages 1.14.2 with support for S3.

**Comment by matthiask** [comment]
Yes that's expected, and yes, updating the HTML yourself is what you have to do. That's the downside of using HTML instead of more structured data formats. 

I recommend using beautifulsoup4 or something for the transform.
