### ISSUE TITLE
Cannot change the UI language

### ISSUE THREAD

**Issue by omidshojaee** [django-ckeditor/django-ckeditor#755]
This is my config:

```
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar': 'full',
        'language': 'ru'
    }
}
```

The UI is still in English.

**Comment by matthiask** [comment]
That's to be expected. The language is dynamically set based upon the currently active Django language, see https://github.com/django-ckeditor/django-ckeditor/blob/6c925441802bc39e1e3563155d9d4432d5527622/ckeditor/widgets.py#L122-L128

**Comment by omidshojaee** [comment]
Thank you.
