### ISSUE TITLE
Loading SimpleUploadAdapter from generated bundle

### ISSUE THREAD

**Issue by alexandremjacques** [django-ckeditor/django-ckeditor#759]
Hi.

I followed the instructions on using the online builder (https://ckeditor.com/docs/ckeditor5/latest/installation/plugins/installing-plugins.html) to avoid having to `npm install` the adapter.

I created a bundle that includes the plugin but I'm unable to use it since the editor fails initializing as it doesn't find the plugin: 

```
Uncaught ReferenceError: SimpleUploadAdapter is not defined
``` 

Is there anyway to use the adapter without the `npm install`?

Thanks in advance.

**Comment by matthiask** [comment]
django-ckeditor uses CKEditor 4, maybe you have more luck with https://github.com/hvlads/django-ckeditor-5 ?
