### ISSUE TITLE
"This CKEditor 4.22.1 version is not secure"

### ISSUE THREAD

**Issue by dkoenigroer** [django-ckeditor/django-ckeditor#761]
The following message appears as overlay on the text editor area. We updated to [Release 6.7.0](https://github.com/django-ckeditor/django-ckeditor/blob/main/CHANGELOG.rst#670) which integrates CKEditor 4.22.1
 
![image](https://github.com/django-ckeditor/django-ckeditor/assets/72100882/2b02bb25-53e7-4ed3-9845-3770a707c17a)

> This CKEditor 4.22.1 version is not secure. Consider [upgrading to the latest one](https://ckeditor.com/ckeditor-4-support/), 4.24.0-lts.

Is djago-ckeditor upgradeable to CKEditor 4.24.0-lts?

**Comment by matthiask** [comment]
https://ckeditor.com/ckeditor-4/download/

ckeditor 4 LTS is a paid product, so we cannot bundle it in django-ckeditor unfortunately, or that's my understanding.

**Comment by dkoenigroer** [comment]
Oh, i didn't do further investigations. Ok, that argument just closes the ticket :(

**Comment by Pietro395** [comment]
We have the same problem, is there nothing that can be done?

**Comment by matthiask** [comment]
I have downgraded a client's project to `django-ckeditor=6.6.1` for now. I'm afraid I don't have a better option right now.

**Comment by Pietro395** [comment]
> I have downgraded a client's project to `django-ckeditor=6.6.1` for now. I'm afraid I don't have a better option right now.

Thank you, we too did the same while waiting to find a viable alternative

**Comment by dkoenigroer** [comment]
For now we hide the box but we will examin the possibility to change all RichTextfields to [django-ckeditor-5](https://github.com/hvlads/django-ckeditor-5)


`.cms-admin-modal {
  .cke_notifications_area:has(.cke_notification_warning) {
    display: none;
  }
}
`

**Comment by elinaldosoft** [comment]
For me, it worked like this. Add in `admin/base.html`

```
    <style>
        .cke_notifications_area { display: none; }
    </style>
```

**Comment by dbreen** [comment]
Another solution I discovered is in your Django settings, add or modify this setting:

```
CKEDITOR_CONFIGS = {
    'default': {
        'versionCheck': False
    }
}
```

**Comment by bartels** [comment]
`'versionCheck': False` should probably be made the default

**Comment by matthiask** [comment]
Oh nice, the `versionCheck` thing is great. 

I think it's not that useful to show this warning ot users when we're bundling a CKEditor version in django-ckeditor itself.

OTOH I understand why the CKEditor folks did this. Also, running software which isn't patched anymore is certainly a risk.

I think we should add the `versionCheck: False` but also add a system check warning which tells developers that they should think about the consequences of using non-LTS CKEditor 4 in production environments 
https://docs.djangoproject.com/en/4.2/topics/checks/

**Comment by matthiask** [comment]
https://ckeditor.com/cke4/release/CKEditor-4.24.0-LTS

CKEditor 4.22.1 really isn't secure. (It always depends on the threat model of course.)

I have implemented the change mentioned above. If anyone wants to propose a different wording or maybe a different solution, please feel free! I don't think I'm willing to include the LTS package in django-ckeditor though since I'm quite sure that this would violate the spirit of the licensing change, and being an open source developer and maintainer myself I'd rather not disregard the licensing choices of others.

**Comment by cctslo** [comment]
I edited: [ config.js ]
With the following: 

CKEDITOR.editorConfig = function( config ) {
	config.versionCheck = false;
};

**Comment by matthiask** [comment]
@cctslo django-ckeditor 6.7.1 already sets `versionCheck = False ` by default.

**Comment by cctslo** [comment]
@matthiask This was in response to the general ckeditor error - 

["This CKEditor 4.22.1 version is not secure"] 

I was leaving this incase someone else ran into that error.

**Comment by rumvir** [comment]
very nice bro!

**Comment by rumvir** [comment]
> Another solution I discovered is in your Django settings, add or modify this setting:
> 
> ```
> CKEDITOR_CONFIGS = {
>     'default': {
>         'versionCheck': False
>     }
> }
> ```

very nice bro!

**Comment by matthiask** [comment]
It's nice that y'all are posting about that, but you could also just upgrade to django-ckeditor 6.7.1 which already includes this setting.

**Comment by jyoudan1996** [comment]
I simply searched "latestVersion" in ckeditor.js and modified the condition "if(e.secure&&e.latest)" to "if(true)".

**Comment by kurtisdevv** [comment]
> I simply searched "latestVersion" in ckeditor.js and modified the condition "if(e.secure&&e.latest)" to "if(true)".

Can confirm this works, bizarre that it came up as an issue for me on a legacy site and you commented 3 hours ago - saved me some hassle so thanks :)

**Comment by bobocow123** [comment]
> Another solution I discovered is in your Django settings, add or modify this setting:
> 
> ```
> CKEDITOR_CONFIGS = {
>     'default': {
>         'versionCheck': False
>     }
> }
> ```
Hahaha, you saved my life, brother
