### ISSUE TITLE
CKEditor 4.22.1 version is not secure.

### ISSUE THREAD

**Issue by nicolochiellini** [django-ckeditor/django-ckeditor#763]
Hello
It could be a good idea upgrade to 4.24.0-lts version.
![image](https://github.com/django-ckeditor/django-ckeditor/assets/7115561/af84d0b2-5e73-495c-8d91-22a9b14e466f)

**Comment by matthiask** [comment]
Thank you!

This has been discussed in https://github.com/django-ckeditor/django-ckeditor/issues/761
