### ISSUE TITLE
Version: 6.7.1 in Django 4.2 WARNINGS: (ckeditor.W001) django-ckeditor bundles CKEditor 4.22.1 which isn't supported anmyore

### ISSUE THREAD

**Issue by ppyakovlev** [django-ckeditor/django-ckeditor#764]
Hi everybody. I have such a problem. Django-ckeditor version 6.7.1 is installed, but I get warnings in the console about using version 4.22.1 Here are the screenshots:
**pip show django-ckeditor**
<img width="522" alt="Снимок экрана 2024-02-09 в 17 36 45" src="https://github.com/django-ckeditor/django-ckeditor/assets/29551962/7d1992ed-ad1c-4df7-abb2-8adf293ed386">
**Console log:**
<img width="1264" alt="Снимок экрана 2024-02-09 в 17 37 18" src="https://github.com/django-ckeditor/django-ckeditor/assets/29551962/45f88c09-e30b-4124-a30a-4de0dc63de90">
site-packages:
<img width="279" alt="Снимок экрана 2024-02-09 в 17 38 13" src="https://github.com/django-ckeditor/django-ckeditor/assets/29551962/41d58e70-1d23-4cd5-ad65-edf557c33be3">

I do not want to prohibit the output of package errors. Can you tell me what can be done?

**Comment by buzz-buzz-Alaska** [comment]
Hello. Unfortunately, there does not appear to be any way to upgrade the version of CKEditor (to version 5) itself reliably, without major modification to Django CKEditor.

So, we will just have to wait to see if Django CKEditor upgrades. For more information, see: #761

I do understand that you would like to keep the warning message. However, if you would like to disable the message, you can add:
```
CKEDITOR_CONFIGS = {
    "default": {
        "versionCheck": False
    }
}
```
to your settings.

**Comment by niccolomineo** [comment]
> Hello. Unfortunately, there does not appear to be any way to upgrade the version of CKEditor (to version 5) itself reliably, without major modification to Django CKEditor.
> 
> So, we will just have to wait to see if Django CKEditor upgrades. For more information, see: #761
> 
> I do understand that you would like to keep the warning message. However, if you would like to disable the message, you can add:
> 
> ```
> CKEDITOR_CONFIGS = {
>     "default": {
>         "versionCheck": False
>     }
> }
> ```
> 
> to your settings.

Doesn't work, because the `w001` is raised at Django app level, whereas `versionCheck` is a widget setting.

**Comment by matthiask** [comment]
Hey

You should be able to fork the repo, push there and open a pull request here.

I'm not sure what you're proposing. As you say, `versionCheck` is a CKEditor setting. Disabling the check doesn't actually make CKEditor secure, it's just hiding the notification. I don't want to give the (completely) wrong impression that using django-ckeditor is fine, since it already contains known security issues, see for example https://ckeditor.com/cke4/release/CKEditor-4.24.0-LTS -- and it will only get worse.

I don't have a good suggestion unfortunately, I'm searching for alternatives myself. The `Warning` text points out at least one alternative though: https://raw.githubusercontent.com/django-ckeditor/django-ckeditor/main/ckeditor/apps.py

Thanks!

**Comment by niccolomineo** [comment]
> Hey
> 
> 
> 
> You should be able to fork the repo, push there and open a pull request here.
> 
> 
> 
> I'm not sure what you're proposing. As you say, `versionCheck` is a CKEditor setting. Disabling the check doesn't actually make CKEditor secure, it's just hiding the notification. I don't want to give the (completely) wrong impression that using django-ckeditor is fine, since it already contains known security issues, see for example https://ckeditor.com/cke4/release/CKEditor-4.24.0-LTS -- and it will only get worse.
> 
> 
> 
> I don't have a good suggestion unfortunately, I'm searching for alternatives myself. The `Warning` text points out at least one alternative though: https://raw.githubusercontent.com/django-ckeditor/django-ckeditor/main/ckeditor/apps.py
> 
> 
> 
> Thanks!

I am proposing making `versionCheck` a master setting for disabling any version-related prompt. Else, we can simply define a separate constant for that purpose.

**Comment by niccolomineo** [comment]
Sounds good to me.

**Comment by LexVega** [comment]
> Ah, I see, thanks for explaining.
> 
> I strongly disagree with this idea. The point of [d1cd092](https://github.com/django-ckeditor/django-ckeditor/commit/d1cd092b4fbfb0534ded7f09a219d89fea5e547f) was to nag developers, not users, since the latter cannot do anything about it but the former absolutely should do something.
> 
> If you want to silence the warning you can add `SILENCED_SYSTEM_CHECKS = ["ckeditor.W001"]` to your settings file. I wouldn't recommend it since it doesn't fix the underlying issue, which is that CKEditor 4 is dead and people should switch away from it. The open source version already has security issues, the LTS version is only expected to be around until the end of 2026 https://ckeditor.com/ckeditor-4-support/ -- that's quite soon. So, in essence, the separate constant you're proposing already exists in Django itself https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-SILENCED_SYSTEM_CHECKS

Sorry if i dumb, i read everything related to django-prose-editor and 4.24.0 LTS version, and i still not fully understand why django-ckeditor is 'basically dead'? I imagine using this at frontend part may cause problems if user insert some js in text, but what about casual admin usage? If we use django-ckeditor only for the purpose of making admin widget that allow to fill in some model's TextField. Is it still bad? Should we be worried about warning and look for alternatives? 

By the way, this warning breaks fixtures, so every time you cast `manage.py dumpdata myapp.MyModel --format=json --indent=2 > mymodel.json  `, you will get full message in file before actual fixture (at least if app is running in docker container). So at least for my case, adding `SILENCED_SYSTEM_CHECKS = ["ckeditor.W001"]` to settings file is a must. 

Thank you for sharing valuable information about current django-ckeditor and hint on hot to suppress warning, i hope it will save some time for folks out there.

**Comment by matthiask** [comment]
> Is it still bad? Should we be worried about warning and look for alternatives?

That's your decision to make. Is running software which doesn't get any updates bad? The answer is, as always, it depends. 

I definitely wouldn't use CKEditor 4 in new projects. Replacing CKEditor 4 in all of my projects will be very hard and maybe not worth it, especially because of the custom plugins some people wrote a few years back. 

> By the way, this warning breaks fixtures, so every time you cast  [...]

You should probably use `--output mymodel.json` instead of redirecting stdout. One could argue that the error messages belong on STDERR, but django-ckeditor cannot do anything about that, this would be a Django enhancement.

**Comment by LexVega** [comment]
> That's your decision to make. Is running software which doesn't get any updates bad? The answer is, as always, it depends.
> 
> I definitely wouldn't use CKEditor 4 in new projects. Replacing CKEditor 4 in all of my projects will be very hard and maybe not worth it, especially because of the custom plugins some people wrote a few years back. I certainly hope that I can leave ckeditor behind at some time in the future.

Thank you for clarification! Its just hard to understand how those security problems impact on the project overall in a narrow use case. In my project the main usage of django-ckeditor is a one line of model admin view where i override text widget for a field, and my project is new indeed, and i also not a big fan of using 'dead' libraries, but i just can't find any suitable replacement that will do the job as good as django-ckeditor does, especially when it comes to images. Non the less, you did a great job of keeping django-ckeditor alive and i am sure a lot of devs out there (not just me) appreciate it! 

> You should probably use `--output mymodel.json` instead of redirecting stdout. One could argue that the error messages belong on STDERR, but django-ckeditor cannot do anything about that, this would be a Django enhancement.

This is something that not crossed my mind, you are right and solves the problem. Very grateful :bowing_woman: !

**Comment by matthiask** [comment]
I'm going to close this issue; #761 exists and contains the history.
