### ISSUE TITLE
When click on "source" -  <p>&nbsp;</p> is added

### ISSUE THREAD

**Issue by serSok** [django-ckeditor/django-ckeditor#769]
1. Press button "source"
2. Add context
    ```
        <svg fill="none" viewbox="0 0 1920 397" xmlns="http://www.w3.org/2000/svg"></svg>
        <p>&nbsp;</p>

    ```
3. Save object
4. Again press "source"
5. Contents of the context will now be like this
    ```
        <svg fill="none" viewbox="0 0 1920 397" xmlns="http://www.w3.org/2000/svg"></svg>
        <p>&nbsp;</p>

        <p>&nbsp;</p>
    ```

    added independently - `<p>&nbsp;</p>`

6. Again press "source", without saving object
7. Contents of the context will now be like this
    ```
        <svg fill="none" viewbox="0 0 1920 397" xmlns="http://www.w3.org/2000/svg"></svg>
        <p>&nbsp;</p>

        <p>&nbsp;</p>

        <p>&nbsp;</p>

        <p>&nbsp;</p>

        <p>&nbsp;</p>
    ```
8. etc.

This behavior was observed only when using the tag `<svg>`

**Comment by matthiask** [comment]
Wow, that's ugly.

However, this is a CKEditor 4 behavior and should be reported upstream https://github.com/ckeditor/ckeditor4

You're probably out of luck though since CKEditor 4 has reached its end of life date in Summer 2023.
