### ISSUE TITLE
django-ckeditor-5 toolbar not showing

### ISSUE THREAD

**Issue by memetkayr2** [django-ckeditor/django-ckeditor#770]
I was using django-ckeditor and upgraded to ckeditor-5 due to the end of support, but I can't see it on my front-end. works as it should in admin panel 
admin panel:
![2](https://github.com/django-ckeditor/django-ckeditor/assets/167210551/76a5e1f5-aa68-4e1c-a936-61d36fc5ff41)

  front-end:
![Screenshot_2](https://github.com/django-ckeditor/django-ckeditor/assets/167210551/2546ed71-ff84-401b-a603-12f97f42fa39)

forms.py:
```
class CreateComment(forms.ModelForm):
      """Form for comments to the article."""

      def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          self.fields["comment_content"].required = False

      class Meta:
          model = Comments
          fields = ['comment_content']
          widgets = {
              "comment_content": CKEditor5Widget(
                  attrs={"class": "django_ckeditor_5"}, config_name="extends"
              )
          }
```
html:
    <div class="ck-content">
        {{ comment | safe }}
      </div>

**Comment by matthiask** [comment]
You should report this here: https://github.com/hvlads/django-ckeditor-5
