### ISSUE TITLE
avif support PR

### ISSUE THREAD

**Issue by amirreza8002** [django-ckeditor/django-ckeditor#775]
hi
i did an override on the image backend to support avif
it's a bit messy at the moment as it repeats a lot of code

if you are interested i can clean it up and make a pr

**Comment by matthiask** [comment]
Hi @amirreza8002 

Thank you! I'm not sure that would be a good idea. I wouldn't recommend using django-ckeditor anymore the open source version of CKEditor 4 has unfixed security issues, see https://ckeditor.com/blog/ckeditor-4-end-of-life/ and https://github.com/django-ckeditor/django-ckeditor/issues/761, so further development also makes little sense. Maybe compatibility updates for those unable to switch away from it, but new features really do not seem to make a lot of sense to me.
