### ISSUE TITLE
CSRF token

### ISSUE THREAD

**Issue by lmanzurv** [django-ckeditor/django-ckeditor#84]
I installed ckeditor to allow Rich Text editor with image upload in my models. The problem is that when I try to upload an image to the server, it shows me a Forbidden error stating that there's no CSRF token passed.

How can I upload an image to the server?

Thanks

**Comment by 4nc3str4l** [comment]
I had the same error and it was because i had the ckeditor urls in the wrong place so, if you put the url in:
urlpatterns = patterns(
...,
    url(r'^ckeditor/', include('ckeditor.urls')),
...,
)

**Comment by hoaphumanoid** [comment]
I had the same error as well. The solution was as @4nc3str4l said but, specifically was related to django version, so just let me add something:

    if django.VERSION >= (1, 8):
    urlpatterns = [
        url(r'^$', ckeditor_form_view, name='ckeditor-form'),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^ckeditor/', include('ckeditor_uploader.urls')),
        url(r'^static/(?P<path>.*)$', views.serve),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]
    else:
    from django.conf.urls import patterns

    admin.autodiscover()
    urlpatterns = patterns(
        '',
        url(r'^$', ckeditor_form_view, name='ckeditor-form'),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^ckeditor/', include('ckeditor_uploader.urls')),
        url(r'^static/(?P<path>.*)$', views.serve),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

**Comment by sedrubal** [comment]
I'm running Django 1.8 and have this in `urls.py` but also experience the same problem:

```python
urlpatterns = [
    # auth
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name
    url(r'^logout/$', 'django.contrib.auth.views.logout'),

    # i18n
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # ...

    # ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
```

**Comment by sedrubal** [comment]
Ping?

**Comment by luzfcb** [comment]
https://docs.djangoproject.com/ja/1.9/ref/csrf/#ajax

**Comment by sedrubal** [comment]
Did you post this link for me or as hint for this project? What do I have to do?

**Comment by riklaunim** [comment]
I wonder why url pattern order would change this?

**Comment by riklaunim** [comment]
I wonder if it's related to the uploader being in an iframe and some browsers blocking cookie work inside iframes?

**Comment by Vanpitkinobi** [comment]
I lost the csrf-token error when I put  url(r'^ckeditor/', include('ckeditor_uploader.urls')) before url(r'^admin/', admin.site.urls),

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', admin.site.urls),
    #...
]

**Comment by umeshror** [comment]
Still an open issue?

**Comment by dominz2** [comment]
For me also order of url was a problem
